/**
 * Generiert die idempotente Migration für die Ernährungsform-Abdeckung der
 * coach_meal_library und korrigiert Ernährungsform-Tags bestehender Gerichte.
 *
 * Aufruf: bun run scripts/gen-diet-meal-seed.ts > supabase/migrations/<ts>_diet_meal_library.sql
 */
import { classifyMealDiet } from "../src/lib/diet-compat";

type Cat = "breakfast" | "lunch" | "dinner" | "snack";
type Dish = {
  n: string;
  d: string;
  c: Cat;
  p: number;
  ch: number;
  f: number;
  portion: string;
  ing: [string, number][];
  how: string;
  tags: string[];
  prep: boolean;
  cold: boolean;
  effort: "low" | "medium" | "high";
  budget: "low" | "medium" | "high";
  mp: string;
  mc: string;
  train?: boolean;
  rest?: boolean;
};

const V = "vegan";
const P = "pescetarisch";

const dishes: Dish[] = [
  // ---------------- VEGAN — FRÜHSTÜCK (21) ----------------
  { n: "Porridge mit Sojadrink und Erdnussmus", d: "Warmer Haferbrei mit pflanzlichem Protein", c: "breakfast", p: 21, ch: 58, f: 16, portion: "1 Schale (ca. 430 g)", ing: [["Haferflocken", 70], ["Sojadrink ungesüßt", 250], ["Erdnussmus", 20], ["Banane", 100]], how: "Haferflocken mit Sojadrink aufkochen, quellen lassen, Erdnussmus und Banane unterheben.", tags: [V, "warm", "high_protein", "günstig"], prep: false, cold: false, effort: "low", budget: "low", mp: "Sojadrink", mc: "Haferflocken" },
  { n: "Tofu-Scramble mit Champignons", d: "Herzhaftes Rührtofu-Frühstück mit Pilzen", c: "breakfast", p: 28, ch: 26, f: 18, portion: "1 Pfanne", ing: [["Naturtofu", 200], ["Champignons", 100], ["Vollkornbrot", 60], ["Rapsöl", 10], ["Kurkuma", 2]], how: "Tofu zerbröseln, mit Pilzen anbraten, würzen und mit Brot servieren.", tags: [V, "high_protein", "warm"], prep: false, cold: false, effort: "low", budget: "low", mp: "Tofu", mc: "Vollkornbrot" },
  { n: "Hirse-Porridge mit Apfelkompott", d: "Glutenfreie Alternative zum Haferbrei", c: "breakfast", p: 12, ch: 66, f: 10, portion: "1 Schale", ing: [["Hirse gekocht", 250], ["Hafermilch", 150], ["Apfel", 130], ["Leinsamen geschrotet", 15]], how: "Hirse mit Hafermilch erwärmen, Apfel weich dünsten, alles mischen.", tags: [V, "warm", "günstig"], prep: true, cold: false, effort: "low", budget: "low", mp: "Hirse", mc: "Hirse" },
  { n: "Vollkornbrot mit Hummus und Gurke", d: "Kaltes herzhaftes Frühstück ohne Kochen", c: "breakfast", p: 16, ch: 44, f: 14, portion: "2 Scheiben", ing: [["Vollkornbrot", 100], ["Hummus", 80], ["Gurke", 80], ["Kresse", 5]], how: "Brot mit Hummus bestreichen, Gurke auflegen.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Vollkornbrot" },
  { n: "Sojajoghurt mit Müsli und Birne", d: "Schnelle pflanzliche Frühstücks-Bowl", c: "breakfast", p: 19, ch: 52, f: 12, portion: "1 Bowl", ing: [["Sojajoghurt", 250], ["Vollkornmüsli", 60], ["Birne", 120], ["Sonnenblumenkerne", 10]], how: "Alles in eine Schüssel geben und mischen.", tags: [V, "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "low", mp: "Sojajoghurt", mc: "Müsli" },
  { n: "Protein-Smoothie mit Erbsenprotein und Banane", d: "Trinkfrühstück für eilige Morgen", c: "breakfast", p: 32, ch: 42, f: 8, portion: "1 großes Glas (500 ml)", ing: [["Erbsenprotein", 30], ["Hafermilch", 300], ["Banane", 120], ["Haferflocken", 30]], how: "Alles im Mixer glatt mixen.", tags: [V, "high_protein", "schnell", "pre_workout"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Erbsenprotein", mc: "Banane" },
  { n: "Overnight Oats mit Sojadrink und Himbeeren", d: "Am Vorabend angesetzt, morgens fertig", c: "breakfast", p: 17, ch: 54, f: 11, portion: "1 Glas", ing: [["Haferflocken", 65], ["Sojadrink ungesüßt", 220], ["Himbeeren TK", 80], ["Chiasamen", 12]], how: "Alles im Glas verrühren und über Nacht kühlen.", tags: [V, "mealprep", "kalt", "günstig"], prep: true, cold: true, effort: "low", budget: "low", mp: "Sojadrink", mc: "Haferflocken" },
  { n: "Vollkorntoast mit Avocado und Kichererbsen", d: "Sättigender Toast mit pflanzlichem Eiweiß", c: "breakfast", p: 18, ch: 46, f: 19, portion: "2 Scheiben", ing: [["Vollkorntoast", 80], ["Avocado", 70], ["Kichererbsen", 100], ["Zitrone", 10]], how: "Avocado zerdrücken, mit Kichererbsen auf den Toast geben, würzen.", tags: [V, "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Kichererbsen", mc: "Vollkornbrot" },
  { n: "Bircher Müsli vegan", d: "Klassisches Schweizer Müsli rein pflanzlich", c: "breakfast", p: 15, ch: 60, f: 13, portion: "1 Schale", ing: [["Haferflocken", 70], ["Hafermilch", 200], ["Apfel", 120], ["Mandeln gehackt", 15], ["Rosinen", 15]], how: "Alles mischen und mindestens 30 Minuten ziehen lassen.", tags: [V, "mealprep", "kalt", "klassisch"], prep: true, cold: true, effort: "low", budget: "low", mp: "Hafer", mc: "Haferflocken" },
  { n: "Quinoa-Frühstücksbowl mit Sojajoghurt", d: "Protein-Bowl mit gekochtem Quinoa", c: "breakfast", p: 22, ch: 50, f: 12, portion: "1 Bowl", ing: [["Quinoa gekocht", 180], ["Sojajoghurt", 150], ["Blaubeeren", 80], ["Kürbiskerne", 15]], how: "Quinoa kalt oder warm mit Sojajoghurt und Beeren anrichten.", tags: [V, "mealprep", "high_protein"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Sojajoghurt", mc: "Quinoa" },
  { n: "Kichererbsenmehl-Pfannkuchen mit Spinat", d: "Herzhafte Pancakes mit viel Eiweiß", c: "breakfast", p: 24, ch: 42, f: 14, portion: "2 Pfannkuchen", ing: [["Kichererbsenmehl", 80], ["Wasser", 150], ["Blattspinat", 100], ["Olivenöl", 10]], how: "Mehl mit Wasser verrühren, Spinat zugeben, in der Pfanne backen.", tags: [V, "high_protein", "warm", "günstig"], prep: false, cold: false, effort: "medium", budget: "low", mp: "Kichererbsenmehl", mc: "Kichererbsenmehl" },
  { n: "Haferwaffeln mit Apfelmus", d: "Waffeln aus Haferflocken ohne Ei", c: "breakfast", p: 14, ch: 62, f: 12, portion: "2 Waffeln", ing: [["Haferflocken", 80], ["Hafermilch", 150], ["Apfelmus ungesüßt", 100], ["Rapsöl", 8]], how: "Haferflocken mahlen, mit Hafermilch zum Teig rühren, Waffeln backen.", tags: [V, "warm", "günstig"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Hafer", mc: "Haferflocken" },
  { n: "Erdnussbutter-Bananen-Sandwich", d: "Schnelles Energie-Frühstück to go", c: "breakfast", p: 17, ch: 52, f: 20, portion: "1 Sandwich", ing: [["Vollkornbrot", 100], ["Erdnussbutter", 30], ["Banane", 110]], how: "Brot bestreichen, Bananenscheiben auflegen, zusammenklappen.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Erdnussbutter", mc: "Vollkornbrot" },
  { n: "Sojaquark mit Beeren und Leinsamen", d: "Kalte Proteinquelle für den Morgen", c: "breakfast", p: 26, ch: 24, f: 12, portion: "1 Schale", ing: [["Sojaquark", 250], ["Beerenmischung TK", 100], ["Leinsamen geschrotet", 15]], how: "Sojaquark mit Beeren und Leinsamen verrühren.", tags: [V, "high_protein", "low_carb", "kalt"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Sojaquark", mc: "Beeren" },
  { n: "Hafergrütze mit Zimt und Rosinen", d: "Günstiger warmer Klassiker", c: "breakfast", p: 13, ch: 64, f: 9, portion: "1 Schale", ing: [["Haferflocken kernig", 75], ["Wasser", 250], ["Rosinen", 25], ["Zimt", 2], ["Walnüsse", 10]], how: "Haferflocken in Wasser weich kochen, Rosinen und Zimt zugeben.", tags: [V, "warm", "günstig", "schnell"], prep: false, cold: false, effort: "low", budget: "low", mp: "Hafer", mc: "Haferflocken" },
  { n: "Süßkartoffel-Hash mit Räuchertofu", d: "Herzhaftes Pfannenfrühstück", c: "breakfast", p: 26, ch: 44, f: 16, portion: "1 Pfanne", ing: [["Süßkartoffel", 220], ["Räuchertofu", 150], ["Paprika", 80], ["Rapsöl", 10]], how: "Süßkartoffelwürfel anbraten, Tofu und Paprika zugeben, würzen.", tags: [V, "warm", "high_protein", "mealprep"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Tofu", mc: "Süßkartoffel" },
  { n: "Vollkornbagel mit Räuchertofu-Creme", d: "Kalter Bagel mit pflanzlichem Aufstrich", c: "breakfast", p: 22, ch: 54, f: 14, portion: "1 Bagel", ing: [["Vollkornbagel", 90], ["Räuchertofu", 100], ["Sojajoghurt", 40], ["Rucola", 20]], how: "Tofu mit Sojajoghurt pürieren, Bagel bestreichen und belegen.", tags: [V, "kalt", "schnell", "high_protein"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Tofu", mc: "Bagel" },
  { n: "Green Smoothie Bowl mit Hanfprotein", d: "Grüne Bowl mit Spinat und Mango", c: "breakfast", p: 24, ch: 46, f: 12, portion: "1 Bowl", ing: [["Hanfprotein", 25], ["Blattspinat", 60], ["Mango", 150], ["Hafermilch", 200], ["Haferflocken", 30]], how: "Spinat, Mango und Hafermilch mixen, Protein einrühren, mit Haferflocken toppen.", tags: [V, "kalt", "high_protein"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Hanfprotein", mc: "Mango" },
  { n: "Kichererbsen-Frühstückswrap mit Kala Namak", d: "Wrap mit klassischer Frühstücksfüllung", c: "breakfast", p: 23, ch: 48, f: 15, portion: "1 Wrap", ing: [["Kichererbsenmehl", 60], ["Vollkorn-Wrap", 70], ["Paprika", 70], ["Kala Namak", 2], ["Olivenöl", 8]], how: "Kichererbsenmasse in der Pfanne stocken lassen, mit Paprika im Wrap rollen.", tags: [V, "warm", "high_protein"], prep: false, cold: false, effort: "medium", budget: "low", mp: "Kichererbsenmehl", mc: "Wrap" },
  { n: "Amaranth-Porridge mit Kakao und Nussmus", d: "Schokoladiger Start mit Amaranth", c: "breakfast", p: 18, ch: 54, f: 16, portion: "1 Schale", ing: [["Amaranth gepufft", 50], ["Hafermilch", 250], ["Kakaopulver", 10], ["Mandelmus", 20], ["Banane", 90]], how: "Hafermilch erwärmen, Kakao und Mandelmus einrühren, Amaranth und Banane zugeben.", tags: [V, "warm", "schnell"], prep: false, cold: false, effort: "low", budget: "medium", mp: "Mandelmus", mc: "Amaranth" },
  { n: "Vollkornbrot mit Linsenaufstrich und Tomate", d: "Deftiger Linsenaufstrich auf Vollkornbrot", c: "breakfast", p: 21, ch: 48, f: 12, portion: "2 Scheiben", ing: [["Vollkornbrot", 100], ["Rote Linsen gekocht", 120], ["Tomate", 80], ["Olivenöl", 8], ["Zwiebel", 20]], how: "Linsen mit Zwiebel und Öl pürieren, Brot bestreichen, Tomate auflegen.", tags: [V, "kalt", "mealprep", "günstig"], prep: true, cold: true, effort: "low", budget: "low", mp: "Linsen", mc: "Vollkornbrot" },

  // ---------------- VEGAN — MITTAG (20) ----------------
  { n: "Falafel-Bowl mit Bulgur und Tahinisauce", d: "Orientalische Bowl mit Ofen-Falafel", c: "lunch", p: 28, ch: 68, f: 22, portion: "1 Bowl", ing: [["Falafel (Ofen)", 150], ["Bulgur gekocht", 200], ["Tomate", 80], ["Tahini", 20], ["Zitrone", 10]], how: "Falafel im Ofen backen, mit Bulgur, Gemüse und Tahinisauce anrichten.", tags: [V, "high_protein", "mealprep"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Kichererbsen", mc: "Bulgur" },
  { n: "Vollkornnudeln mit Erbsen-Minz-Pesto", d: "Frisches Pesto mit hohem Erbsenanteil", c: "lunch", p: 26, ch: 74, f: 18, portion: "1 Teller", ing: [["Vollkornnudeln gekocht", 250], ["Erbsen TK", 150], ["Minze", 5], ["Olivenöl", 15], ["Cashews", 20]], how: "Erbsen mit Minze, Cashews und Öl pürieren, unter die Nudeln heben.", tags: [V, "schnell", "high_protein"], prep: true, cold: false, effort: "low", budget: "low", mp: "Erbsen", mc: "Vollkornnudeln" },
  { n: "Erbsen-Kichererbsen-Curry mit Hirse", d: "Cremiges Curry mit doppelter Hülsenfrucht", c: "lunch", p: 27, ch: 72, f: 16, portion: "1 Teller", ing: [["Kichererbsen", 150], ["Erbsen TK", 100], ["Hirse gekocht", 200], ["Kokosmilch light", 80], ["Currypulver", 5]], how: "Hülsenfrüchte in Kokosmilch und Curry köcheln, mit Hirse servieren.", tags: [V, "mealprep", "warm", "günstig"], prep: true, cold: false, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Hirse" },
  { n: "Bohnen-Burrito-Bowl mit Reis", d: "Mexikanische Bowl mit schwarzen Bohnen", c: "lunch", p: 26, ch: 80, f: 14, portion: "1 Bowl", ing: [["Schwarze Bohnen", 180], ["Reis gekocht", 220], ["Mais", 60], ["Salsa", 60], ["Avocado", 40]], how: "Bohnen erwärmen, mit Reis, Mais, Salsa und Avocado schichten.", tags: [V, "mealprep", "günstig"], prep: true, cold: true, effort: "low", budget: "low", mp: "Bohnen", mc: "Reis" },
  { n: "Quinoa-Salat mit schwarzen Bohnen und Mais", d: "Kalter Meal-Prep-Salat fürs Büro", c: "lunch", p: 24, ch: 66, f: 16, portion: "1 Schale", ing: [["Quinoa gekocht", 200], ["Schwarze Bohnen", 150], ["Mais", 60], ["Paprika", 80], ["Olivenöl", 12]], how: "Alles vermengen, mit Limette und Kreuzkümmel abschmecken.", tags: [V, "kalt", "mealprep", "high_protein"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Bohnen", mc: "Quinoa" },
  { n: "Gemüse-Dal mit Basmatireis", d: "Indisches Linsengericht mit Gemüse", c: "lunch", p: 25, ch: 78, f: 12, portion: "1 Teller", ing: [["Rote Linsen", 90], ["Basmatireis gekocht", 200], ["Möhren", 100], ["Passierte Tomaten", 100], ["Rapsöl", 8]], how: "Linsen mit Gemüse und Tomaten weich kochen, mit Reis servieren.", tags: [V, "mealprep", "warm", "günstig"], prep: true, cold: false, effort: "low", budget: "low", mp: "Linsen", mc: "Reis" },
  { n: "Tempeh-Streifen mit Vollkornfladen", d: "Würziger Tempeh im Fladenbrot", c: "lunch", p: 34, ch: 58, f: 20, portion: "1 Fladen", ing: [["Tempeh", 160], ["Vollkornfladenbrot", 100], ["Weißkohlsalat", 80], ["Sojajoghurt", 50], ["Rapsöl", 10]], how: "Tempeh würzen und braten, mit Salat und Sojajoghurt im Fladen servieren.", tags: [V, "high_protein", "warm"], prep: false, cold: false, effort: "medium", budget: "medium", mp: "Tempeh", mc: "Fladenbrot" },
  { n: "Seitangeschnetzeltes mit Vollkornnudeln", d: "Herzhaftes Geschnetzeltes rein pflanzlich", c: "lunch", p: 40, ch: 68, f: 14, portion: "1 Teller", ing: [["Seitan", 180], ["Vollkornnudeln gekocht", 220], ["Champignons", 100], ["Sojacreme", 50], ["Rapsöl", 8]], how: "Seitan mit Pilzen anbraten, mit Sojacreme ablöschen, Nudeln unterheben.", tags: [V, "high_protein", "warm"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Seitan", mc: "Vollkornnudeln" },
  { n: "Kartoffel-Kichererbsen-Curry", d: "Sättigendes Curry ohne Reis", c: "lunch", p: 22, ch: 70, f: 15, portion: "1 Teller", ing: [["Kartoffeln", 300], ["Kichererbsen", 150], ["Kokosmilch light", 100], ["Spinat", 80], ["Currypaste", 15]], how: "Kartoffeln garen, mit Kichererbsen und Kokosmilch köcheln, Spinat unterheben.", tags: [V, "mealprep", "günstig", "warm"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Kichererbsen", mc: "Kartoffeln" },
  { n: "Nudelsalat mit Erbsenprotein-Pesto", d: "Kalter Nudelsalat mit extra Eiweiß", c: "lunch", p: 30, ch: 68, f: 18, portion: "1 Schale", ing: [["Vollkornnudeln gekocht", 230], ["Erbsenprotein", 20], ["Basilikumpesto vegan", 30], ["Kirschtomaten", 100], ["Rucola", 20]], how: "Nudeln auskühlen lassen, mit Pesto und Protein mischen, Gemüse zugeben.", tags: [V, "kalt", "mealprep", "high_protein"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Erbsenprotein", mc: "Vollkornnudeln" },
  { n: "Vegane Linsen-Lasagne", d: "Ofengericht mit Linsenragout", c: "lunch", p: 30, ch: 70, f: 18, portion: "1 Portion", ing: [["Vollkorn-Lasagneplatten", 90], ["Rote Linsen", 90], ["Passierte Tomaten", 200], ["Sojacreme", 80], ["Hefeflocken", 10]], how: "Linsenragout kochen, mit Platten schichten, Sojacreme darüber, 35 Min. backen.", tags: [V, "mealprep", "warm", "klassisch"], prep: true, cold: false, effort: "high", budget: "low", mp: "Linsen", mc: "Lasagneplatten" },
  { n: "Sojageschnetzeltes süß-sauer mit Reis", d: "Asiatischer Klassiker pflanzlich", c: "lunch", p: 36, ch: 76, f: 12, portion: "1 Teller", ing: [["Sojaschnetzel trocken", 60], ["Reis gekocht", 220], ["Paprika", 100], ["Ananas", 60], ["Sojasauce", 15]], how: "Sojaschnetzel einweichen, anbraten, mit Gemüse und Sauce mischen.", tags: [V, "high_protein", "günstig", "mealprep"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Sojaschnetzel", mc: "Reis" },
  { n: "Buddha Bowl mit Edamame und Quinoa", d: "Bunte Bowl mit Sojabohnen", c: "lunch", p: 30, ch: 62, f: 18, portion: "1 Bowl", ing: [["Edamame TK", 150], ["Quinoa gekocht", 200], ["Rotkohl", 80], ["Möhren", 80], ["Sesamöl", 10]], how: "Edamame garen, alles in der Schüssel anrichten, mit Sesamöl beträufeln.", tags: [V, "kalt", "high_protein", "mealprep"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Edamame", mc: "Quinoa" },
  { n: "Vollkorn-Wrap mit Räuchertofu und Gemüse", d: "Handlicher Wrap für unterwegs", c: "lunch", p: 27, ch: 58, f: 17, portion: "1 Wrap", ing: [["Vollkorn-Wrap", 80], ["Räuchertofu", 150], ["Hummus", 40], ["Salat", 40], ["Paprika", 60]], how: "Wrap bestreichen, Tofu und Gemüse einrollen.", tags: [V, "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Tofu", mc: "Wrap" },
  { n: "Weiße-Bohnen-Eintopf mit Vollkornbrot", d: "Deftiger Eintopf für kalte Tage", c: "lunch", p: 26, ch: 66, f: 12, portion: "1 Teller + Brot", ing: [["Weiße Bohnen", 220], ["Möhren", 100], ["Sellerie", 60], ["Gemüsebrühe", 300], ["Vollkornbrot", 60]], how: "Gemüse anschwitzen, mit Brühe und Bohnen 20 Minuten köcheln.", tags: [V, "warm", "günstig", "mealprep"], prep: true, cold: false, effort: "low", budget: "low", mp: "Bohnen", mc: "Vollkornbrot" },
  { n: "Sojaschnetzel-Gemüsepfanne mit Kartoffeln", d: "Bunte Pfanne mit viel Eiweiß", c: "lunch", p: 34, ch: 62, f: 14, portion: "1 Pfanne", ing: [["Sojaschnetzel trocken", 55], ["Kartoffeln", 280], ["Zucchini", 100], ["Zwiebel", 50], ["Rapsöl", 10]], how: "Kartoffeln anbraten, eingeweichte Sojaschnetzel und Gemüse zugeben.", tags: [V, "high_protein", "günstig", "warm"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Sojaschnetzel", mc: "Kartoffeln" },
  { n: "Erbsensuppe mit Vollkornbrot", d: "Klassische deftige Suppe ohne Fleisch", c: "lunch", p: 28, ch: 68, f: 10, portion: "1 großer Teller", ing: [["Trockenerbsen", 100], ["Möhren", 80], ["Kartoffeln", 120], ["Gemüsebrühe", 400], ["Vollkornbrot", 50]], how: "Erbsen mit Gemüse weich kochen, grob pürieren, mit Brot servieren.", tags: [V, "warm", "günstig", "mealprep", "klassisch"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Erbsen", mc: "Kartoffeln" },
  { n: "Bulgur-Pfanne mit Kichererbsen und Spinat", d: "Schnelle One-Pot-Pfanne", c: "lunch", p: 24, ch: 70, f: 14, portion: "1 Pfanne", ing: [["Bulgur gekocht", 220], ["Kichererbsen", 150], ["Blattspinat", 100], ["Olivenöl", 10], ["Zitrone", 10]], how: "Alles in der Pfanne erhitzen, mit Zitrone abschmecken.", tags: [V, "schnell", "mealprep", "günstig"], prep: true, cold: false, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Bulgur" },
  { n: "Reisnudel-Salat mit Erdnusssauce und Tofu", d: "Asiatischer kalter Nudelsalat", c: "lunch", p: 28, ch: 68, f: 20, portion: "1 Schale", ing: [["Reisnudeln gekocht", 200], ["Naturtofu", 150], ["Möhren", 80], ["Erdnussmus", 25], ["Sojasauce", 15]], how: "Tofu anbraten, Sauce anrühren, alles mit Nudeln vermengen.", tags: [V, "kalt", "high_protein"], prep: true, cold: true, effort: "medium", budget: "medium", mp: "Tofu", mc: "Reisnudeln" },
  { n: "Ofengemüse mit Linsen und Tahini", d: "Warmes Ofenblech mit Belugalinsen", c: "lunch", p: 25, ch: 60, f: 18, portion: "1 Blechportion", ing: [["Belugalinsen gekocht", 200], ["Süßkartoffel", 180], ["Blumenkohl", 120], ["Tahini", 20], ["Olivenöl", 10]], how: "Gemüse 25 Minuten backen, mit Linsen mischen, Tahinisauce darüber.", tags: [V, "mealprep", "warm", "high_protein"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Linsen", mc: "Süßkartoffel" },

  // ---------------- VEGAN — ABEND (22) ----------------
  { n: "Tofu-Curry mit Blumenkohlreis", d: "Low-Carb-Curry am Abend", c: "dinner", p: 32, ch: 22, f: 20, portion: "1 Teller", ing: [["Naturtofu", 200], ["Blumenkohlreis", 250], ["Kokosmilch light", 100], ["Currypaste", 15], ["Rapsöl", 10]], how: "Tofu anbraten, Currysauce zugeben, Blumenkohlreis kurz mitgaren.", tags: [V, "low_carb", "high_protein", "warm"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Tofu", mc: "Blumenkohl", train: false },
  { n: "Ofenkartoffel mit Kichererbsen-Guacamole", d: "Sättigend und einfach", c: "dinner", p: 20, ch: 62, f: 18, portion: "1 große Kartoffel", ing: [["Kartoffel", 350], ["Kichererbsen", 120], ["Avocado", 60], ["Limette", 10], ["Olivenöl", 8]], how: "Kartoffel im Ofen garen, Kichererbsen mit Avocado zerdrücken, füllen.", tags: [V, "warm", "günstig"], prep: false, cold: false, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Kartoffeln" },
  { n: "Vegane Bolognese mit Sojahack", d: "Klassische Bolognese rein pflanzlich", c: "dinner", p: 34, ch: 66, f: 14, portion: "1 Teller", ing: [["Sojahack trocken", 55], ["Vollkornspaghetti gekocht", 220], ["Passierte Tomaten", 200], ["Zwiebel", 50], ["Olivenöl", 10]], how: "Sojahack anbraten, mit Tomaten köcheln, über Spaghetti geben.", tags: [V, "high_protein", "klassisch", "mealprep"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Sojahack", mc: "Vollkornnudeln" },
  { n: "Gefüllte Paprika mit Linsen und Reis", d: "Ofengericht mit Hülsenfrüchten", c: "dinner", p: 24, ch: 62, f: 12, portion: "2 Paprika", ing: [["Paprika", 250], ["Rote Linsen gekocht", 150], ["Reis gekocht", 150], ["Passierte Tomaten", 100], ["Olivenöl", 8]], how: "Paprika füllen und 30 Minuten im Ofen garen.", tags: [V, "mealprep", "warm"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Linsen", mc: "Reis" },
  { n: "Kichererbsen-Spinat-Pfanne mit Vollkornbrot", d: "Schnelle Abendpfanne", c: "dinner", p: 24, ch: 50, f: 16, portion: "1 Pfanne + Brot", ing: [["Kichererbsen", 200], ["Blattspinat", 150], ["Vollkornbrot", 60], ["Knoblauch", 5], ["Olivenöl", 12]], how: "Kichererbsen mit Knoblauch anbraten, Spinat zusammenfallen lassen.", tags: [V, "schnell", "günstig", "warm"], prep: false, cold: false, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Vollkornbrot" },
  { n: "Miso-Gemüsesuppe mit Tofu", d: "Leichte japanische Suppe", c: "dinner", p: 22, ch: 20, f: 10, portion: "1 großer Teller", ing: [["Naturtofu", 180], ["Misopaste", 25], ["Pak Choi", 120], ["Frühlingszwiebel", 30], ["Wasser", 400]], how: "Brühe erhitzen, Miso einrühren, Tofu und Gemüse kurz ziehen lassen.", tags: [V, "low_carb", "warm", "schnell"], prep: false, cold: false, effort: "low", budget: "medium", mp: "Tofu", mc: "Gemüse", train: false },
  { n: "Chili sin Carne mit Bohnenmix", d: "Scharfer Bohneneintopf ohne Beilage", c: "dinner", p: 26, ch: 56, f: 12, portion: "1 Schale", ing: [["Kidneybohnen", 180], ["Schwarze Bohnen", 120], ["Passierte Tomaten", 200], ["Mais", 60], ["Olivenöl", 10]], how: "Alles 20 Minuten köcheln und scharf abschmecken.", tags: [V, "mealprep", "günstig", "warm"], prep: true, cold: false, effort: "low", budget: "low", mp: "Bohnen", mc: "Bohnen" },
  { n: "Tempeh-Filets mit Ofengemüse", d: "Marinierter Tempeh vom Blech", c: "dinner", p: 34, ch: 34, f: 22, portion: "1 Blechportion", ing: [["Tempeh", 180], ["Zucchini", 150], ["Paprika", 120], ["Olivenöl", 12], ["Sojasauce", 15]], how: "Tempeh marinieren, mit Gemüse 25 Minuten backen.", tags: [V, "high_protein", "low_carb", "warm"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Tempeh", mc: "Gemüse" },
  { n: "Zucchini-Nudeln mit Erdnuss-Tofu", d: "Leichtes Low-Carb-Abendessen", c: "dinner", p: 30, ch: 22, f: 24, portion: "1 Teller", ing: [["Zucchini", 300], ["Naturtofu", 180], ["Erdnussmus", 20], ["Sojasauce", 15], ["Sesamöl", 8]], how: "Zucchinistreifen kurz braten, Tofu mit Erdnusssauce zugeben.", tags: [V, "low_carb", "high_protein"], prep: false, cold: false, effort: "medium", budget: "medium", mp: "Tofu", mc: "Zucchini", train: false },
  { n: "Vollkornbrot mit Räuchertofu-Aufstrich und Salat", d: "Kaltes Abendbrot pflanzlich", c: "dinner", p: 24, ch: 46, f: 16, portion: "3 Scheiben", ing: [["Vollkornbrot", 100], ["Räuchertofu", 120], ["Sojajoghurt", 40], ["Blattsalat", 60], ["Tomate", 60]], how: "Tofu mit Sojajoghurt pürieren, Brot bestreichen, Salat dazu.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Tofu", mc: "Vollkornbrot" },
  { n: "Bratkartoffeln mit Sojaschnetzel", d: "Deftiger Klassiker mit Eiweiß", c: "dinner", p: 30, ch: 58, f: 16, portion: "1 Pfanne", ing: [["Kartoffeln", 300], ["Sojaschnetzel trocken", 50], ["Zwiebel", 60], ["Rapsöl", 12], ["Paprikapulver", 3]], how: "Kartoffeln knusprig braten, Sojaschnetzel und Zwiebeln zugeben.", tags: [V, "günstig", "warm", "klassisch"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Sojaschnetzel", mc: "Kartoffeln" },
  { n: "Vegane Gemüsepizza mit Hefeschmelz", d: "Pizza mit pflanzlichem Hefeschmelz", c: "dinner", p: 24, ch: 72, f: 18, portion: "1 kleine Pizza", ing: [["Vollkornpizzateig", 180], ["Passierte Tomaten", 80], ["Hefeschmelz", 60], ["Champignons", 80], ["Paprika", 70]], how: "Teig belegen, Hefeschmelz verteilen, 15 Minuten backen.", tags: [V, "warm", "klassisch"], prep: false, cold: false, effort: "medium", budget: "low", mp: "Hefeschmelz", mc: "Pizzateig" },
  { n: "Rote-Linsen-Kokos-Suppe", d: "Cremige Suppe mit Ingwer", c: "dinner", p: 22, ch: 52, f: 14, portion: "1 großer Teller", ing: [["Rote Linsen", 90], ["Kokosmilch light", 120], ["Möhren", 120], ["Ingwer", 8], ["Gemüsebrühe", 350]], how: "Alles weich kochen und pürieren.", tags: [V, "mealprep", "warm", "günstig"], prep: true, cold: false, effort: "low", budget: "low", mp: "Linsen", mc: "Möhren" },
  { n: "Süßkartoffel-Bohnen-Auflauf", d: "Ofenauflauf mit Kidneybohnen", c: "dinner", p: 24, ch: 66, f: 14, portion: "1 Portion", ing: [["Süßkartoffel", 280], ["Kidneybohnen", 180], ["Passierte Tomaten", 120], ["Hefeflocken", 10], ["Olivenöl", 10]], how: "Alles schichten und 30 Minuten backen.", tags: [V, "mealprep", "warm"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Bohnen", mc: "Süßkartoffel" },
  { n: "Grünkohl-Kartoffel-Pfanne mit Räuchertofu", d: "Winterliche Pfanne mit Grünkohl", c: "dinner", p: 28, ch: 50, f: 18, portion: "1 Pfanne", ing: [["Grünkohl", 200], ["Kartoffeln", 250], ["Räuchertofu", 150], ["Rapsöl", 12], ["Senf", 8]], how: "Kartoffeln garen, Grünkohl und Tofu dazugeben, kräftig würzen.", tags: [V, "warm", "günstig", "klassisch"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Tofu", mc: "Kartoffeln" },
  { n: "Couscous mit Ofengemüse und Kichererbsen", d: "Mediterrane Kombination vom Blech", c: "dinner", p: 22, ch: 68, f: 14, portion: "1 Teller", ing: [["Couscous gekocht", 200], ["Kichererbsen", 150], ["Aubergine", 120], ["Paprika", 100], ["Olivenöl", 12]], how: "Gemüse backen, mit Couscous und Kichererbsen mischen.", tags: [V, "mealprep", "warm"], prep: true, cold: true, effort: "medium", budget: "low", mp: "Kichererbsen", mc: "Couscous" },
  { n: "Erbsen-Risotto mit Hefeflocken", d: "Cremiges Risotto ohne Käse", c: "dinner", p: 22, ch: 70, f: 14, portion: "1 Teller", ing: [["Risottoreis gekocht", 250], ["Erbsen TK", 150], ["Hefeflocken", 15], ["Gemüsebrühe", 200], ["Olivenöl", 12]], how: "Reis in Brühe garen, Erbsen und Hefeflocken unterrühren.", tags: [V, "warm", "klassisch"], prep: false, cold: false, effort: "medium", budget: "low", mp: "Erbsen", mc: "Risottoreis" },
  { n: "Falafel mit Sojajoghurt-Gurken-Salat", d: "Leichtes Abendessen mit Dip", c: "dinner", p: 26, ch: 44, f: 20, portion: "6 Falafel + Salat", ing: [["Falafel (Ofen)", 160], ["Sojajoghurt", 120], ["Gurke", 150], ["Minze", 5], ["Olivenöl", 8]], how: "Falafel backen, Sojajoghurt mit Gurke und Minze anrühren.", tags: [V, "kalt", "high_protein"], prep: true, cold: true, effort: "medium", budget: "medium", mp: "Kichererbsen", mc: "Falafel" },
  { n: "Gemüsecurry mit Edamame und Reis", d: "Currypfanne mit Sojabohnen", c: "dinner", p: 28, ch: 64, f: 14, portion: "1 Teller", ing: [["Edamame TK", 160], ["Reis gekocht", 200], ["Brokkoli", 120], ["Kokosmilch light", 80], ["Currypulver", 5]], how: "Gemüse und Edamame in Kokossauce garen, mit Reis servieren.", tags: [V, "high_protein", "mealprep", "warm"], prep: true, cold: false, effort: "low", budget: "medium", mp: "Edamame", mc: "Reis" },
  { n: "Pilz-Stroganoff mit Vollkornnudeln", d: "Cremige Pilzpfanne ohne Sahne", c: "dinner", p: 22, ch: 66, f: 16, portion: "1 Teller", ing: [["Champignons", 250], ["Vollkornnudeln gekocht", 220], ["Sojacreme", 80], ["Zwiebel", 50], ["Rapsöl", 10]], how: "Pilze scharf anbraten, mit Sojacreme binden, Nudeln zugeben.", tags: [V, "warm", "günstig", "klassisch"], prep: true, cold: false, effort: "medium", budget: "low", mp: "Champignons", mc: "Vollkornnudeln" },
  { n: "Weiße Bohnen auf Vollkorntoast", d: "Schnelle Baked Beans selbst gemacht", c: "dinner", p: 24, ch: 62, f: 10, portion: "2 Scheiben Toast", ing: [["Weiße Bohnen", 250], ["Passierte Tomaten", 120], ["Vollkorntoast", 80], ["Zwiebel", 40], ["Olivenöl", 8]], how: "Bohnen in Tomatensauce köcheln, auf getoastetem Brot servieren.", tags: [V, "schnell", "günstig", "warm"], prep: true, cold: false, effort: "low", budget: "low", mp: "Bohnen", mc: "Vollkornbrot" },
  { n: "Buchweizen-Gemüsepfanne mit Nüssen", d: "Nussige Pfanne mit Buchweizen", c: "dinner", p: 20, ch: 60, f: 20, portion: "1 Pfanne", ing: [["Buchweizen gekocht", 220], ["Zucchini", 120], ["Möhren", 100], ["Walnüsse", 25], ["Olivenöl", 10]], how: "Gemüse anbraten, Buchweizen und Nüsse untermischen.", tags: [V, "warm", "mealprep"], prep: true, cold: false, effort: "low", budget: "medium", mp: "Buchweizen", mc: "Buchweizen" },

  // ---------------- VEGAN — SNACKS (17) ----------------
  { n: "Sojajoghurt mit Proteinpulver und Beeren", d: "Schneller Proteinsnack", c: "snack", p: 28, ch: 20, f: 6, portion: "1 Becher", ing: [["Sojajoghurt", 200], ["Erbsenprotein", 20], ["Beerenmischung TK", 80]], how: "Protein unter den Sojajoghurt rühren, Beeren zugeben.", tags: [V, "high_protein", "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Sojajoghurt", mc: "Beeren" },
  { n: "Geröstete Erdnüsse ungesalzen", d: "Kompakter Energie-Snack", c: "snack", p: 12, ch: 8, f: 24, portion: "40 g", ing: [["Erdnüsse geröstet", 40]], how: "Portionieren und genießen.", tags: [V, "kalt", "schnell", "low_carb", "günstig"], prep: true, cold: true, effort: "low", budget: "low", mp: "Erdnüsse", mc: "Erdnüsse" },
  { n: "Hummus mit Vollkornknäckebrot", d: "Herzhafter Snack für zwischendurch", c: "snack", p: 11, ch: 30, f: 12, portion: "3 Knäcke + Dip", ing: [["Hummus", 80], ["Vollkornknäckebrot", 40]], how: "Knäckebrot mit Hummus bestreichen.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Knäckebrot" },
  { n: "Veganer Proteinshake mit Hafermilch", d: "Post-Workout-Shake pflanzlich", c: "snack", p: 30, ch: 24, f: 6, portion: "1 Shaker (400 ml)", ing: [["Erbsen-Reis-Protein", 30], ["Hafermilch", 300]], how: "Protein mit Hafermilch shaken.", tags: [V, "high_protein", "post_workout", "schnell"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Pflanzenprotein", mc: "Hafermilch" },
  { n: "Geröstete Kichererbsen", d: "Knuspriger Ofensnack", c: "snack", p: 13, ch: 30, f: 8, portion: "150 g", ing: [["Kichererbsen", 150], ["Olivenöl", 6], ["Paprikapulver", 3]], how: "Kichererbsen mit Öl und Gewürzen 25 Minuten im Ofen rösten.", tags: [V, "mealprep", "kalt", "günstig"], prep: true, cold: true, effort: "medium", budget: "low", mp: "Kichererbsen", mc: "Kichererbsen" },
  { n: "Reiswaffeln mit Erdnussmus und Banane", d: "Schneller Kohlenhydrat-Snack", c: "snack", p: 9, ch: 40, f: 12, portion: "3 Reiswaffeln", ing: [["Reiswaffeln", 30], ["Erdnussmus", 20], ["Banane", 80]], how: "Reiswaffeln bestreichen und mit Bananenscheiben belegen.", tags: [V, "kalt", "schnell", "pre_workout"], prep: false, cold: true, effort: "low", budget: "low", mp: "Erdnussmus", mc: "Reiswaffeln" },
  { n: "Kakao-Sojadrink", d: "Trinkbarer Snack mit Eiweiß", c: "snack", p: 14, ch: 22, f: 8, portion: "1 Glas (350 ml)", ing: [["Sojadrink ungesüßt", 350], ["Kakaopulver", 12], ["Ahornsirup", 8]], how: "Sojadrink erwärmen, Kakao und Sirup einrühren.", tags: [V, "warm", "schnell", "günstig"], prep: false, cold: false, effort: "low", budget: "low", mp: "Sojadrink", mc: "Kakao" },
  { n: "Kürbiskerne und Cashews", d: "Mineralstoffreicher Nussmix", c: "snack", p: 12, ch: 12, f: 22, portion: "40 g", ing: [["Kürbiskerne", 20], ["Cashewkerne", 20]], how: "Mischen und portionieren.", tags: [V, "kalt", "schnell", "mealprep"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Kerne", mc: "Nüsse" },
  { n: "Knäckebrot mit Avocado und Tomate", d: "Frischer herzhafter Snack", c: "snack", p: 7, ch: 26, f: 14, portion: "3 Scheiben", ing: [["Vollkornknäckebrot", 40], ["Avocado", 60], ["Tomate", 60]], how: "Avocado zerdrücken, aufstreichen, Tomate auflegen.", tags: [V, "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "low", mp: "Avocado", mc: "Knäckebrot" },
  { n: "Energy Balls mit Datteln und Haferflocken", d: "Selbstgemachte Kugeln für die Woche", c: "snack", p: 8, ch: 44, f: 12, portion: "4 Kugeln", ing: [["Datteln", 60], ["Haferflocken", 40], ["Mandelmus", 15], ["Kakaopulver", 5]], how: "Alles im Mixer zerkleinern, Kugeln formen, kühlen.", tags: [V, "mealprep", "kalt", "pre_workout"], prep: true, cold: true, effort: "medium", budget: "low", mp: "Mandelmus", mc: "Datteln" },
  { n: "Edamame-Dip mit Gurkensticks", d: "Grüner Proteindip", c: "snack", p: 16, ch: 16, f: 10, portion: "1 Schälchen", ing: [["Edamame TK", 150], ["Gurke", 120], ["Olivenöl", 8], ["Zitrone", 10]], how: "Edamame garen und pürieren, mit Gurkensticks servieren.", tags: [V, "high_protein", "low_carb", "kalt"], prep: true, cold: true, effort: "low", budget: "medium", mp: "Edamame", mc: "Gurke" },
  { n: "Bananen-Erdnuss-Shake mit Sojadrink", d: "Kalorienreicher Aufbau-Shake", c: "snack", p: 18, ch: 40, f: 18, portion: "1 Glas (450 ml)", ing: [["Sojadrink ungesüßt", 300], ["Banane", 120], ["Erdnussmus", 25]], how: "Alles glatt mixen.", tags: [V, "schnell", "post_workout"], prep: false, cold: true, effort: "low", budget: "low", mp: "Sojadrink", mc: "Banane" },
  { n: "Sojajoghurt mit Granola", d: "Süßer Löffelsnack", c: "snack", p: 13, ch: 38, f: 12, portion: "1 Becher", ing: [["Sojajoghurt", 200], ["Granola", 45]], how: "Granola über den Sojajoghurt geben.", tags: [V, "kalt", "schnell"], prep: false, cold: true, effort: "low", budget: "low", mp: "Sojajoghurt", mc: "Granola" },
  { n: "Mini-Wrap mit Hummus und Rucola", d: "Handlicher Snack für unterwegs", c: "snack", p: 10, ch: 32, f: 11, portion: "1 Mini-Wrap", ing: [["Vollkorn-Wrap", 45], ["Hummus", 50], ["Rucola", 20]], how: "Wrap bestreichen, Rucola einrollen.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Kichererbsen", mc: "Wrap" },
  { n: "Apfelscheiben mit Zimt und Walnüssen", d: "Fruchtiger Snack mit gesunden Fetten", c: "snack", p: 5, ch: 24, f: 14, portion: "1 Apfel + Nüsse", ing: [["Apfel", 160], ["Walnüsse", 20], ["Zimt", 2]], how: "Apfel schneiden, mit Zimt bestreuen, Nüsse dazu.", tags: [V, "kalt", "schnell", "günstig"], prep: false, cold: true, effort: "low", budget: "low", mp: "Walnüsse", mc: "Apfel" },
  { n: "Sojaquark mit Kakao", d: "Pflanzlicher Proteinpudding", c: "snack", p: 24, ch: 14, f: 8, portion: "1 Schale", ing: [["Sojaquark", 220], ["Kakaopulver", 10], ["Süßstoff", 2]], how: "Kakao unter den Sojaquark rühren.", tags: [V, "high_protein", "low_carb", "kalt"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Sojaquark", mc: "Kakao" },
  { n: "Selbstgemachtes Popcorn", d: "Leichter Abendsnack", c: "snack", p: 5, ch: 32, f: 8, portion: "1 Schüssel", ing: [["Popcornmais", 40], ["Rapsöl", 7]], how: "Mais im Topf mit wenig Öl aufpoppen, leicht salzen.", tags: [V, "warm", "günstig", "schnell"], prep: false, cold: true, effort: "low", budget: "low", mp: "Mais", mc: "Mais" },

  // ---------------- PESCETARISCH (12) ----------------
  { n: "Vollkornbrot mit Makrele und Meerrettich", d: "Kräftiges Fischfrühstück", c: "breakfast", p: 30, ch: 38, f: 20, portion: "2 Scheiben", ing: [["Vollkornbrot", 90], ["Räuchermakrele", 100], ["Meerrettich", 15], ["Gurke", 60]], how: "Makrele zerpflücken, mit Meerrettich auf dem Brot verteilen.", tags: [P, "kalt", "high_protein"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Makrele", mc: "Vollkornbrot" },
  { n: "Matjesbrot mit Zwiebeln", d: "Norddeutscher Klassiker", c: "breakfast", p: 26, ch: 40, f: 18, portion: "2 Scheiben", ing: [["Vollkornbrot", 100], ["Matjesfilet", 90], ["Zwiebel", 40], ["Apfel", 50]], how: "Matjes auf Brot legen, mit Zwiebel- und Apfelscheiben belegen.", tags: [P, "kalt", "klassisch"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Matjes", mc: "Vollkornbrot" },
  { n: "Sardinen auf Vollkornknäckebrot", d: "Omega-3-reicher Start", c: "breakfast", p: 27, ch: 26, f: 16, portion: "4 Knäcke", ing: [["Sardinen in Öl abgetropft", 90], ["Vollkornknäckebrot", 50], ["Tomate", 60], ["Zitrone", 10]], how: "Sardinen auf Knäckebrot verteilen, Tomate und Zitrone dazu.", tags: [P, "kalt", "schnell", "high_protein"], prep: false, cold: true, effort: "low", budget: "low", mp: "Sardinen", mc: "Knäckebrot" },
  { n: "Kabeljau mit Kartoffeln und Senfsauce", d: "Klassisches Fischgericht", c: "lunch", p: 42, ch: 52, f: 14, portion: "1 Teller", ing: [["Kabeljaufilet", 200], ["Kartoffeln", 280], ["Senf", 15], ["Sojacreme", 60], ["Rapsöl", 8]], how: "Fisch garen, Senfsauce anrühren, mit Kartoffeln servieren.", tags: [P, "klassisch", "high_protein"], prep: false, cold: false, effort: "medium", budget: "medium", mp: "Kabeljau", mc: "Kartoffeln" },
  { n: "Garnelen-Nudelsalat mit Zitrone", d: "Frischer Salat fürs Büro", c: "lunch", p: 36, ch: 58, f: 14, portion: "1 Schale", ing: [["Garnelen", 180], ["Vollkornnudeln gekocht", 200], ["Kirschtomaten", 100], ["Rucola", 30], ["Olivenöl", 12]], how: "Garnelen kurz braten, mit Nudeln und Gemüse mischen.", tags: [P, "kalt", "mealprep", "high_protein"], prep: true, cold: true, effort: "medium", budget: "high", mp: "Garnelen", mc: "Vollkornnudeln" },
  { n: "Fischcurry mit Pangasius und Reis", d: "Mildes Curry mit Weißfisch", c: "lunch", p: 38, ch: 66, f: 14, portion: "1 Teller", ing: [["Pangasiusfilet", 200], ["Reis gekocht", 220], ["Kokosmilch light", 100], ["Paprika", 80], ["Currypaste", 12]], how: "Fisch in Currysauce garen, mit Reis servieren.", tags: [P, "warm", "mealprep"], prep: true, cold: false, effort: "medium", budget: "medium", mp: "Pangasius", mc: "Reis" },
  { n: "Zanderfilet mit Rahmspinat und Kartoffeln", d: "Feines Abendessen mit Süßwasserfisch", c: "dinner", p: 42, ch: 44, f: 16, portion: "1 Teller", ing: [["Zanderfilet", 200], ["Blattspinat", 200], ["Kartoffeln", 220], ["Sojacreme", 60], ["Olivenöl", 10]], how: "Zander braten, Spinat mit Sojacreme binden, Kartoffeln dazu.", tags: [P, "high_protein", "warm"], prep: false, cold: false, effort: "medium", budget: "high", mp: "Zander", mc: "Kartoffeln" },
  { n: "Miesmuscheln in Tomatensud mit Vollkornbrot", d: "Mediterranes Muschelgericht", c: "dinner", p: 34, ch: 42, f: 12, portion: "1 Topf", ing: [["Miesmuscheln", 500], ["Passierte Tomaten", 200], ["Vollkornbrot", 60], ["Knoblauch", 8], ["Olivenöl", 10]], how: "Muscheln im Tomatensud öffnen lassen, mit Brot servieren.", tags: [P, "warm", "klassisch"], prep: false, cold: false, effort: "medium", budget: "medium", mp: "Miesmuscheln", mc: "Vollkornbrot" },
  { n: "Fischfrikadellen mit Kartoffelsalat", d: "Hausmannskost mit Seelachs", c: "dinner", p: 38, ch: 50, f: 18, portion: "2 Frikadellen + Salat", ing: [["Seelachsfilet", 200], ["Kartoffeln", 250], ["Zwiebel", 40], ["Joghurtdressing", 60], ["Rapsöl", 10]], how: "Fisch hacken, Frikadellen formen und braten, Kartoffelsalat dazu.", tags: [P, "klassisch", "mealprep"], prep: true, cold: true, effort: "high", budget: "medium", mp: "Seelachs", mc: "Kartoffeln" },
  { n: "Makrelenfilet auf Gurkenscheiben", d: "Low-Carb-Snack mit Omega-3", c: "snack", p: 20, ch: 4, f: 14, portion: "1 Portion", ing: [["Räuchermakrele", 80], ["Gurke", 120], ["Zitrone", 10]], how: "Makrele auf Gurkenscheiben setzen, Zitrone darüber.", tags: [P, "low_carb", "kalt", "high_protein"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Makrele", mc: "Gurke" },
  { n: "Räucherforelle auf Knäckebrot", d: "Herzhafter Fischsnack", c: "snack", p: 22, ch: 20, f: 8, portion: "3 Knäcke", ing: [["Räucherforellenfilet", 90], ["Vollkornknäckebrot", 35], ["Frischkäse light", 30], ["Dill", 3]], how: "Knäckebrot bestreichen und mit Forelle belegen.", tags: [P, "kalt", "high_protein", "schnell"], prep: false, cold: true, effort: "low", budget: "medium", mp: "Forelle", mc: "Knäckebrot" },
  { n: "Shrimps-Cocktail mit Joghurtdip", d: "Leichter Proteinsnack", c: "snack", p: 24, ch: 8, f: 6, portion: "1 Schälchen", ing: [["Garnelen gegart", 130], ["Joghurt 1,5%", 60], ["Tomatenmark", 15], ["Zitrone", 10]], how: "Dip anrühren, Garnelen darin wenden.", tags: [P, "low_carb", "kalt", "high_protein"], prep: false, cold: true, effort: "low", budget: "high", mp: "Garnelen", mc: "Gurke" },
];

function q(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}
function arr(items: string[]): string {
  return items.length ? `ARRAY[${items.map(q).join(",")}]::text[]` : "ARRAY[]::text[]";
}

// --- Sanity: Duplikate innerhalb der Datei + Klassifizierung prüfen ---
const seen = new Set<string>();
const misclassified: string[] = [];
for (const d of dishes) {
  const key = `${d.n}|${d.c}`;
  if (seen.has(key)) throw new Error(`Duplikat in Seed-Daten: ${key}`);
  seen.add(key);
  const cls = classifyMealDiet({
    name: d.n,
    description: d.d,
    tags: d.tags,
    ingredients: d.ing.map(([name]) => ({ name })),
    main_protein: d.mp,
  });
  const expected = d.tags.includes(V) ? "vegan" : "pescetarian";
  if (cls !== expected) misclassified.push(`${d.n}: ${cls} (erwartet ${expected})`);
}

if (misclassified.length) throw new Error("Falsch klassifiziert:\n" + misclassified.join("\n"));

const rows = dishes.map((d) => {
  const kcal = Math.round(4 * d.p + 4 * d.ch + 9 * d.f);
  const ing = JSON.stringify(d.ing.map(([name, amount_g]) => ({ name, amount_g })));
  return `  (${q(d.n)}, ${q(d.d)}, ${q(d.c)}::meal_slot_kind, ${kcal}, ${d.p}, ${d.ch}, ${d.f}, ${q(d.portion)},
   ${q(ing)}::jsonb, ${q(d.how)}, ${arr(d.tags)}, ARRAY[]::text[],
   ${d.train ?? true}, ${d.rest ?? true}, ${d.prep}, ${d.cold},
   ${q(d.effort)}::meal_effort_level, ${q(d.budget)}::meal_budget_level, ${q(d.mp)}, ${q(d.mc)})`;
});

// --- Tag-Korrekturen: reine SQL-Logik (gleiche Marker wie diet-compat.ts) ---
const updates: string[] = [];
const sql = `-- BodyFuel: Gerichtsbibliothek für alle Ernährungsformen (idempotent)
-- 1) Ernährungsform-Tags bestehender Gerichte korrigieren (inhaltsbasiert)
${updates.join("\n")}

-- 2) Neue Gerichte ergänzen (nur wenn Name+Kategorie noch nicht existiert)
INSERT INTO public.coach_meal_library (
  name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
  ingredients, instructions, tags, no_go_ingredients,
  suitable_training, suitable_rest, mealprep_ok, eat_cold,
  effort, budget, main_protein, main_carb, is_system, is_active
)
SELECT s.name, s.description, s.category, s.kcal, s.protein_g, s.carbs_g, s.fat_g, s.portion_label,
       s.ingredients, s.instructions, s.tags, s.no_go_ingredients,
       s.suitable_training, s.suitable_rest, s.mealprep_ok, s.eat_cold,
       s.effort, s.budget, s.main_protein, s.main_carb, true, true
FROM (VALUES
${rows.join(",\n")}
) AS s(name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
       ingredients, instructions, tags, no_go_ingredients,
       suitable_training, suitable_rest, mealprep_ok, eat_cold,
       effort, budget, main_protein, main_carb)
WHERE NOT EXISTS (
  SELECT 1 FROM public.coach_meal_library m
  WHERE lower(m.name) = lower(s.name) AND m.category = s.category
);
`;
process.stdout.write(sql);
process.stderr.write(`Gerichte: ${dishes.length}, Tag-Updates: ${updates.length}\n`);
