/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as StrengthCheckRouteImport } from './routes/strength-check'
import { Route as SmartRouteImport } from './routes/smart'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyChecklistRouteImport } from './routes/daily-checklist'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackerIndexRouteImport } from './routes/tracker.index'
import { Route as SmartIndexRouteImport } from './routes/smart.index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as BullsIndexRouteImport } from './routes/bulls.index'
import { Route as TrackerSignupRouteImport } from './routes/tracker.signup'
import { Route as TrackerLoginRouteImport } from './routes/tracker.login'
import { Route as TrackerAppRouteImport } from './routes/tracker.app'
import { Route as SmartSignupRouteImport } from './routes/smart.signup'
import { Route as OnboardingSmartNutritionRouteImport } from './routes/onboarding.smart-nutrition'
import { Route as OnboardingSmartRouteImport } from './routes/onboarding.smart'
import { Route as NutritionTrackingRouteImport } from './routes/nutrition.tracking'
import { Route as NutritionShoppingRouteImport } from './routes/nutrition.shopping'
import { Route as NutritionRecipeFromIngredientsRouteImport } from './routes/nutrition.recipe-from-ingredients'
import { Route as NutritionFavoritesRouteImport } from './routes/nutrition.favorites'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CoachReviewsRouteImport } from './routes/coach.reviews'
import { Route as CoachPackageRequestsRouteImport } from './routes/coach.package-requests'
import { Route as CoachLeadsRouteImport } from './routes/coach.leads'
import { Route as CoachGiftsRouteImport } from './routes/coach.gifts'
import { Route as CoachCustomersRouteImport } from './routes/coach.customers'
import { Route as CoachClientIdRouteImport } from './routes/coach.$clientId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BullsWeightRouteImport } from './routes/bulls.weight'
import { Route as BullsTrainingRouteImport } from './routes/bulls.training'
import { Route as BullsRecoveryRouteImport } from './routes/bulls.recovery'
import { Route as BullsPhotosRouteImport } from './routes/bulls.photos'
import { Route as BullsNutritionRouteImport } from './routes/bulls.nutrition'
import { Route as BullsBenchmarksRouteImport } from './routes/bulls.benchmarks'
import { Route as TrackerAppIndexRouteImport } from './routes/tracker.app.index'
import { Route as CoachCustomersIndexRouteImport } from './routes/coach.customers.index'
import { Route as TrackerAppWeightRouteImport } from './routes/tracker.app.weight'
import { Route as TrackerAppWaterRouteImport } from './routes/tracker.app.water'
import { Route as TrackerAppTrainingRouteImport } from './routes/tracker.app.training'
import { Route as TrackerAppProfileRouteImport } from './routes/tracker.app.profile'
import { Route as TrackerAppNutritionRouteImport } from './routes/tracker.app.nutrition'
import { Route as TrackerAppActivityRouteImport } from './routes/tracker.app.activity'
import { Route as TrackerAppAchievementsRouteImport } from './routes/tracker.app.achievements'
import { Route as SmartGiftCodeRouteImport } from './routes/smart.gift.$code'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CoachPlanPreviewPlanIdRouteImport } from './routes/coach.plan-preview.$planId'
import { Route as CoachCustomersNewRouteImport } from './routes/coach.customers.new'
import { Route as CoachCustomersUserIdRouteImport } from './routes/coach.customers.$userId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTrialRemindersRouteImport } from './routes/api/public/hooks/trial-reminders'
import { Route as ApiPublicHooksSendFeatureNewsRouteImport } from './routes/api/public/hooks/send-feature-news'
import { Route as ApiPublicHooksRegenTrainingPlansRouteImport } from './routes/api/public/hooks/regen-training-plans'
import { Route as ApiPublicHooksRegenNutritionPlansRouteImport } from './routes/api/public/hooks/regen-nutrition-plans'
import { Route as ApiPublicHooksPlanRotationRouteImport } from './routes/api/public/hooks/plan-rotation'
import { Route as ApiPublicHooksCoachDailySummaryRouteImport } from './routes/api/public/hooks/coach-daily-summary'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthCheckRoute = StrengthCheckRouteImport.update({
  id: '/strength-check',
  path: '/strength-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartRoute = SmartRouteImport.update({
  id: '/smart',
  path: '/smart',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyChecklistRoute = DailyChecklistRouteImport.update({
  id: '/daily-checklist',
  path: '/daily-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartIndexRoute = SmartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SmartRoute,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutritionRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const BullsIndexRoute = BullsIndexRouteImport.update({
  id: '/bulls/',
  path: '/bulls/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerSignupRoute = TrackerSignupRouteImport.update({
  id: '/tracker/signup',
  path: '/tracker/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerLoginRoute = TrackerLoginRouteImport.update({
  id: '/tracker/login',
  path: '/tracker/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerAppRoute = TrackerAppRouteImport.update({
  id: '/tracker/app',
  path: '/tracker/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSignupRoute = SmartSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => SmartRoute,
} as any)
const OnboardingSmartNutritionRoute =
  OnboardingSmartNutritionRouteImport.update({
    id: '/onboarding/smart-nutrition',
    path: '/onboarding/smart-nutrition',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSmartRoute = OnboardingSmartRouteImport.update({
  id: '/onboarding/smart',
  path: '/onboarding/smart',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionTrackingRoute = NutritionTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionShoppingRoute = NutritionShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionRecipeFromIngredientsRoute =
  NutritionRecipeFromIngredientsRouteImport.update({
    id: '/recipe-from-ingredients',
    path: '/recipe-from-ingredients',
    getParentRoute: () => NutritionRoute,
  } as any)
const NutritionFavoritesRoute = NutritionFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => NutritionRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachReviewsRoute = CoachReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CoachRoute,
} as any)
const CoachPackageRequestsRoute = CoachPackageRequestsRouteImport.update({
  id: '/package-requests',
  path: '/package-requests',
  getParentRoute: () => CoachRoute,
} as any)
const CoachLeadsRoute = CoachLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CoachRoute,
} as any)
const CoachGiftsRoute = CoachGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCustomersRoute = CoachCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientIdRoute = CoachClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsWeightRoute = BullsWeightRouteImport.update({
  id: '/bulls/weight',
  path: '/bulls/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsTrainingRoute = BullsTrainingRouteImport.update({
  id: '/bulls/training',
  path: '/bulls/training',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsRecoveryRoute = BullsRecoveryRouteImport.update({
  id: '/bulls/recovery',
  path: '/bulls/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsPhotosRoute = BullsPhotosRouteImport.update({
  id: '/bulls/photos',
  path: '/bulls/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsNutritionRoute = BullsNutritionRouteImport.update({
  id: '/bulls/nutrition',
  path: '/bulls/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const BullsBenchmarksRoute = BullsBenchmarksRouteImport.update({
  id: '/bulls/benchmarks',
  path: '/bulls/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerAppIndexRoute = TrackerAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackerAppRoute,
} as any)
const CoachCustomersIndexRoute = CoachCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const TrackerAppWeightRoute = TrackerAppWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppWaterRoute = TrackerAppWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppTrainingRoute = TrackerAppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppProfileRoute = TrackerAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppNutritionRoute = TrackerAppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppActivityRoute = TrackerAppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TrackerAppRoute,
} as any)
const TrackerAppAchievementsRoute = TrackerAppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => TrackerAppRoute,
} as any)
const SmartGiftCodeRoute = SmartGiftCodeRouteImport.update({
  id: '/gift/$code',
  path: '/gift/$code',
  getParentRoute: () => SmartRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachPlanPreviewPlanIdRoute = CoachPlanPreviewPlanIdRouteImport.update({
  id: '/plan-preview/$planId',
  path: '/plan-preview/$planId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCustomersNewRoute = CoachCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const CoachCustomersUserIdRoute = CoachCustomersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialRemindersRoute =
  ApiPublicHooksTrialRemindersRouteImport.update({
    id: '/api/public/hooks/trial-reminders',
    path: '/api/public/hooks/trial-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendFeatureNewsRoute =
  ApiPublicHooksSendFeatureNewsRouteImport.update({
    id: '/api/public/hooks/send-feature-news',
    path: '/api/public/hooks/send-feature-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRegenTrainingPlansRoute =
  ApiPublicHooksRegenTrainingPlansRouteImport.update({
    id: '/api/public/hooks/regen-training-plans',
    path: '/api/public/hooks/regen-training-plans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRegenNutritionPlansRoute =
  ApiPublicHooksRegenNutritionPlansRouteImport.update({
    id: '/api/public/hooks/regen-nutrition-plans',
    path: '/api/public/hooks/regen-nutrition-plans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlanRotationRoute =
  ApiPublicHooksPlanRotationRouteImport.update({
    id: '/api/public/hooks/plan-rotation',
    path: '/api/public/hooks/plan-rotation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCoachDailySummaryRoute =
  ApiPublicHooksCoachDailySummaryRouteImport.update({
    id: '/api/public/hooks/coach-daily-summary',
    path: '/api/public/hooks/coach-daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/coach': typeof CoachRouteWithChildren
  '/community': typeof CommunityRoute
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/messages': typeof MessagesRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ranking': typeof RankingRoute
  '/smart': typeof SmartRouteWithChildren
  '/strength-check': typeof StrengthCheckRoute
  '/training': typeof TrainingRoute
  '/trial': typeof TrialRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/bulls/benchmarks': typeof BullsBenchmarksRoute
  '/bulls/nutrition': typeof BullsNutritionRoute
  '/bulls/photos': typeof BullsPhotosRoute
  '/bulls/recovery': typeof BullsRecoveryRoute
  '/bulls/training': typeof BullsTrainingRoute
  '/bulls/weight': typeof BullsWeightRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/customers': typeof CoachCustomersRouteWithChildren
  '/coach/gifts': typeof CoachGiftsRoute
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/coach/reviews': typeof CoachReviewsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/nutrition/favorites': typeof NutritionFavoritesRoute
  '/nutrition/recipe-from-ingredients': typeof NutritionRecipeFromIngredientsRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/onboarding/smart': typeof OnboardingSmartRoute
  '/onboarding/smart-nutrition': typeof OnboardingSmartNutritionRoute
  '/smart/signup': typeof SmartSignupRoute
  '/tracker/app': typeof TrackerAppRouteWithChildren
  '/tracker/login': typeof TrackerLoginRoute
  '/tracker/signup': typeof TrackerSignupRoute
  '/bulls/': typeof BullsIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/smart/': typeof SmartIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/plan-preview/$planId': typeof CoachPlanPreviewPlanIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/smart/gift/$code': typeof SmartGiftCodeRoute
  '/tracker/app/achievements': typeof TrackerAppAchievementsRoute
  '/tracker/app/activity': typeof TrackerAppActivityRoute
  '/tracker/app/nutrition': typeof TrackerAppNutritionRoute
  '/tracker/app/profile': typeof TrackerAppProfileRoute
  '/tracker/app/training': typeof TrackerAppTrainingRoute
  '/tracker/app/water': typeof TrackerAppWaterRoute
  '/tracker/app/weight': typeof TrackerAppWeightRoute
  '/coach/customers/': typeof CoachCustomersIndexRoute
  '/tracker/app/': typeof TrackerAppIndexRoute
  '/api/public/hooks/coach-daily-summary': typeof ApiPublicHooksCoachDailySummaryRoute
  '/api/public/hooks/plan-rotation': typeof ApiPublicHooksPlanRotationRoute
  '/api/public/hooks/regen-nutrition-plans': typeof ApiPublicHooksRegenNutritionPlansRoute
  '/api/public/hooks/regen-training-plans': typeof ApiPublicHooksRegenTrainingPlansRoute
  '/api/public/hooks/send-feature-news': typeof ApiPublicHooksSendFeatureNewsRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ranking': typeof RankingRoute
  '/strength-check': typeof StrengthCheckRoute
  '/training': typeof TrainingRoute
  '/trial': typeof TrialRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/bulls/benchmarks': typeof BullsBenchmarksRoute
  '/bulls/nutrition': typeof BullsNutritionRoute
  '/bulls/photos': typeof BullsPhotosRoute
  '/bulls/recovery': typeof BullsRecoveryRoute
  '/bulls/training': typeof BullsTrainingRoute
  '/bulls/weight': typeof BullsWeightRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/gifts': typeof CoachGiftsRoute
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/coach/reviews': typeof CoachReviewsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/nutrition/favorites': typeof NutritionFavoritesRoute
  '/nutrition/recipe-from-ingredients': typeof NutritionRecipeFromIngredientsRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/onboarding/smart': typeof OnboardingSmartRoute
  '/onboarding/smart-nutrition': typeof OnboardingSmartNutritionRoute
  '/smart/signup': typeof SmartSignupRoute
  '/tracker/login': typeof TrackerLoginRoute
  '/tracker/signup': typeof TrackerSignupRoute
  '/bulls': typeof BullsIndexRoute
  '/coach': typeof CoachIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/smart': typeof SmartIndexRoute
  '/tracker': typeof TrackerIndexRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/plan-preview/$planId': typeof CoachPlanPreviewPlanIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/smart/gift/$code': typeof SmartGiftCodeRoute
  '/tracker/app/achievements': typeof TrackerAppAchievementsRoute
  '/tracker/app/activity': typeof TrackerAppActivityRoute
  '/tracker/app/nutrition': typeof TrackerAppNutritionRoute
  '/tracker/app/profile': typeof TrackerAppProfileRoute
  '/tracker/app/training': typeof TrackerAppTrainingRoute
  '/tracker/app/water': typeof TrackerAppWaterRoute
  '/tracker/app/weight': typeof TrackerAppWeightRoute
  '/coach/customers': typeof CoachCustomersIndexRoute
  '/tracker/app': typeof TrackerAppIndexRoute
  '/api/public/hooks/coach-daily-summary': typeof ApiPublicHooksCoachDailySummaryRoute
  '/api/public/hooks/plan-rotation': typeof ApiPublicHooksPlanRotationRoute
  '/api/public/hooks/regen-nutrition-plans': typeof ApiPublicHooksRegenNutritionPlansRoute
  '/api/public/hooks/regen-training-plans': typeof ApiPublicHooksRegenTrainingPlansRoute
  '/api/public/hooks/send-feature-news': typeof ApiPublicHooksSendFeatureNewsRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/coach': typeof CoachRouteWithChildren
  '/community': typeof CommunityRoute
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/messages': typeof MessagesRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ranking': typeof RankingRoute
  '/smart': typeof SmartRouteWithChildren
  '/strength-check': typeof StrengthCheckRoute
  '/training': typeof TrainingRoute
  '/trial': typeof TrialRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/welcome': typeof WelcomeRoute
  '/bulls/benchmarks': typeof BullsBenchmarksRoute
  '/bulls/nutrition': typeof BullsNutritionRoute
  '/bulls/photos': typeof BullsPhotosRoute
  '/bulls/recovery': typeof BullsRecoveryRoute
  '/bulls/training': typeof BullsTrainingRoute
  '/bulls/weight': typeof BullsWeightRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/customers': typeof CoachCustomersRouteWithChildren
  '/coach/gifts': typeof CoachGiftsRoute
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/coach/reviews': typeof CoachReviewsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/nutrition/favorites': typeof NutritionFavoritesRoute
  '/nutrition/recipe-from-ingredients': typeof NutritionRecipeFromIngredientsRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/onboarding/smart': typeof OnboardingSmartRoute
  '/onboarding/smart-nutrition': typeof OnboardingSmartNutritionRoute
  '/smart/signup': typeof SmartSignupRoute
  '/tracker/app': typeof TrackerAppRouteWithChildren
  '/tracker/login': typeof TrackerLoginRoute
  '/tracker/signup': typeof TrackerSignupRoute
  '/bulls/': typeof BullsIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/smart/': typeof SmartIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/plan-preview/$planId': typeof CoachPlanPreviewPlanIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/smart/gift/$code': typeof SmartGiftCodeRoute
  '/tracker/app/achievements': typeof TrackerAppAchievementsRoute
  '/tracker/app/activity': typeof TrackerAppActivityRoute
  '/tracker/app/nutrition': typeof TrackerAppNutritionRoute
  '/tracker/app/profile': typeof TrackerAppProfileRoute
  '/tracker/app/training': typeof TrackerAppTrainingRoute
  '/tracker/app/water': typeof TrackerAppWaterRoute
  '/tracker/app/weight': typeof TrackerAppWeightRoute
  '/coach/customers/': typeof CoachCustomersIndexRoute
  '/tracker/app/': typeof TrackerAppIndexRoute
  '/api/public/hooks/coach-daily-summary': typeof ApiPublicHooksCoachDailySummaryRoute
  '/api/public/hooks/plan-rotation': typeof ApiPublicHooksPlanRotationRoute
  '/api/public/hooks/regen-nutrition-plans': typeof ApiPublicHooksRegenNutritionPlansRoute
  '/api/public/hooks/regen-training-plans': typeof ApiPublicHooksRegenTrainingPlansRoute
  '/api/public/hooks/send-feature-news': typeof ApiPublicHooksSendFeatureNewsRoute
  '/api/public/hooks/trial-reminders': typeof ApiPublicHooksTrialRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/coach'
    | '/community'
    | '/daily-checklist'
    | '/dashboard'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/measurements'
    | '/messages'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/ranking'
    | '/smart'
    | '/strength-check'
    | '/training'
    | '/trial'
    | '/trust'
    | '/unsubscribe'
    | '/welcome'
    | '/bulls/benchmarks'
    | '/bulls/nutrition'
    | '/bulls/photos'
    | '/bulls/recovery'
    | '/bulls/training'
    | '/bulls/weight'
    | '/checkout/return'
    | '/coach/$clientId'
    | '/coach/customers'
    | '/coach/gifts'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/coach/reviews'
    | '/email/unsubscribe'
    | '/nutrition/favorites'
    | '/nutrition/recipe-from-ingredients'
    | '/nutrition/shopping'
    | '/nutrition/tracking'
    | '/onboarding/smart'
    | '/onboarding/smart-nutrition'
    | '/smart/signup'
    | '/tracker/app'
    | '/tracker/login'
    | '/tracker/signup'
    | '/bulls/'
    | '/coach/'
    | '/nutrition/'
    | '/smart/'
    | '/tracker/'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/plan-preview/$planId'
    | '/lovable/email/suppression'
    | '/smart/gift/$code'
    | '/tracker/app/achievements'
    | '/tracker/app/activity'
    | '/tracker/app/nutrition'
    | '/tracker/app/profile'
    | '/tracker/app/training'
    | '/tracker/app/water'
    | '/tracker/app/weight'
    | '/coach/customers/'
    | '/tracker/app/'
    | '/api/public/hooks/coach-daily-summary'
    | '/api/public/hooks/plan-rotation'
    | '/api/public/hooks/regen-nutrition-plans'
    | '/api/public/hooks/regen-training-plans'
    | '/api/public/hooks/send-feature-news'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/community'
    | '/daily-checklist'
    | '/dashboard'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/measurements'
    | '/messages'
    | '/profile'
    | '/progress'
    | '/ranking'
    | '/strength-check'
    | '/training'
    | '/trial'
    | '/trust'
    | '/unsubscribe'
    | '/welcome'
    | '/bulls/benchmarks'
    | '/bulls/nutrition'
    | '/bulls/photos'
    | '/bulls/recovery'
    | '/bulls/training'
    | '/bulls/weight'
    | '/checkout/return'
    | '/coach/$clientId'
    | '/coach/gifts'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/coach/reviews'
    | '/email/unsubscribe'
    | '/nutrition/favorites'
    | '/nutrition/recipe-from-ingredients'
    | '/nutrition/shopping'
    | '/nutrition/tracking'
    | '/onboarding/smart'
    | '/onboarding/smart-nutrition'
    | '/smart/signup'
    | '/tracker/login'
    | '/tracker/signup'
    | '/bulls'
    | '/coach'
    | '/nutrition'
    | '/smart'
    | '/tracker'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/plan-preview/$planId'
    | '/lovable/email/suppression'
    | '/smart/gift/$code'
    | '/tracker/app/achievements'
    | '/tracker/app/activity'
    | '/tracker/app/nutrition'
    | '/tracker/app/profile'
    | '/tracker/app/training'
    | '/tracker/app/water'
    | '/tracker/app/weight'
    | '/coach/customers'
    | '/tracker/app'
    | '/api/public/hooks/coach-daily-summary'
    | '/api/public/hooks/plan-rotation'
    | '/api/public/hooks/regen-nutrition-plans'
    | '/api/public/hooks/regen-training-plans'
    | '/api/public/hooks/send-feature-news'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/coach'
    | '/community'
    | '/daily-checklist'
    | '/dashboard'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/measurements'
    | '/messages'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/ranking'
    | '/smart'
    | '/strength-check'
    | '/training'
    | '/trial'
    | '/trust'
    | '/unsubscribe'
    | '/welcome'
    | '/bulls/benchmarks'
    | '/bulls/nutrition'
    | '/bulls/photos'
    | '/bulls/recovery'
    | '/bulls/training'
    | '/bulls/weight'
    | '/checkout/return'
    | '/coach/$clientId'
    | '/coach/customers'
    | '/coach/gifts'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/coach/reviews'
    | '/email/unsubscribe'
    | '/nutrition/favorites'
    | '/nutrition/recipe-from-ingredients'
    | '/nutrition/shopping'
    | '/nutrition/tracking'
    | '/onboarding/smart'
    | '/onboarding/smart-nutrition'
    | '/smart/signup'
    | '/tracker/app'
    | '/tracker/login'
    | '/tracker/signup'
    | '/bulls/'
    | '/coach/'
    | '/nutrition/'
    | '/smart/'
    | '/tracker/'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/plan-preview/$planId'
    | '/lovable/email/suppression'
    | '/smart/gift/$code'
    | '/tracker/app/achievements'
    | '/tracker/app/activity'
    | '/tracker/app/nutrition'
    | '/tracker/app/profile'
    | '/tracker/app/training'
    | '/tracker/app/water'
    | '/tracker/app/weight'
    | '/coach/customers/'
    | '/tracker/app/'
    | '/api/public/hooks/coach-daily-summary'
    | '/api/public/hooks/plan-rotation'
    | '/api/public/hooks/regen-nutrition-plans'
    | '/api/public/hooks/regen-training-plans'
    | '/api/public/hooks/send-feature-news'
    | '/api/public/hooks/trial-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CheckInRoute: typeof CheckInRoute
  CoachRoute: typeof CoachRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DailyChecklistRoute: typeof DailyChecklistRoute
  DashboardRoute: typeof DashboardRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  MessagesRoute: typeof MessagesRoute
  NutritionRoute: typeof NutritionRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RankingRoute: typeof RankingRoute
  SmartRoute: typeof SmartRouteWithChildren
  StrengthCheckRoute: typeof StrengthCheckRoute
  TrainingRoute: typeof TrainingRoute
  TrialRoute: typeof TrialRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WelcomeRoute: typeof WelcomeRoute
  BullsBenchmarksRoute: typeof BullsBenchmarksRoute
  BullsNutritionRoute: typeof BullsNutritionRoute
  BullsPhotosRoute: typeof BullsPhotosRoute
  BullsRecoveryRoute: typeof BullsRecoveryRoute
  BullsTrainingRoute: typeof BullsTrainingRoute
  BullsWeightRoute: typeof BullsWeightRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  OnboardingSmartRoute: typeof OnboardingSmartRoute
  OnboardingSmartNutritionRoute: typeof OnboardingSmartNutritionRoute
  TrackerAppRoute: typeof TrackerAppRouteWithChildren
  TrackerLoginRoute: typeof TrackerLoginRoute
  TrackerSignupRoute: typeof TrackerSignupRoute
  BullsIndexRoute: typeof BullsIndexRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCoachDailySummaryRoute: typeof ApiPublicHooksCoachDailySummaryRoute
  ApiPublicHooksPlanRotationRoute: typeof ApiPublicHooksPlanRotationRoute
  ApiPublicHooksRegenNutritionPlansRoute: typeof ApiPublicHooksRegenNutritionPlansRoute
  ApiPublicHooksRegenTrainingPlansRoute: typeof ApiPublicHooksRegenTrainingPlansRoute
  ApiPublicHooksSendFeatureNewsRoute: typeof ApiPublicHooksSendFeatureNewsRoute
  ApiPublicHooksTrialRemindersRoute: typeof ApiPublicHooksTrialRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength-check': {
      id: '/strength-check'
      path: '/strength-check'
      fullPath: '/strength-check'
      preLoaderRoute: typeof StrengthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart': {
      id: '/smart'
      path: '/smart'
      fullPath: '/smart'
      preLoaderRoute: typeof SmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-checklist': {
      id: '/daily-checklist'
      path: '/daily-checklist'
      fullPath: '/daily-checklist'
      preLoaderRoute: typeof DailyChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/tracker'
      fullPath: '/tracker/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart/': {
      id: '/smart/'
      path: '/'
      fullPath: '/smart/'
      preLoaderRoute: typeof SmartIndexRouteImport
      parentRoute: typeof SmartRoute
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/bulls/': {
      id: '/bulls/'
      path: '/bulls'
      fullPath: '/bulls/'
      preLoaderRoute: typeof BullsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/signup': {
      id: '/tracker/signup'
      path: '/tracker/signup'
      fullPath: '/tracker/signup'
      preLoaderRoute: typeof TrackerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/login': {
      id: '/tracker/login'
      path: '/tracker/login'
      fullPath: '/tracker/login'
      preLoaderRoute: typeof TrackerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/app': {
      id: '/tracker/app'
      path: '/tracker/app'
      fullPath: '/tracker/app'
      preLoaderRoute: typeof TrackerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart/signup': {
      id: '/smart/signup'
      path: '/signup'
      fullPath: '/smart/signup'
      preLoaderRoute: typeof SmartSignupRouteImport
      parentRoute: typeof SmartRoute
    }
    '/onboarding/smart-nutrition': {
      id: '/onboarding/smart-nutrition'
      path: '/onboarding/smart-nutrition'
      fullPath: '/onboarding/smart-nutrition'
      preLoaderRoute: typeof OnboardingSmartNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/smart': {
      id: '/onboarding/smart'
      path: '/onboarding/smart'
      fullPath: '/onboarding/smart'
      preLoaderRoute: typeof OnboardingSmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/tracking': {
      id: '/nutrition/tracking'
      path: '/tracking'
      fullPath: '/nutrition/tracking'
      preLoaderRoute: typeof NutritionTrackingRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/shopping': {
      id: '/nutrition/shopping'
      path: '/shopping'
      fullPath: '/nutrition/shopping'
      preLoaderRoute: typeof NutritionShoppingRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/recipe-from-ingredients': {
      id: '/nutrition/recipe-from-ingredients'
      path: '/recipe-from-ingredients'
      fullPath: '/nutrition/recipe-from-ingredients'
      preLoaderRoute: typeof NutritionRecipeFromIngredientsRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/favorites': {
      id: '/nutrition/favorites'
      path: '/favorites'
      fullPath: '/nutrition/favorites'
      preLoaderRoute: typeof NutritionFavoritesRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/reviews': {
      id: '/coach/reviews'
      path: '/reviews'
      fullPath: '/coach/reviews'
      preLoaderRoute: typeof CoachReviewsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/package-requests': {
      id: '/coach/package-requests'
      path: '/package-requests'
      fullPath: '/coach/package-requests'
      preLoaderRoute: typeof CoachPackageRequestsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/leads': {
      id: '/coach/leads'
      path: '/leads'
      fullPath: '/coach/leads'
      preLoaderRoute: typeof CoachLeadsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/gifts': {
      id: '/coach/gifts'
      path: '/gifts'
      fullPath: '/coach/gifts'
      preLoaderRoute: typeof CoachGiftsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/customers': {
      id: '/coach/customers'
      path: '/customers'
      fullPath: '/coach/customers'
      preLoaderRoute: typeof CoachCustomersRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/$clientId': {
      id: '/coach/$clientId'
      path: '/$clientId'
      fullPath: '/coach/$clientId'
      preLoaderRoute: typeof CoachClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/weight': {
      id: '/bulls/weight'
      path: '/bulls/weight'
      fullPath: '/bulls/weight'
      preLoaderRoute: typeof BullsWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/training': {
      id: '/bulls/training'
      path: '/bulls/training'
      fullPath: '/bulls/training'
      preLoaderRoute: typeof BullsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/recovery': {
      id: '/bulls/recovery'
      path: '/bulls/recovery'
      fullPath: '/bulls/recovery'
      preLoaderRoute: typeof BullsRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/photos': {
      id: '/bulls/photos'
      path: '/bulls/photos'
      fullPath: '/bulls/photos'
      preLoaderRoute: typeof BullsPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/nutrition': {
      id: '/bulls/nutrition'
      path: '/bulls/nutrition'
      fullPath: '/bulls/nutrition'
      preLoaderRoute: typeof BullsNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulls/benchmarks': {
      id: '/bulls/benchmarks'
      path: '/bulls/benchmarks'
      fullPath: '/bulls/benchmarks'
      preLoaderRoute: typeof BullsBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker/app/': {
      id: '/tracker/app/'
      path: '/'
      fullPath: '/tracker/app/'
      preLoaderRoute: typeof TrackerAppIndexRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/coach/customers/': {
      id: '/coach/customers/'
      path: '/'
      fullPath: '/coach/customers/'
      preLoaderRoute: typeof CoachCustomersIndexRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/tracker/app/weight': {
      id: '/tracker/app/weight'
      path: '/weight'
      fullPath: '/tracker/app/weight'
      preLoaderRoute: typeof TrackerAppWeightRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/water': {
      id: '/tracker/app/water'
      path: '/water'
      fullPath: '/tracker/app/water'
      preLoaderRoute: typeof TrackerAppWaterRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/training': {
      id: '/tracker/app/training'
      path: '/training'
      fullPath: '/tracker/app/training'
      preLoaderRoute: typeof TrackerAppTrainingRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/profile': {
      id: '/tracker/app/profile'
      path: '/profile'
      fullPath: '/tracker/app/profile'
      preLoaderRoute: typeof TrackerAppProfileRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/nutrition': {
      id: '/tracker/app/nutrition'
      path: '/nutrition'
      fullPath: '/tracker/app/nutrition'
      preLoaderRoute: typeof TrackerAppNutritionRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/activity': {
      id: '/tracker/app/activity'
      path: '/activity'
      fullPath: '/tracker/app/activity'
      preLoaderRoute: typeof TrackerAppActivityRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/tracker/app/achievements': {
      id: '/tracker/app/achievements'
      path: '/achievements'
      fullPath: '/tracker/app/achievements'
      preLoaderRoute: typeof TrackerAppAchievementsRouteImport
      parentRoute: typeof TrackerAppRoute
    }
    '/smart/gift/$code': {
      id: '/smart/gift/$code'
      path: '/gift/$code'
      fullPath: '/smart/gift/$code'
      preLoaderRoute: typeof SmartGiftCodeRouteImport
      parentRoute: typeof SmartRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/plan-preview/$planId': {
      id: '/coach/plan-preview/$planId'
      path: '/plan-preview/$planId'
      fullPath: '/coach/plan-preview/$planId'
      preLoaderRoute: typeof CoachPlanPreviewPlanIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/customers/new': {
      id: '/coach/customers/new'
      path: '/new'
      fullPath: '/coach/customers/new'
      preLoaderRoute: typeof CoachCustomersNewRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/coach/customers/$userId': {
      id: '/coach/customers/$userId'
      path: '/$userId'
      fullPath: '/coach/customers/$userId'
      preLoaderRoute: typeof CoachCustomersUserIdRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-reminders': {
      id: '/api/public/hooks/trial-reminders'
      path: '/api/public/hooks/trial-reminders'
      fullPath: '/api/public/hooks/trial-reminders'
      preLoaderRoute: typeof ApiPublicHooksTrialRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-feature-news': {
      id: '/api/public/hooks/send-feature-news'
      path: '/api/public/hooks/send-feature-news'
      fullPath: '/api/public/hooks/send-feature-news'
      preLoaderRoute: typeof ApiPublicHooksSendFeatureNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/regen-training-plans': {
      id: '/api/public/hooks/regen-training-plans'
      path: '/api/public/hooks/regen-training-plans'
      fullPath: '/api/public/hooks/regen-training-plans'
      preLoaderRoute: typeof ApiPublicHooksRegenTrainingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/regen-nutrition-plans': {
      id: '/api/public/hooks/regen-nutrition-plans'
      path: '/api/public/hooks/regen-nutrition-plans'
      fullPath: '/api/public/hooks/regen-nutrition-plans'
      preLoaderRoute: typeof ApiPublicHooksRegenNutritionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/plan-rotation': {
      id: '/api/public/hooks/plan-rotation'
      path: '/api/public/hooks/plan-rotation'
      fullPath: '/api/public/hooks/plan-rotation'
      preLoaderRoute: typeof ApiPublicHooksPlanRotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/coach-daily-summary': {
      id: '/api/public/hooks/coach-daily-summary'
      path: '/api/public/hooks/coach-daily-summary'
      fullPath: '/api/public/hooks/coach-daily-summary'
      preLoaderRoute: typeof ApiPublicHooksCoachDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachCustomersRouteChildren {
  CoachCustomersUserIdRoute: typeof CoachCustomersUserIdRoute
  CoachCustomersNewRoute: typeof CoachCustomersNewRoute
  CoachCustomersIndexRoute: typeof CoachCustomersIndexRoute
}

const CoachCustomersRouteChildren: CoachCustomersRouteChildren = {
  CoachCustomersUserIdRoute: CoachCustomersUserIdRoute,
  CoachCustomersNewRoute: CoachCustomersNewRoute,
  CoachCustomersIndexRoute: CoachCustomersIndexRoute,
}

const CoachCustomersRouteWithChildren = CoachCustomersRoute._addFileChildren(
  CoachCustomersRouteChildren,
)

interface CoachRouteChildren {
  CoachClientIdRoute: typeof CoachClientIdRoute
  CoachCustomersRoute: typeof CoachCustomersRouteWithChildren
  CoachGiftsRoute: typeof CoachGiftsRoute
  CoachLeadsRoute: typeof CoachLeadsRoute
  CoachPackageRequestsRoute: typeof CoachPackageRequestsRoute
  CoachReviewsRoute: typeof CoachReviewsRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachPlanPreviewPlanIdRoute: typeof CoachPlanPreviewPlanIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientIdRoute: CoachClientIdRoute,
  CoachCustomersRoute: CoachCustomersRouteWithChildren,
  CoachGiftsRoute: CoachGiftsRoute,
  CoachLeadsRoute: CoachLeadsRoute,
  CoachPackageRequestsRoute: CoachPackageRequestsRoute,
  CoachReviewsRoute: CoachReviewsRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachPlanPreviewPlanIdRoute: CoachPlanPreviewPlanIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface NutritionRouteChildren {
  NutritionFavoritesRoute: typeof NutritionFavoritesRoute
  NutritionRecipeFromIngredientsRoute: typeof NutritionRecipeFromIngredientsRoute
  NutritionShoppingRoute: typeof NutritionShoppingRoute
  NutritionTrackingRoute: typeof NutritionTrackingRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
}

const NutritionRouteChildren: NutritionRouteChildren = {
  NutritionFavoritesRoute: NutritionFavoritesRoute,
  NutritionRecipeFromIngredientsRoute: NutritionRecipeFromIngredientsRoute,
  NutritionShoppingRoute: NutritionShoppingRoute,
  NutritionTrackingRoute: NutritionTrackingRoute,
  NutritionIndexRoute: NutritionIndexRoute,
}

const NutritionRouteWithChildren = NutritionRoute._addFileChildren(
  NutritionRouteChildren,
)

interface SmartRouteChildren {
  SmartSignupRoute: typeof SmartSignupRoute
  SmartIndexRoute: typeof SmartIndexRoute
  SmartGiftCodeRoute: typeof SmartGiftCodeRoute
}

const SmartRouteChildren: SmartRouteChildren = {
  SmartSignupRoute: SmartSignupRoute,
  SmartIndexRoute: SmartIndexRoute,
  SmartGiftCodeRoute: SmartGiftCodeRoute,
}

const SmartRouteWithChildren = SmartRoute._addFileChildren(SmartRouteChildren)

interface TrackerAppRouteChildren {
  TrackerAppAchievementsRoute: typeof TrackerAppAchievementsRoute
  TrackerAppActivityRoute: typeof TrackerAppActivityRoute
  TrackerAppNutritionRoute: typeof TrackerAppNutritionRoute
  TrackerAppProfileRoute: typeof TrackerAppProfileRoute
  TrackerAppTrainingRoute: typeof TrackerAppTrainingRoute
  TrackerAppWaterRoute: typeof TrackerAppWaterRoute
  TrackerAppWeightRoute: typeof TrackerAppWeightRoute
  TrackerAppIndexRoute: typeof TrackerAppIndexRoute
}

const TrackerAppRouteChildren: TrackerAppRouteChildren = {
  TrackerAppAchievementsRoute: TrackerAppAchievementsRoute,
  TrackerAppActivityRoute: TrackerAppActivityRoute,
  TrackerAppNutritionRoute: TrackerAppNutritionRoute,
  TrackerAppProfileRoute: TrackerAppProfileRoute,
  TrackerAppTrainingRoute: TrackerAppTrainingRoute,
  TrackerAppWaterRoute: TrackerAppWaterRoute,
  TrackerAppWeightRoute: TrackerAppWeightRoute,
  TrackerAppIndexRoute: TrackerAppIndexRoute,
}

const TrackerAppRouteWithChildren = TrackerAppRoute._addFileChildren(
  TrackerAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CheckInRoute: CheckInRoute,
  CoachRoute: CoachRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DailyChecklistRoute: DailyChecklistRoute,
  DashboardRoute: DashboardRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  MessagesRoute: MessagesRoute,
  NutritionRoute: NutritionRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RankingRoute: RankingRoute,
  SmartRoute: SmartRouteWithChildren,
  StrengthCheckRoute: StrengthCheckRoute,
  TrainingRoute: TrainingRoute,
  TrialRoute: TrialRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WelcomeRoute: WelcomeRoute,
  BullsBenchmarksRoute: BullsBenchmarksRoute,
  BullsNutritionRoute: BullsNutritionRoute,
  BullsPhotosRoute: BullsPhotosRoute,
  BullsRecoveryRoute: BullsRecoveryRoute,
  BullsTrainingRoute: BullsTrainingRoute,
  BullsWeightRoute: BullsWeightRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  OnboardingSmartRoute: OnboardingSmartRoute,
  OnboardingSmartNutritionRoute: OnboardingSmartNutritionRoute,
  TrackerAppRoute: TrackerAppRouteWithChildren,
  TrackerLoginRoute: TrackerLoginRoute,
  TrackerSignupRoute: TrackerSignupRoute,
  BullsIndexRoute: BullsIndexRoute,
  TrackerIndexRoute: TrackerIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCoachDailySummaryRoute: ApiPublicHooksCoachDailySummaryRoute,
  ApiPublicHooksPlanRotationRoute: ApiPublicHooksPlanRotationRoute,
  ApiPublicHooksRegenNutritionPlansRoute:
    ApiPublicHooksRegenNutritionPlansRoute,
  ApiPublicHooksRegenTrainingPlansRoute: ApiPublicHooksRegenTrainingPlansRoute,
  ApiPublicHooksSendFeatureNewsRoute: ApiPublicHooksSendFeatureNewsRoute,
  ApiPublicHooksTrialRemindersRoute: ApiPublicHooksTrialRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
