/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyChecklistRouteImport } from './routes/daily-checklist'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as NutritionTrackingRouteImport } from './routes/nutrition.tracking'
import { Route as CoachPackageRequestsRouteImport } from './routes/coach.package-requests'
import { Route as CoachLeadsRouteImport } from './routes/coach.leads'
import { Route as CoachCustomersRouteImport } from './routes/coach.customers'
import { Route as CoachClientIdRouteImport } from './routes/coach.$clientId'
import { Route as CoachCustomersIndexRouteImport } from './routes/coach.customers.index'
import { Route as CoachCustomersNewRouteImport } from './routes/coach.customers.new'
import { Route as CoachCustomersUserIdRouteImport } from './routes/coach.customers.$userId'
import { Route as ApiPublicResetLukasRouteImport } from './routes/api/public/reset-lukas'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyChecklistRoute = DailyChecklistRouteImport.update({
  id: '/daily-checklist',
  path: '/daily-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutritionRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const NutritionTrackingRoute = NutritionTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => NutritionRoute,
} as any)
const CoachPackageRequestsRoute = CoachPackageRequestsRouteImport.update({
  id: '/package-requests',
  path: '/package-requests',
  getParentRoute: () => CoachRoute,
} as any)
const CoachLeadsRoute = CoachLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCustomersRoute = CoachCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientIdRoute = CoachClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachCustomersIndexRoute = CoachCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const CoachCustomersNewRoute = CoachCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const CoachCustomersUserIdRoute = CoachCustomersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => CoachCustomersRoute,
} as any)
const ApiPublicResetLukasRoute = ApiPublicResetLukasRouteImport.update({
  id: '/api/public/reset-lukas',
  path: '/api/public/reset-lukas',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/coach': typeof CoachRouteWithChildren
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/customers': typeof CoachCustomersRouteWithChildren
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/coach/': typeof CoachIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/api/public/reset-lukas': typeof ApiPublicResetLukasRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/customers/': typeof CoachCustomersIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/coach': typeof CoachIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/api/public/reset-lukas': typeof ApiPublicResetLukasRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/customers': typeof CoachCustomersIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/coach': typeof CoachRouteWithChildren
  '/daily-checklist': typeof DailyChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/coach/$clientId': typeof CoachClientIdRoute
  '/coach/customers': typeof CoachCustomersRouteWithChildren
  '/coach/leads': typeof CoachLeadsRoute
  '/coach/package-requests': typeof CoachPackageRequestsRoute
  '/nutrition/tracking': typeof NutritionTrackingRoute
  '/coach/': typeof CoachIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/api/public/reset-lukas': typeof ApiPublicResetLukasRoute
  '/coach/customers/$userId': typeof CoachCustomersUserIdRoute
  '/coach/customers/new': typeof CoachCustomersNewRoute
  '/coach/customers/': typeof CoachCustomersIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/coach'
    | '/daily-checklist'
    | '/dashboard'
    | '/login'
    | '/measurements'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/training'
    | '/welcome'
    | '/coach/$clientId'
    | '/coach/customers'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/nutrition/tracking'
    | '/coach/'
    | '/nutrition/'
    | '/api/public/reset-lukas'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/customers/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/daily-checklist'
    | '/dashboard'
    | '/login'
    | '/measurements'
    | '/profile'
    | '/progress'
    | '/training'
    | '/welcome'
    | '/coach/$clientId'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/nutrition/tracking'
    | '/coach'
    | '/nutrition'
    | '/api/public/reset-lukas'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/customers'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/check-in'
    | '/coach'
    | '/daily-checklist'
    | '/dashboard'
    | '/login'
    | '/measurements'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/training'
    | '/welcome'
    | '/coach/$clientId'
    | '/coach/customers'
    | '/coach/leads'
    | '/coach/package-requests'
    | '/nutrition/tracking'
    | '/coach/'
    | '/nutrition/'
    | '/api/public/reset-lukas'
    | '/coach/customers/$userId'
    | '/coach/customers/new'
    | '/coach/customers/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  CheckInRoute: typeof CheckInRoute
  CoachRoute: typeof CoachRouteWithChildren
  DailyChecklistRoute: typeof DailyChecklistRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  NutritionRoute: typeof NutritionRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  TrainingRoute: typeof TrainingRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicResetLukasRoute: typeof ApiPublicResetLukasRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-checklist': {
      id: '/daily-checklist'
      path: '/daily-checklist'
      fullPath: '/daily-checklist'
      preLoaderRoute: typeof DailyChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/nutrition/tracking': {
      id: '/nutrition/tracking'
      path: '/tracking'
      fullPath: '/nutrition/tracking'
      preLoaderRoute: typeof NutritionTrackingRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/coach/package-requests': {
      id: '/coach/package-requests'
      path: '/package-requests'
      fullPath: '/coach/package-requests'
      preLoaderRoute: typeof CoachPackageRequestsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/leads': {
      id: '/coach/leads'
      path: '/leads'
      fullPath: '/coach/leads'
      preLoaderRoute: typeof CoachLeadsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/customers': {
      id: '/coach/customers'
      path: '/customers'
      fullPath: '/coach/customers'
      preLoaderRoute: typeof CoachCustomersRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/$clientId': {
      id: '/coach/$clientId'
      path: '/$clientId'
      fullPath: '/coach/$clientId'
      preLoaderRoute: typeof CoachClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/customers/': {
      id: '/coach/customers/'
      path: '/'
      fullPath: '/coach/customers/'
      preLoaderRoute: typeof CoachCustomersIndexRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/coach/customers/new': {
      id: '/coach/customers/new'
      path: '/new'
      fullPath: '/coach/customers/new'
      preLoaderRoute: typeof CoachCustomersNewRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/coach/customers/$userId': {
      id: '/coach/customers/$userId'
      path: '/$userId'
      fullPath: '/coach/customers/$userId'
      preLoaderRoute: typeof CoachCustomersUserIdRouteImport
      parentRoute: typeof CoachCustomersRoute
    }
    '/api/public/reset-lukas': {
      id: '/api/public/reset-lukas'
      path: '/api/public/reset-lukas'
      fullPath: '/api/public/reset-lukas'
      preLoaderRoute: typeof ApiPublicResetLukasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachCustomersRouteChildren {
  CoachCustomersUserIdRoute: typeof CoachCustomersUserIdRoute
  CoachCustomersNewRoute: typeof CoachCustomersNewRoute
  CoachCustomersIndexRoute: typeof CoachCustomersIndexRoute
}

const CoachCustomersRouteChildren: CoachCustomersRouteChildren = {
  CoachCustomersUserIdRoute: CoachCustomersUserIdRoute,
  CoachCustomersNewRoute: CoachCustomersNewRoute,
  CoachCustomersIndexRoute: CoachCustomersIndexRoute,
}

const CoachCustomersRouteWithChildren = CoachCustomersRoute._addFileChildren(
  CoachCustomersRouteChildren,
)

interface CoachRouteChildren {
  CoachClientIdRoute: typeof CoachClientIdRoute
  CoachCustomersRoute: typeof CoachCustomersRouteWithChildren
  CoachLeadsRoute: typeof CoachLeadsRoute
  CoachPackageRequestsRoute: typeof CoachPackageRequestsRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientIdRoute: CoachClientIdRoute,
  CoachCustomersRoute: CoachCustomersRouteWithChildren,
  CoachLeadsRoute: CoachLeadsRoute,
  CoachPackageRequestsRoute: CoachPackageRequestsRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface NutritionRouteChildren {
  NutritionTrackingRoute: typeof NutritionTrackingRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
}

const NutritionRouteChildren: NutritionRouteChildren = {
  NutritionTrackingRoute: NutritionTrackingRoute,
  NutritionIndexRoute: NutritionIndexRoute,
}

const NutritionRouteWithChildren = NutritionRoute._addFileChildren(
  NutritionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  CheckInRoute: CheckInRoute,
  CoachRoute: CoachRouteWithChildren,
  DailyChecklistRoute: DailyChecklistRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  NutritionRoute: NutritionRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  TrainingRoute: TrainingRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicResetLukasRoute: ApiPublicResetLukasRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
