-- BodyFuel: Gerichtsbibliothek für alle Ernährungsformen (idempotent)
-- 1) Ernährungsform-Tags bestehender Gerichte korrigieren (inhaltsbasiert)
UPDATE public.coach_meal_library SET tags = ARRAY['classic','vegetarisch']::text[], updated_at = now() WHERE id = '1f43ae2b-4d90-4d31-b02f-f153de809857';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','carb_heavy','vegetarisch']::text[], updated_at = now() WHERE id = 'a60712a9-07a8-4050-bf06-e15fdd1e5b7b';
UPDATE public.coach_meal_library SET tags = ARRAY['omega3','healthy','pescetarisch']::text[], updated_at = now() WHERE id = '9bc9f276-d076-461c-970c-021adf1d1dc3';
UPDATE public.coach_meal_library SET tags = ARRAY['low_carb','quick','vegetarisch']::text[], updated_at = now() WHERE id = 'fa6a6f9b-8d01-4345-b569-78880bb7c287';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','cold','vegetarisch']::text[], updated_at = now() WHERE id = '280e14ff-1ca8-4878-bcf3-c71ba0e07c56';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','cold','vegetarisch']::text[], updated_at = now() WHERE id = '528ea9c5-e435-45e9-b83c-e9a87ef44bd8';
UPDATE public.coach_meal_library SET tags = ARRAY['healthy','low_carb','pescetarisch']::text[], updated_at = now() WHERE id = '79f9707f-c1e6-47a8-9dbd-94b6e3638c64';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','portable','vegetarisch']::text[], updated_at = now() WHERE id = 'ca7fd214-0555-4e3a-aca6-98f30daa3c95';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','high_protein','low_carb','vegetarisch']::text[], updated_at = now() WHERE id = '3f86c922-9cf8-47e9-9518-c92d3eac72e8';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','portable','fat','vegetarisch']::text[], updated_at = now() WHERE id = '95926990-5b43-4ef6-b826-6d2fd1a3ba73';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','high_protein','low_fat','vegetarisch']::text[], updated_at = now() WHERE id = '1c03e5e7-c430-43dd-8933-cf0a200e8fca';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','mealprep','vegan']::text[], updated_at = now() WHERE id = 'bc6dd5b0-6497-40c5-9e5e-fe2984c1fec5';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','mealprep','vegetarisch']::text[], updated_at = now() WHERE id = '7e95dd92-0818-493c-bc8e-f535ef66ae8a';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','quick','vegetarisch']::text[], updated_at = now() WHERE id = '498b7127-a174-42de-bc34-bdc8f7ba0d40';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','portable','vegetarisch']::text[], updated_at = now() WHERE id = '08b313cf-8eb5-4afc-9598-a82203cd4a2a';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','low_cal','vegetarisch']::text[], updated_at = now() WHERE id = 'aa0025ca-9aa9-471e-a7b9-ed80afdf25e9';
UPDATE public.coach_meal_library SET tags = ARRAY['vegan']::text[], updated_at = now() WHERE id = '19a28b60-e469-4b62-a5f6-cb20a3dc8af6';
UPDATE public.coach_meal_library SET tags = ARRAY['quick','high_protein','vegetarisch']::text[], updated_at = now() WHERE id = 'd332d8d2-d471-49d0-ae78-ac48dca3f620';
UPDATE public.coach_meal_library SET tags = ARRAY['klassisch','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '869e0450-dfa1-4560-91fc-6ce6d8be4aa4';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','mealprep']::text[], updated_at = now() WHERE id = '88e8f4a6-9324-4439-983a-25afb710098d';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','mealprep','vegan']::text[], updated_at = now() WHERE id = 'f6764e6c-fbdf-4b66-b995-9df1e253bc97';
UPDATE public.coach_meal_library SET tags = ARRAY['klassisch','pescetarisch']::text[], updated_at = now() WHERE id = '7c1e275f-8a0c-458f-87f2-8ef88e19dd05';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','warm','vegetarisch']::text[], updated_at = now() WHERE id = '75f2f2f5-eb79-4f0c-8e02-4d89273047a2';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','low_carb','vegan']::text[], updated_at = now() WHERE id = '1f90680e-1aa2-4803-8bbb-e0fa973295b4';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','günstig','vegan']::text[], updated_at = now() WHERE id = '716b6109-ad7e-4a8b-b293-2f2056475d77';
UPDATE public.coach_meal_library SET tags = ARRAY['schnell','low_carb','günstig','vegetarisch']::text[], updated_at = now() WHERE id = 'c203962b-d5e4-48cc-8adb-41052848fb39';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','günstig','vegan']::text[], updated_at = now() WHERE id = '664bca05-8439-42f9-95de-b28058418f09';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','low_carb','vegetarisch']::text[], updated_at = now() WHERE id = '1a720e4e-4f35-45df-b5c0-1ecd28f7d148';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','günstig','warm','vegan']::text[], updated_at = now() WHERE id = '4c43ac9a-74f8-4b25-9a90-c7809e8d69be';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','vegan']::text[], updated_at = now() WHERE id = 'aa7eed3f-5743-48d1-b194-30dca9e891c2';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '7ba512f1-9bb4-4eea-914b-f11103b8cd5a';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','schnell','vegetarisch']::text[], updated_at = now() WHERE id = '28898214-7ed0-4030-b7d0-76c7148642b7';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '7438e63e-2ca8-4ff7-b965-ef960b7da67b';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','low_carb','kalt','günstig','mealprep','vegetarisch']::text[], updated_at = now() WHERE id = '99cbcf6a-2383-4dac-b429-e42fe11b3998';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','kalt','vegan']::text[], updated_at = now() WHERE id = '9e4bba89-353e-47fb-a17b-3dc7c2c97030';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','vegan']::text[], updated_at = now() WHERE id = 'eec427cc-dc3a-4c3f-879b-ca5ad3a4bd30';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','vegan']::text[], updated_at = now() WHERE id = 'd9b79c06-eb20-4568-979b-add2bab14bb5';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','günstig','schnell','vegetarisch']::text[], updated_at = now() WHERE id = 'eb2b2ea0-bc69-4b0a-812f-70936f109a9d';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','kalt','schnell','pescetarisch']::text[], updated_at = now() WHERE id = '1c2b8fd8-c26c-4ad5-af94-18f0db97dd03';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','klassisch','pescetarisch']::text[], updated_at = now() WHERE id = '3f77f8ee-1e1a-4ea6-a43e-f8aba3d9a65e';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','vegan']::text[], updated_at = now() WHERE id = '6c99c997-ba23-4245-9bcc-06be4f21dac1';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','kalt','schnell','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '21ce37dd-c121-4796-b3cb-b45689048e8a';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','günstig','vegan']::text[], updated_at = now() WHERE id = '2c95e59a-3e6d-4bc4-8bca-b6e072909f8e';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','günstig','schnell','vegetarisch']::text[], updated_at = now() WHERE id = 'e04f325c-a62e-4bbe-8349-43b8140c9873';
UPDATE public.coach_meal_library SET tags = ARRAY['klassisch','günstig','pescetarisch']::text[], updated_at = now() WHERE id = '42aee618-85bd-4165-a775-867aaa669ee7';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','mealprep','vegetarisch']::text[], updated_at = now() WHERE id = '7382f32b-c247-4620-a8d6-9e77aab3610a';
UPDATE public.coach_meal_library SET tags = ARRAY['mealprep','kalt','vegan']::text[], updated_at = now() WHERE id = 'e9d8e2ae-fd8b-4ed3-889b-5dcbe709f50e';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','kalt','günstig','vegetarisch']::text[], updated_at = now() WHERE id = 'e90816e8-00fa-4502-80b2-5bb18e47932a';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','schnell','pre_workout','vegetarisch']::text[], updated_at = now() WHERE id = '42216df0-ae0e-4ecc-a04a-c66fe6078f3b';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','klassisch','vegetarisch']::text[], updated_at = now() WHERE id = '7c662b5d-466e-4a9b-9cb2-ed43a2939cdf';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','mealprep','vegan']::text[], updated_at = now() WHERE id = 'c1f69350-4635-450e-8a8d-c129c17f5215';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','mealprep','vegetarisch']::text[], updated_at = now() WHERE id = 'a85aabda-41c5-470f-9755-e62b442c560d';
UPDATE public.coach_meal_library SET tags = ARRAY['klassisch','schnell','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '2bb8899f-dcfe-483c-8b94-b256660c80c0';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','high_protein','pescetarisch']::text[], updated_at = now() WHERE id = 'b8d540e1-3564-44be-8258-b46a0fe1ec9c';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','klassisch','vegetarisch']::text[], updated_at = now() WHERE id = '20c3ee3e-fc8b-4c49-a225-30825b49126b';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','klassisch','vegetarisch']::text[], updated_at = now() WHERE id = '28b2d70a-b40f-41ee-80d7-e4302c18e365';
UPDATE public.coach_meal_library SET tags = ARRAY['low_carb','warm','high_protein','vegetarisch']::text[], updated_at = now() WHERE id = 'fc3a0332-293a-41dc-b1c9-2317bc2b5412';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','low_carb','kalt','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '1536143c-6c1f-4afe-ac1e-6688c37460de';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','warm','schnell','vegan']::text[], updated_at = now() WHERE id = 'cb242452-01e1-4211-8215-1c0e405e5242';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','vegan']::text[], updated_at = now() WHERE id = '82d5a326-0e64-4dcb-a331-970944777f28';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','vegan']::text[], updated_at = now() WHERE id = '27bf638e-5be0-4367-aa6b-40802975ad89';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','schnell','pescetarisch']::text[], updated_at = now() WHERE id = '24074dd2-2f98-4995-a8ae-bbc272abbfd7';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','mealprep','schnell','pescetarisch']::text[], updated_at = now() WHERE id = '6af5a8d8-287b-43a2-94aa-8cf1be49ae69';
UPDATE public.coach_meal_library SET tags = ARRAY['high_protein','post_workout','schnell','vegetarisch']::text[], updated_at = now() WHERE id = '20a4de3d-089c-4d7c-8476-724a84e60f55';
UPDATE public.coach_meal_library SET tags = ARRAY['warm','high_protein','günstig','vegetarisch']::text[], updated_at = now() WHERE id = '660cee19-4429-4aeb-8376-39babceda77e';
UPDATE public.coach_meal_library SET tags = ARRAY['kalt','schnell','high_protein','vegetarisch']::text[], updated_at = now() WHERE id = '563df27d-b04e-45b5-aaff-28a52ded1daf';

-- 2) Neue Gerichte ergänzen (nur wenn Name+Kategorie noch nicht existiert)
INSERT INTO public.coach_meal_library (
  name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
  ingredients, instructions, tags, no_go_ingredients,
  suitable_training, suitable_rest, mealprep_ok, eat_cold,
  effort, budget, main_protein, main_carb, is_system, is_active
)
SELECT s.name, s.description, s.category, s.kcal, s.protein_g, s.carbs_g, s.fat_g, s.portion_label,
       s.ingredients, s.instructions, s.tags, s.no_go_ingredients,
       s.suitable_training, s.suitable_rest, s.mealprep_ok, s.eat_cold,
       s.effort, s.budget, s.main_protein, s.main_carb, true, true
FROM (VALUES
  ('Porridge mit Sojadrink und Erdnussmus', 'Warmer Haferbrei mit pflanzlichem Protein', 'breakfast'::meal_slot_kind, 460, 21, 58, 16, '1 Schale (ca. 430 g)',
   '[{"name":"Haferflocken","amount_g":70},{"name":"Sojadrink ungesüßt","amount_g":250},{"name":"Erdnussmus","amount_g":20},{"name":"Banane","amount_g":100}]'::jsonb, 'Haferflocken mit Sojadrink aufkochen, quellen lassen, Erdnussmus und Banane unterheben.', ARRAY['vegan','warm','high_protein','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojadrink', 'Haferflocken'),
  ('Tofu-Scramble mit Champignons', 'Herzhaftes Rührtofu-Frühstück mit Pilzen', 'breakfast'::meal_slot_kind, 378, 28, 26, 18, '1 Pfanne',
   '[{"name":"Naturtofu","amount_g":200},{"name":"Champignons","amount_g":100},{"name":"Vollkornbrot","amount_g":60},{"name":"Rapsöl","amount_g":10},{"name":"Kurkuma","amount_g":2}]'::jsonb, 'Tofu zerbröseln, mit Pilzen anbraten, würzen und mit Brot servieren.', ARRAY['vegan','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Tofu', 'Vollkornbrot'),
  ('Hirse-Porridge mit Apfelkompott', 'Glutenfreie Alternative zum Haferbrei', 'breakfast'::meal_slot_kind, 402, 12, 66, 10, '1 Schale',
   '[{"name":"Hirse gekocht","amount_g":250},{"name":"Hafermilch","amount_g":150},{"name":"Apfel","amount_g":130},{"name":"Leinsamen geschrotet","amount_g":15}]'::jsonb, 'Hirse mit Hafermilch erwärmen, Apfel weich dünsten, alles mischen.', ARRAY['vegan','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hirse', 'Hirse'),
  ('Vollkornbrot mit Hummus und Gurke', 'Kaltes herzhaftes Frühstück ohne Kochen', 'breakfast'::meal_slot_kind, 366, 16, 44, 14, '2 Scheiben',
   '[{"name":"Vollkornbrot","amount_g":100},{"name":"Hummus","amount_g":80},{"name":"Gurke","amount_g":80},{"name":"Kresse","amount_g":5}]'::jsonb, 'Brot mit Hummus bestreichen, Gurke auflegen.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Vollkornbrot'),
  ('Sojajoghurt mit Müsli und Birne', 'Schnelle pflanzliche Frühstücks-Bowl', 'breakfast'::meal_slot_kind, 392, 19, 52, 12, '1 Bowl',
   '[{"name":"Sojajoghurt","amount_g":250},{"name":"Vollkornmüsli","amount_g":60},{"name":"Birne","amount_g":120},{"name":"Sonnenblumenkerne","amount_g":10}]'::jsonb, 'Alles in eine Schüssel geben und mischen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojajoghurt', 'Müsli'),
  ('Protein-Smoothie mit Erbsenprotein und Banane', 'Trinkfrühstück für eilige Morgen', 'breakfast'::meal_slot_kind, 368, 32, 42, 8, '1 großes Glas (500 ml)',
   '[{"name":"Erbsenprotein","amount_g":30},{"name":"Hafermilch","amount_g":300},{"name":"Banane","amount_g":120},{"name":"Haferflocken","amount_g":30}]'::jsonb, 'Alles im Mixer glatt mixen.', ARRAY['vegan','high_protein','schnell','pre_workout']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Erbsenprotein', 'Banane'),
  ('Overnight Oats mit Sojadrink und Himbeeren', 'Am Vorabend angesetzt, morgens fertig', 'breakfast'::meal_slot_kind, 383, 17, 54, 11, '1 Glas',
   '[{"name":"Haferflocken","amount_g":65},{"name":"Sojadrink ungesüßt","amount_g":220},{"name":"Himbeeren TK","amount_g":80},{"name":"Chiasamen","amount_g":12}]'::jsonb, 'Alles im Glas verrühren und über Nacht kühlen.', ARRAY['vegan','mealprep','kalt','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojadrink', 'Haferflocken'),
  ('Vollkorntoast mit Avocado und Kichererbsen', 'Sättigender Toast mit pflanzlichem Eiweiß', 'breakfast'::meal_slot_kind, 427, 18, 46, 19, '2 Scheiben',
   '[{"name":"Vollkorntoast","amount_g":80},{"name":"Avocado","amount_g":70},{"name":"Kichererbsen","amount_g":100},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Avocado zerdrücken, mit Kichererbsen auf den Toast geben, würzen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Kichererbsen', 'Vollkornbrot'),
  ('Bircher Müsli vegan', 'Klassisches Schweizer Müsli rein pflanzlich', 'breakfast'::meal_slot_kind, 417, 15, 60, 13, '1 Schale',
   '[{"name":"Haferflocken","amount_g":70},{"name":"Hafermilch","amount_g":200},{"name":"Apfel","amount_g":120},{"name":"Mandeln gehackt","amount_g":15},{"name":"Rosinen","amount_g":15}]'::jsonb, 'Alles mischen und mindestens 30 Minuten ziehen lassen.', ARRAY['vegan','mealprep','kalt','klassisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hafer', 'Haferflocken'),
  ('Quinoa-Frühstücksbowl mit Sojajoghurt', 'Protein-Bowl mit gekochtem Quinoa', 'breakfast'::meal_slot_kind, 396, 22, 50, 12, '1 Bowl',
   '[{"name":"Quinoa gekocht","amount_g":180},{"name":"Sojajoghurt","amount_g":150},{"name":"Blaubeeren","amount_g":80},{"name":"Kürbiskerne","amount_g":15}]'::jsonb, 'Quinoa kalt oder warm mit Sojajoghurt und Beeren anrichten.', ARRAY['vegan','mealprep','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojajoghurt', 'Quinoa'),
  ('Kichererbsenmehl-Pfannkuchen mit Spinat', 'Herzhafte Pancakes mit viel Eiweiß', 'breakfast'::meal_slot_kind, 390, 24, 42, 14, '2 Pfannkuchen',
   '[{"name":"Kichererbsenmehl","amount_g":80},{"name":"Wasser","amount_g":150},{"name":"Blattspinat","amount_g":100},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Mehl mit Wasser verrühren, Spinat zugeben, in der Pfanne backen.', ARRAY['vegan','high_protein','warm','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsenmehl', 'Kichererbsenmehl'),
  ('Haferwaffeln mit Apfelmus', 'Waffeln aus Haferflocken ohne Ei', 'breakfast'::meal_slot_kind, 412, 14, 62, 12, '2 Waffeln',
   '[{"name":"Haferflocken","amount_g":80},{"name":"Hafermilch","amount_g":150},{"name":"Apfelmus ungesüßt","amount_g":100},{"name":"Rapsöl","amount_g":8}]'::jsonb, 'Haferflocken mahlen, mit Hafermilch zum Teig rühren, Waffeln backen.', ARRAY['vegan','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Hafer', 'Haferflocken'),
  ('Erdnussbutter-Bananen-Sandwich', 'Schnelles Energie-Frühstück to go', 'breakfast'::meal_slot_kind, 456, 17, 52, 20, '1 Sandwich',
   '[{"name":"Vollkornbrot","amount_g":100},{"name":"Erdnussbutter","amount_g":30},{"name":"Banane","amount_g":110}]'::jsonb, 'Brot bestreichen, Bananenscheiben auflegen, zusammenklappen.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Erdnussbutter', 'Vollkornbrot'),
  ('Sojaquark mit Beeren und Leinsamen', 'Kalte Proteinquelle für den Morgen', 'breakfast'::meal_slot_kind, 308, 26, 24, 12, '1 Schale',
   '[{"name":"Sojaquark","amount_g":250},{"name":"Beerenmischung TK","amount_g":100},{"name":"Leinsamen geschrotet","amount_g":15}]'::jsonb, 'Sojaquark mit Beeren und Leinsamen verrühren.', ARRAY['vegan','high_protein','low_carb','kalt']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojaquark', 'Beeren'),
  ('Hafergrütze mit Zimt und Rosinen', 'Günstiger warmer Klassiker', 'breakfast'::meal_slot_kind, 389, 13, 64, 9, '1 Schale',
   '[{"name":"Haferflocken kernig","amount_g":75},{"name":"Wasser","amount_g":250},{"name":"Rosinen","amount_g":25},{"name":"Zimt","amount_g":2},{"name":"Walnüsse","amount_g":10}]'::jsonb, 'Haferflocken in Wasser weich kochen, Rosinen und Zimt zugeben.', ARRAY['vegan','warm','günstig','schnell']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hafer', 'Haferflocken'),
  ('Süßkartoffel-Hash mit Räuchertofu', 'Herzhaftes Pfannenfrühstück', 'breakfast'::meal_slot_kind, 424, 26, 44, 16, '1 Pfanne',
   '[{"name":"Süßkartoffel","amount_g":220},{"name":"Räuchertofu","amount_g":150},{"name":"Paprika","amount_g":80},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Süßkartoffelwürfel anbraten, Tofu und Paprika zugeben, würzen.', ARRAY['vegan','warm','high_protein','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Süßkartoffel'),
  ('Vollkornbagel mit Räuchertofu-Creme', 'Kalter Bagel mit pflanzlichem Aufstrich', 'breakfast'::meal_slot_kind, 430, 22, 54, 14, '1 Bagel',
   '[{"name":"Vollkornbagel","amount_g":90},{"name":"Räuchertofu","amount_g":100},{"name":"Sojajoghurt","amount_g":40},{"name":"Rucola","amount_g":20}]'::jsonb, 'Tofu mit Sojajoghurt pürieren, Bagel bestreichen und belegen.', ARRAY['vegan','kalt','schnell','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Bagel'),
  ('Green Smoothie Bowl mit Hanfprotein', 'Grüne Bowl mit Spinat und Mango', 'breakfast'::meal_slot_kind, 388, 24, 46, 12, '1 Bowl',
   '[{"name":"Hanfprotein","amount_g":25},{"name":"Blattspinat","amount_g":60},{"name":"Mango","amount_g":150},{"name":"Hafermilch","amount_g":200},{"name":"Haferflocken","amount_g":30}]'::jsonb, 'Spinat, Mango und Hafermilch mixen, Protein einrühren, mit Haferflocken toppen.', ARRAY['vegan','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hanfprotein', 'Mango'),
  ('Kichererbsen-Frühstückswrap mit Kala Namak', 'Wrap mit klassischer Frühstücksfüllung', 'breakfast'::meal_slot_kind, 419, 23, 48, 15, '1 Wrap',
   '[{"name":"Kichererbsenmehl","amount_g":60},{"name":"Vollkorn-Wrap","amount_g":70},{"name":"Paprika","amount_g":70},{"name":"Kala Namak","amount_g":2},{"name":"Olivenöl","amount_g":8}]'::jsonb, 'Kichererbsenmasse in der Pfanne stocken lassen, mit Paprika im Wrap rollen.', ARRAY['vegan','warm','high_protein']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsenmehl', 'Wrap'),
  ('Amaranth-Porridge mit Kakao und Nussmus', 'Schokoladiger Start mit Amaranth', 'breakfast'::meal_slot_kind, 432, 18, 54, 16, '1 Schale',
   '[{"name":"Amaranth gepufft","amount_g":50},{"name":"Hafermilch","amount_g":250},{"name":"Kakaopulver","amount_g":10},{"name":"Mandelmus","amount_g":20},{"name":"Banane","amount_g":90}]'::jsonb, 'Hafermilch erwärmen, Kakao und Mandelmus einrühren, Amaranth und Banane zugeben.', ARRAY['vegan','warm','schnell']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Mandelmus', 'Amaranth'),
  ('Vollkornbrot mit Linsenaufstrich und Tomate', 'Deftiger Linsenaufstrich auf Vollkornbrot', 'breakfast'::meal_slot_kind, 384, 21, 48, 12, '2 Scheiben',
   '[{"name":"Vollkornbrot","amount_g":100},{"name":"Rote Linsen gekocht","amount_g":120},{"name":"Tomate","amount_g":80},{"name":"Olivenöl","amount_g":8},{"name":"Zwiebel","amount_g":20}]'::jsonb, 'Linsen mit Zwiebel und Öl pürieren, Brot bestreichen, Tomate auflegen.', ARRAY['vegan','kalt','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Vollkornbrot'),
  ('Falafel-Bowl mit Bulgur und Tahinisauce', 'Orientalische Bowl mit Ofen-Falafel', 'lunch'::meal_slot_kind, 582, 28, 68, 22, '1 Bowl',
   '[{"name":"Falafel (Ofen)","amount_g":150},{"name":"Bulgur gekocht","amount_g":200},{"name":"Tomate","amount_g":80},{"name":"Tahini","amount_g":20},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Falafel im Ofen backen, mit Bulgur, Gemüse und Tahinisauce anrichten.', ARRAY['vegan','high_protein','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Kichererbsen', 'Bulgur'),
  ('Vollkornnudeln mit Erbsen-Minz-Pesto', 'Frisches Pesto mit hohem Erbsenanteil', 'lunch'::meal_slot_kind, 562, 26, 74, 18, '1 Teller',
   '[{"name":"Vollkornnudeln gekocht","amount_g":250},{"name":"Erbsen TK","amount_g":150},{"name":"Minze","amount_g":5},{"name":"Olivenöl","amount_g":15},{"name":"Cashews","amount_g":20}]'::jsonb, 'Erbsen mit Minze, Cashews und Öl pürieren, unter die Nudeln heben.', ARRAY['vegan','schnell','high_protein']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Erbsen', 'Vollkornnudeln'),
  ('Erbsen-Kichererbsen-Curry mit Hirse', 'Cremiges Curry mit doppelter Hülsenfrucht', 'lunch'::meal_slot_kind, 540, 27, 72, 16, '1 Teller',
   '[{"name":"Kichererbsen","amount_g":150},{"name":"Erbsen TK","amount_g":100},{"name":"Hirse gekocht","amount_g":200},{"name":"Kokosmilch light","amount_g":80},{"name":"Currypulver","amount_g":5}]'::jsonb, 'Hülsenfrüchte in Kokosmilch und Curry köcheln, mit Hirse servieren.', ARRAY['vegan','mealprep','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Hirse'),
  ('Bohnen-Burrito-Bowl mit Reis', 'Mexikanische Bowl mit schwarzen Bohnen', 'lunch'::meal_slot_kind, 550, 26, 80, 14, '1 Bowl',
   '[{"name":"Schwarze Bohnen","amount_g":180},{"name":"Reis gekocht","amount_g":220},{"name":"Mais","amount_g":60},{"name":"Salsa","amount_g":60},{"name":"Avocado","amount_g":40}]'::jsonb, 'Bohnen erwärmen, mit Reis, Mais, Salsa und Avocado schichten.', ARRAY['vegan','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Reis'),
  ('Quinoa-Salat mit schwarzen Bohnen und Mais', 'Kalter Meal-Prep-Salat fürs Büro', 'lunch'::meal_slot_kind, 504, 24, 66, 16, '1 Schale',
   '[{"name":"Quinoa gekocht","amount_g":200},{"name":"Schwarze Bohnen","amount_g":150},{"name":"Mais","amount_g":60},{"name":"Paprika","amount_g":80},{"name":"Olivenöl","amount_g":12}]'::jsonb, 'Alles vermengen, mit Limette und Kreuzkümmel abschmecken.', ARRAY['vegan','kalt','mealprep','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Bohnen', 'Quinoa'),
  ('Gemüse-Dal mit Basmatireis', 'Indisches Linsengericht mit Gemüse', 'lunch'::meal_slot_kind, 520, 25, 78, 12, '1 Teller',
   '[{"name":"Rote Linsen","amount_g":90},{"name":"Basmatireis gekocht","amount_g":200},{"name":"Möhren","amount_g":100},{"name":"Passierte Tomaten","amount_g":100},{"name":"Rapsöl","amount_g":8}]'::jsonb, 'Linsen mit Gemüse und Tomaten weich kochen, mit Reis servieren.', ARRAY['vegan','mealprep','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Reis'),
  ('Tempeh-Streifen mit Vollkornfladen', 'Würziger Tempeh im Fladenbrot', 'lunch'::meal_slot_kind, 548, 34, 58, 20, '1 Fladen',
   '[{"name":"Tempeh","amount_g":160},{"name":"Vollkornfladenbrot","amount_g":100},{"name":"Weißkohlsalat","amount_g":80},{"name":"Sojajoghurt","amount_g":50},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Tempeh würzen und braten, mit Salat und Sojajoghurt im Fladen servieren.', ARRAY['vegan','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tempeh', 'Fladenbrot'),
  ('Seitangeschnetzeltes mit Vollkornnudeln', 'Herzhaftes Geschnetzeltes rein pflanzlich', 'lunch'::meal_slot_kind, 558, 40, 68, 14, '1 Teller',
   '[{"name":"Seitan","amount_g":180},{"name":"Vollkornnudeln gekocht","amount_g":220},{"name":"Champignons","amount_g":100},{"name":"Sojacreme","amount_g":50},{"name":"Rapsöl","amount_g":8}]'::jsonb, 'Seitan mit Pilzen anbraten, mit Sojacreme ablöschen, Nudeln unterheben.', ARRAY['vegan','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Seitan', 'Vollkornnudeln'),
  ('Kartoffel-Kichererbsen-Curry', 'Sättigendes Curry ohne Reis', 'lunch'::meal_slot_kind, 503, 22, 70, 15, '1 Teller',
   '[{"name":"Kartoffeln","amount_g":300},{"name":"Kichererbsen","amount_g":150},{"name":"Kokosmilch light","amount_g":100},{"name":"Spinat","amount_g":80},{"name":"Currypaste","amount_g":15}]'::jsonb, 'Kartoffeln garen, mit Kichererbsen und Kokosmilch köcheln, Spinat unterheben.', ARRAY['vegan','mealprep','günstig','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Kartoffeln'),
  ('Nudelsalat mit Erbsenprotein-Pesto', 'Kalter Nudelsalat mit extra Eiweiß', 'lunch'::meal_slot_kind, 554, 30, 68, 18, '1 Schale',
   '[{"name":"Vollkornnudeln gekocht","amount_g":230},{"name":"Erbsenprotein","amount_g":20},{"name":"Basilikumpesto vegan","amount_g":30},{"name":"Kirschtomaten","amount_g":100},{"name":"Rucola","amount_g":20}]'::jsonb, 'Nudeln auskühlen lassen, mit Pesto und Protein mischen, Gemüse zugeben.', ARRAY['vegan','kalt','mealprep','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Erbsenprotein', 'Vollkornnudeln'),
  ('Vegane Linsen-Lasagne', 'Ofengericht mit Linsenragout', 'lunch'::meal_slot_kind, 562, 30, 70, 18, '1 Portion',
   '[{"name":"Vollkorn-Lasagneplatten","amount_g":90},{"name":"Rote Linsen","amount_g":90},{"name":"Passierte Tomaten","amount_g":200},{"name":"Sojacreme","amount_g":80},{"name":"Hefeflocken","amount_g":10}]'::jsonb, 'Linsenragout kochen, mit Platten schichten, Sojacreme darüber, 35 Min. backen.', ARRAY['vegan','mealprep','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'high'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Lasagneplatten'),
  ('Sojageschnetzeltes süß-sauer mit Reis', 'Asiatischer Klassiker pflanzlich', 'lunch'::meal_slot_kind, 556, 36, 76, 12, '1 Teller',
   '[{"name":"Sojaschnetzel trocken","amount_g":60},{"name":"Reis gekocht","amount_g":220},{"name":"Paprika","amount_g":100},{"name":"Ananas","amount_g":60},{"name":"Sojasauce","amount_g":15}]'::jsonb, 'Sojaschnetzel einweichen, anbraten, mit Gemüse und Sauce mischen.', ARRAY['vegan','high_protein','günstig','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Sojaschnetzel', 'Reis'),
  ('Buddha Bowl mit Edamame und Quinoa', 'Bunte Bowl mit Sojabohnen', 'lunch'::meal_slot_kind, 530, 30, 62, 18, '1 Bowl',
   '[{"name":"Edamame TK","amount_g":150},{"name":"Quinoa gekocht","amount_g":200},{"name":"Rotkohl","amount_g":80},{"name":"Möhren","amount_g":80},{"name":"Sesamöl","amount_g":10}]'::jsonb, 'Edamame garen, alles in der Schüssel anrichten, mit Sesamöl beträufeln.', ARRAY['vegan','kalt','high_protein','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Edamame', 'Quinoa'),
  ('Vollkorn-Wrap mit Räuchertofu und Gemüse', 'Handlicher Wrap für unterwegs', 'lunch'::meal_slot_kind, 493, 27, 58, 17, '1 Wrap',
   '[{"name":"Vollkorn-Wrap","amount_g":80},{"name":"Räuchertofu","amount_g":150},{"name":"Hummus","amount_g":40},{"name":"Salat","amount_g":40},{"name":"Paprika","amount_g":60}]'::jsonb, 'Wrap bestreichen, Tofu und Gemüse einrollen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Wrap'),
  ('Weiße-Bohnen-Eintopf mit Vollkornbrot', 'Deftiger Eintopf für kalte Tage', 'lunch'::meal_slot_kind, 476, 26, 66, 12, '1 Teller + Brot',
   '[{"name":"Weiße Bohnen","amount_g":220},{"name":"Möhren","amount_g":100},{"name":"Sellerie","amount_g":60},{"name":"Gemüsebrühe","amount_g":300},{"name":"Vollkornbrot","amount_g":60}]'::jsonb, 'Gemüse anschwitzen, mit Brühe und Bohnen 20 Minuten köcheln.', ARRAY['vegan','warm','günstig','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Vollkornbrot'),
  ('Sojaschnetzel-Gemüsepfanne mit Kartoffeln', 'Bunte Pfanne mit viel Eiweiß', 'lunch'::meal_slot_kind, 510, 34, 62, 14, '1 Pfanne',
   '[{"name":"Sojaschnetzel trocken","amount_g":55},{"name":"Kartoffeln","amount_g":280},{"name":"Zucchini","amount_g":100},{"name":"Zwiebel","amount_g":50},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Kartoffeln anbraten, eingeweichte Sojaschnetzel und Gemüse zugeben.', ARRAY['vegan','high_protein','günstig','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Sojaschnetzel', 'Kartoffeln'),
  ('Erbsensuppe mit Vollkornbrot', 'Klassische deftige Suppe ohne Fleisch', 'lunch'::meal_slot_kind, 474, 28, 68, 10, '1 großer Teller',
   '[{"name":"Trockenerbsen","amount_g":100},{"name":"Möhren","amount_g":80},{"name":"Kartoffeln","amount_g":120},{"name":"Gemüsebrühe","amount_g":400},{"name":"Vollkornbrot","amount_g":50}]'::jsonb, 'Erbsen mit Gemüse weich kochen, grob pürieren, mit Brot servieren.', ARRAY['vegan','warm','günstig','mealprep','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Erbsen', 'Kartoffeln'),
  ('Bulgur-Pfanne mit Kichererbsen und Spinat', 'Schnelle One-Pot-Pfanne', 'lunch'::meal_slot_kind, 502, 24, 70, 14, '1 Pfanne',
   '[{"name":"Bulgur gekocht","amount_g":220},{"name":"Kichererbsen","amount_g":150},{"name":"Blattspinat","amount_g":100},{"name":"Olivenöl","amount_g":10},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Alles in der Pfanne erhitzen, mit Zitrone abschmecken.', ARRAY['vegan','schnell','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Bulgur'),
  ('Reisnudel-Salat mit Erdnusssauce und Tofu', 'Asiatischer kalter Nudelsalat', 'lunch'::meal_slot_kind, 564, 28, 68, 20, '1 Schale',
   '[{"name":"Reisnudeln gekocht","amount_g":200},{"name":"Naturtofu","amount_g":150},{"name":"Möhren","amount_g":80},{"name":"Erdnussmus","amount_g":25},{"name":"Sojasauce","amount_g":15}]'::jsonb, 'Tofu anbraten, Sauce anrühren, alles mit Nudeln vermengen.', ARRAY['vegan','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Reisnudeln'),
  ('Ofengemüse mit Linsen und Tahini', 'Warmes Ofenblech mit Belugalinsen', 'lunch'::meal_slot_kind, 502, 25, 60, 18, '1 Blechportion',
   '[{"name":"Belugalinsen gekocht","amount_g":200},{"name":"Süßkartoffel","amount_g":180},{"name":"Blumenkohl","amount_g":120},{"name":"Tahini","amount_g":20},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Gemüse 25 Minuten backen, mit Linsen mischen, Tahinisauce darüber.', ARRAY['vegan','mealprep','warm','high_protein']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Linsen', 'Süßkartoffel'),
  ('Tofu-Curry mit Blumenkohlreis', 'Low-Carb-Curry am Abend', 'dinner'::meal_slot_kind, 396, 32, 22, 20, '1 Teller',
   '[{"name":"Naturtofu","amount_g":200},{"name":"Blumenkohlreis","amount_g":250},{"name":"Kokosmilch light","amount_g":100},{"name":"Currypaste","amount_g":15},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Tofu anbraten, Currysauce zugeben, Blumenkohlreis kurz mitgaren.', ARRAY['vegan','low_carb','high_protein','warm']::text[], ARRAY[]::text[],
   false, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Blumenkohl'),
  ('Ofenkartoffel mit Kichererbsen-Guacamole', 'Sättigend und einfach', 'dinner'::meal_slot_kind, 490, 20, 62, 18, '1 große Kartoffel',
   '[{"name":"Kartoffel","amount_g":350},{"name":"Kichererbsen","amount_g":120},{"name":"Avocado","amount_g":60},{"name":"Limette","amount_g":10},{"name":"Olivenöl","amount_g":8}]'::jsonb, 'Kartoffel im Ofen garen, Kichererbsen mit Avocado zerdrücken, füllen.', ARRAY['vegan','warm','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Kartoffeln'),
  ('Vegane Bolognese mit Sojahack', 'Klassische Bolognese rein pflanzlich', 'dinner'::meal_slot_kind, 526, 34, 66, 14, '1 Teller',
   '[{"name":"Sojahack trocken","amount_g":55},{"name":"Vollkornspaghetti gekocht","amount_g":220},{"name":"Passierte Tomaten","amount_g":200},{"name":"Zwiebel","amount_g":50},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Sojahack anbraten, mit Tomaten köcheln, über Spaghetti geben.', ARRAY['vegan','high_protein','klassisch','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Sojahack', 'Vollkornnudeln'),
  ('Gefüllte Paprika mit Linsen und Reis', 'Ofengericht mit Hülsenfrüchten', 'dinner'::meal_slot_kind, 452, 24, 62, 12, '2 Paprika',
   '[{"name":"Paprika","amount_g":250},{"name":"Rote Linsen gekocht","amount_g":150},{"name":"Reis gekocht","amount_g":150},{"name":"Passierte Tomaten","amount_g":100},{"name":"Olivenöl","amount_g":8}]'::jsonb, 'Paprika füllen und 30 Minuten im Ofen garen.', ARRAY['vegan','mealprep','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Reis'),
  ('Kichererbsen-Spinat-Pfanne mit Vollkornbrot', 'Schnelle Abendpfanne', 'dinner'::meal_slot_kind, 440, 24, 50, 16, '1 Pfanne + Brot',
   '[{"name":"Kichererbsen","amount_g":200},{"name":"Blattspinat","amount_g":150},{"name":"Vollkornbrot","amount_g":60},{"name":"Knoblauch","amount_g":5},{"name":"Olivenöl","amount_g":12}]'::jsonb, 'Kichererbsen mit Knoblauch anbraten, Spinat zusammenfallen lassen.', ARRAY['vegan','schnell','günstig','warm']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Vollkornbrot'),
  ('Miso-Gemüsesuppe mit Tofu', 'Leichte japanische Suppe', 'dinner'::meal_slot_kind, 258, 22, 20, 10, '1 großer Teller',
   '[{"name":"Naturtofu","amount_g":180},{"name":"Misopaste","amount_g":25},{"name":"Pak Choi","amount_g":120},{"name":"Frühlingszwiebel","amount_g":30},{"name":"Wasser","amount_g":400}]'::jsonb, 'Brühe erhitzen, Miso einrühren, Tofu und Gemüse kurz ziehen lassen.', ARRAY['vegan','low_carb','warm','schnell']::text[], ARRAY[]::text[],
   false, true, false, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Gemüse'),
  ('Chili sin Carne mit Bohnenmix', 'Scharfer Bohneneintopf ohne Beilage', 'dinner'::meal_slot_kind, 436, 26, 56, 12, '1 Schale',
   '[{"name":"Kidneybohnen","amount_g":180},{"name":"Schwarze Bohnen","amount_g":120},{"name":"Passierte Tomaten","amount_g":200},{"name":"Mais","amount_g":60},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Alles 20 Minuten köcheln und scharf abschmecken.', ARRAY['vegan','mealprep','günstig','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Bohnen'),
  ('Tempeh-Filets mit Ofengemüse', 'Marinierter Tempeh vom Blech', 'dinner'::meal_slot_kind, 470, 34, 34, 22, '1 Blechportion',
   '[{"name":"Tempeh","amount_g":180},{"name":"Zucchini","amount_g":150},{"name":"Paprika","amount_g":120},{"name":"Olivenöl","amount_g":12},{"name":"Sojasauce","amount_g":15}]'::jsonb, 'Tempeh marinieren, mit Gemüse 25 Minuten backen.', ARRAY['vegan','high_protein','low_carb','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tempeh', 'Gemüse'),
  ('Zucchini-Nudeln mit Erdnuss-Tofu', 'Leichtes Low-Carb-Abendessen', 'dinner'::meal_slot_kind, 424, 30, 22, 24, '1 Teller',
   '[{"name":"Zucchini","amount_g":300},{"name":"Naturtofu","amount_g":180},{"name":"Erdnussmus","amount_g":20},{"name":"Sojasauce","amount_g":15},{"name":"Sesamöl","amount_g":8}]'::jsonb, 'Zucchinistreifen kurz braten, Tofu mit Erdnusssauce zugeben.', ARRAY['vegan','low_carb','high_protein']::text[], ARRAY[]::text[],
   false, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Zucchini'),
  ('Vollkornbrot mit Räuchertofu-Aufstrich und Salat', 'Kaltes Abendbrot pflanzlich', 'dinner'::meal_slot_kind, 424, 24, 46, 16, '3 Scheiben',
   '[{"name":"Vollkornbrot","amount_g":100},{"name":"Räuchertofu","amount_g":120},{"name":"Sojajoghurt","amount_g":40},{"name":"Blattsalat","amount_g":60},{"name":"Tomate","amount_g":60}]'::jsonb, 'Tofu mit Sojajoghurt pürieren, Brot bestreichen, Salat dazu.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Tofu', 'Vollkornbrot'),
  ('Bratkartoffeln mit Sojaschnetzel', 'Deftiger Klassiker mit Eiweiß', 'dinner'::meal_slot_kind, 496, 30, 58, 16, '1 Pfanne',
   '[{"name":"Kartoffeln","amount_g":300},{"name":"Sojaschnetzel trocken","amount_g":50},{"name":"Zwiebel","amount_g":60},{"name":"Rapsöl","amount_g":12},{"name":"Paprikapulver","amount_g":3}]'::jsonb, 'Kartoffeln knusprig braten, Sojaschnetzel und Zwiebeln zugeben.', ARRAY['vegan','günstig','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Sojaschnetzel', 'Kartoffeln'),
  ('Vegane Gemüsepizza mit Hefeschmelz', 'Pizza mit pflanzlichem Hefeschmelz', 'dinner'::meal_slot_kind, 546, 24, 72, 18, '1 kleine Pizza',
   '[{"name":"Vollkornpizzateig","amount_g":180},{"name":"Passierte Tomaten","amount_g":80},{"name":"Hefeschmelz","amount_g":60},{"name":"Champignons","amount_g":80},{"name":"Paprika","amount_g":70}]'::jsonb, 'Teig belegen, Hefeschmelz verteilen, 15 Minuten backen.', ARRAY['vegan','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Hefeschmelz', 'Pizzateig'),
  ('Rote-Linsen-Kokos-Suppe', 'Cremige Suppe mit Ingwer', 'dinner'::meal_slot_kind, 422, 22, 52, 14, '1 großer Teller',
   '[{"name":"Rote Linsen","amount_g":90},{"name":"Kokosmilch light","amount_g":120},{"name":"Möhren","amount_g":120},{"name":"Ingwer","amount_g":8},{"name":"Gemüsebrühe","amount_g":350}]'::jsonb, 'Alles weich kochen und pürieren.', ARRAY['vegan','mealprep','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Möhren'),
  ('Süßkartoffel-Bohnen-Auflauf', 'Ofenauflauf mit Kidneybohnen', 'dinner'::meal_slot_kind, 486, 24, 66, 14, '1 Portion',
   '[{"name":"Süßkartoffel","amount_g":280},{"name":"Kidneybohnen","amount_g":180},{"name":"Passierte Tomaten","amount_g":120},{"name":"Hefeflocken","amount_g":10},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Alles schichten und 30 Minuten backen.', ARRAY['vegan','mealprep','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Süßkartoffel'),
  ('Grünkohl-Kartoffel-Pfanne mit Räuchertofu', 'Winterliche Pfanne mit Grünkohl', 'dinner'::meal_slot_kind, 474, 28, 50, 18, '1 Pfanne',
   '[{"name":"Grünkohl","amount_g":200},{"name":"Kartoffeln","amount_g":250},{"name":"Räuchertofu","amount_g":150},{"name":"Rapsöl","amount_g":12},{"name":"Senf","amount_g":8}]'::jsonb, 'Kartoffeln garen, Grünkohl und Tofu dazugeben, kräftig würzen.', ARRAY['vegan','warm','günstig','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Tofu', 'Kartoffeln'),
  ('Couscous mit Ofengemüse und Kichererbsen', 'Mediterrane Kombination vom Blech', 'dinner'::meal_slot_kind, 486, 22, 68, 14, '1 Teller',
   '[{"name":"Couscous gekocht","amount_g":200},{"name":"Kichererbsen","amount_g":150},{"name":"Aubergine","amount_g":120},{"name":"Paprika","amount_g":100},{"name":"Olivenöl","amount_g":12}]'::jsonb, 'Gemüse backen, mit Couscous und Kichererbsen mischen.', ARRAY['vegan','mealprep','warm']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Couscous'),
  ('Erbsen-Risotto mit Hefeflocken', 'Cremiges Risotto ohne Käse', 'dinner'::meal_slot_kind, 494, 22, 70, 14, '1 Teller',
   '[{"name":"Risottoreis gekocht","amount_g":250},{"name":"Erbsen TK","amount_g":150},{"name":"Hefeflocken","amount_g":15},{"name":"Gemüsebrühe","amount_g":200},{"name":"Olivenöl","amount_g":12}]'::jsonb, 'Reis in Brühe garen, Erbsen und Hefeflocken unterrühren.', ARRAY['vegan','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Erbsen', 'Risottoreis'),
  ('Falafel mit Sojajoghurt-Gurken-Salat', 'Leichtes Abendessen mit Dip', 'dinner'::meal_slot_kind, 460, 26, 44, 20, '6 Falafel + Salat',
   '[{"name":"Falafel (Ofen)","amount_g":160},{"name":"Sojajoghurt","amount_g":120},{"name":"Gurke","amount_g":150},{"name":"Minze","amount_g":5},{"name":"Olivenöl","amount_g":8}]'::jsonb, 'Falafel backen, Sojajoghurt mit Gurke und Minze anrühren.', ARRAY['vegan','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Kichererbsen', 'Falafel'),
  ('Gemüsecurry mit Edamame und Reis', 'Currypfanne mit Sojabohnen', 'dinner'::meal_slot_kind, 494, 28, 64, 14, '1 Teller',
   '[{"name":"Edamame TK","amount_g":160},{"name":"Reis gekocht","amount_g":200},{"name":"Brokkoli","amount_g":120},{"name":"Kokosmilch light","amount_g":80},{"name":"Currypulver","amount_g":5}]'::jsonb, 'Gemüse und Edamame in Kokossauce garen, mit Reis servieren.', ARRAY['vegan','high_protein','mealprep','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Edamame', 'Reis'),
  ('Pilz-Stroganoff mit Vollkornnudeln', 'Cremige Pilzpfanne ohne Sahne', 'dinner'::meal_slot_kind, 496, 22, 66, 16, '1 Teller',
   '[{"name":"Champignons","amount_g":250},{"name":"Vollkornnudeln gekocht","amount_g":220},{"name":"Sojacreme","amount_g":80},{"name":"Zwiebel","amount_g":50},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Pilze scharf anbraten, mit Sojacreme binden, Nudeln zugeben.', ARRAY['vegan','warm','günstig','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Champignons', 'Vollkornnudeln'),
  ('Weiße Bohnen auf Vollkorntoast', 'Schnelle Baked Beans selbst gemacht', 'dinner'::meal_slot_kind, 434, 24, 62, 10, '2 Scheiben Toast',
   '[{"name":"Weiße Bohnen","amount_g":250},{"name":"Passierte Tomaten","amount_g":120},{"name":"Vollkorntoast","amount_g":80},{"name":"Zwiebel","amount_g":40},{"name":"Olivenöl","amount_g":8}]'::jsonb, 'Bohnen in Tomatensauce köcheln, auf getoastetem Brot servieren.', ARRAY['vegan','schnell','günstig','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Vollkornbrot'),
  ('Buchweizen-Gemüsepfanne mit Nüssen', 'Nussige Pfanne mit Buchweizen', 'dinner'::meal_slot_kind, 500, 20, 60, 20, '1 Pfanne',
   '[{"name":"Buchweizen gekocht","amount_g":220},{"name":"Zucchini","amount_g":120},{"name":"Möhren","amount_g":100},{"name":"Walnüsse","amount_g":25},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Gemüse anbraten, Buchweizen und Nüsse untermischen.', ARRAY['vegan','warm','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Buchweizen', 'Buchweizen'),
  ('Sojajoghurt mit Proteinpulver und Beeren', 'Schneller Proteinsnack', 'snack'::meal_slot_kind, 246, 28, 20, 6, '1 Becher',
   '[{"name":"Sojajoghurt","amount_g":200},{"name":"Erbsenprotein","amount_g":20},{"name":"Beerenmischung TK","amount_g":80}]'::jsonb, 'Protein unter den Sojajoghurt rühren, Beeren zugeben.', ARRAY['vegan','high_protein','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojajoghurt', 'Beeren'),
  ('Geröstete Erdnüsse ungesalzen', 'Kompakter Energie-Snack', 'snack'::meal_slot_kind, 296, 12, 8, 24, '40 g',
   '[{"name":"Erdnüsse geröstet","amount_g":40}]'::jsonb, 'Portionieren und genießen.', ARRAY['vegan','kalt','schnell','low_carb','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Erdnüsse', 'Erdnüsse'),
  ('Hummus mit Vollkornknäckebrot', 'Herzhafter Snack für zwischendurch', 'snack'::meal_slot_kind, 272, 11, 30, 12, '3 Knäcke + Dip',
   '[{"name":"Hummus","amount_g":80},{"name":"Vollkornknäckebrot","amount_g":40}]'::jsonb, 'Knäckebrot mit Hummus bestreichen.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Knäckebrot'),
  ('Veganer Proteinshake mit Hafermilch', 'Post-Workout-Shake pflanzlich', 'snack'::meal_slot_kind, 270, 30, 24, 6, '1 Shaker (400 ml)',
   '[{"name":"Erbsen-Reis-Protein","amount_g":30},{"name":"Hafermilch","amount_g":300}]'::jsonb, 'Protein mit Hafermilch shaken.', ARRAY['vegan','high_protein','post_workout','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Pflanzenprotein', 'Hafermilch'),
  ('Geröstete Kichererbsen', 'Knuspriger Ofensnack', 'snack'::meal_slot_kind, 244, 13, 30, 8, '150 g',
   '[{"name":"Kichererbsen","amount_g":150},{"name":"Olivenöl","amount_g":6},{"name":"Paprikapulver","amount_g":3}]'::jsonb, 'Kichererbsen mit Öl und Gewürzen 25 Minuten im Ofen rösten.', ARRAY['vegan','mealprep','kalt','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Kichererbsen'),
  ('Reiswaffeln mit Erdnussmus und Banane', 'Schneller Kohlenhydrat-Snack', 'snack'::meal_slot_kind, 304, 9, 40, 12, '3 Reiswaffeln',
   '[{"name":"Reiswaffeln","amount_g":30},{"name":"Erdnussmus","amount_g":20},{"name":"Banane","amount_g":80}]'::jsonb, 'Reiswaffeln bestreichen und mit Bananenscheiben belegen.', ARRAY['vegan','kalt','schnell','pre_workout']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Erdnussmus', 'Reiswaffeln'),
  ('Kakao-Sojadrink', 'Trinkbarer Snack mit Eiweiß', 'snack'::meal_slot_kind, 216, 14, 22, 8, '1 Glas (350 ml)',
   '[{"name":"Sojadrink ungesüßt","amount_g":350},{"name":"Kakaopulver","amount_g":12},{"name":"Ahornsirup","amount_g":8}]'::jsonb, 'Sojadrink erwärmen, Kakao und Sirup einrühren.', ARRAY['vegan','warm','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojadrink', 'Kakao'),
  ('Kürbiskerne und Cashews', 'Mineralstoffreicher Nussmix', 'snack'::meal_slot_kind, 294, 12, 12, 22, '40 g',
   '[{"name":"Kürbiskerne","amount_g":20},{"name":"Cashewkerne","amount_g":20}]'::jsonb, 'Mischen und portionieren.', ARRAY['vegan','kalt','schnell','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Kerne', 'Nüsse'),
  ('Knäckebrot mit Avocado und Tomate', 'Frischer herzhafter Snack', 'snack'::meal_slot_kind, 258, 7, 26, 14, '3 Scheiben',
   '[{"name":"Vollkornknäckebrot","amount_g":40},{"name":"Avocado","amount_g":60},{"name":"Tomate","amount_g":60}]'::jsonb, 'Avocado zerdrücken, aufstreichen, Tomate auflegen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Avocado', 'Knäckebrot'),
  ('Energy Balls mit Datteln und Haferflocken', 'Selbstgemachte Kugeln für die Woche', 'snack'::meal_slot_kind, 316, 8, 44, 12, '4 Kugeln',
   '[{"name":"Datteln","amount_g":60},{"name":"Haferflocken","amount_g":40},{"name":"Mandelmus","amount_g":15},{"name":"Kakaopulver","amount_g":5}]'::jsonb, 'Alles im Mixer zerkleinern, Kugeln formen, kühlen.', ARRAY['vegan','mealprep','kalt','pre_workout']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Mandelmus', 'Datteln'),
  ('Edamame-Dip mit Gurkensticks', 'Grüner Proteindip', 'snack'::meal_slot_kind, 218, 16, 16, 10, '1 Schälchen',
   '[{"name":"Edamame TK","amount_g":150},{"name":"Gurke","amount_g":120},{"name":"Olivenöl","amount_g":8},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Edamame garen und pürieren, mit Gurkensticks servieren.', ARRAY['vegan','high_protein','low_carb','kalt']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Edamame', 'Gurke'),
  ('Bananen-Erdnuss-Shake mit Sojadrink', 'Kalorienreicher Aufbau-Shake', 'snack'::meal_slot_kind, 394, 18, 40, 18, '1 Glas (450 ml)',
   '[{"name":"Sojadrink ungesüßt","amount_g":300},{"name":"Banane","amount_g":120},{"name":"Erdnussmus","amount_g":25}]'::jsonb, 'Alles glatt mixen.', ARRAY['vegan','schnell','post_workout']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojadrink', 'Banane'),
  ('Sojajoghurt mit Granola', 'Süßer Löffelsnack', 'snack'::meal_slot_kind, 312, 13, 38, 12, '1 Becher',
   '[{"name":"Sojajoghurt","amount_g":200},{"name":"Granola","amount_g":45}]'::jsonb, 'Granola über den Sojajoghurt geben.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sojajoghurt', 'Granola'),
  ('Mini-Wrap mit Hummus und Rucola', 'Handlicher Snack für unterwegs', 'snack'::meal_slot_kind, 267, 10, 32, 11, '1 Mini-Wrap',
   '[{"name":"Vollkorn-Wrap","amount_g":45},{"name":"Hummus","amount_g":50},{"name":"Rucola","amount_g":20}]'::jsonb, 'Wrap bestreichen, Rucola einrollen.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Wrap'),
  ('Apfelscheiben mit Zimt und Walnüssen', 'Fruchtiger Snack mit gesunden Fetten', 'snack'::meal_slot_kind, 242, 5, 24, 14, '1 Apfel + Nüsse',
   '[{"name":"Apfel","amount_g":160},{"name":"Walnüsse","amount_g":20},{"name":"Zimt","amount_g":2}]'::jsonb, 'Apfel schneiden, mit Zimt bestreuen, Nüsse dazu.', ARRAY['vegan','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Walnüsse', 'Apfel'),
  ('Sojaquark mit Kakao', 'Pflanzlicher Proteinpudding', 'snack'::meal_slot_kind, 224, 24, 14, 8, '1 Schale',
   '[{"name":"Sojaquark","amount_g":220},{"name":"Kakaopulver","amount_g":10},{"name":"Süßstoff","amount_g":2}]'::jsonb, 'Kakao unter den Sojaquark rühren.', ARRAY['vegan','high_protein','low_carb','kalt']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojaquark', 'Kakao'),
  ('Selbstgemachtes Popcorn', 'Leichter Abendsnack', 'snack'::meal_slot_kind, 220, 5, 32, 8, '1 Schüssel',
   '[{"name":"Popcornmais","amount_g":40},{"name":"Rapsöl","amount_g":7}]'::jsonb, 'Mais im Topf mit wenig Öl aufpoppen, leicht salzen.', ARRAY['vegan','warm','günstig','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Mais', 'Mais'),
  ('Vollkornbrot mit Makrele und Meerrettich', 'Kräftiges Fischfrühstück', 'breakfast'::meal_slot_kind, 452, 30, 38, 20, '2 Scheiben',
   '[{"name":"Vollkornbrot","amount_g":90},{"name":"Räuchermakrele","amount_g":100},{"name":"Meerrettich","amount_g":15},{"name":"Gurke","amount_g":60}]'::jsonb, 'Makrele zerpflücken, mit Meerrettich auf dem Brot verteilen.', ARRAY['pescetarisch','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Makrele', 'Vollkornbrot'),
  ('Matjesbrot mit Zwiebeln', 'Norddeutscher Klassiker', 'breakfast'::meal_slot_kind, 426, 26, 40, 18, '2 Scheiben',
   '[{"name":"Vollkornbrot","amount_g":100},{"name":"Matjesfilet","amount_g":90},{"name":"Zwiebel","amount_g":40},{"name":"Apfel","amount_g":50}]'::jsonb, 'Matjes auf Brot legen, mit Zwiebel- und Apfelscheiben belegen.', ARRAY['pescetarisch','kalt','klassisch']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Matjes', 'Vollkornbrot'),
  ('Sardinen auf Vollkornknäckebrot', 'Omega-3-reicher Start', 'breakfast'::meal_slot_kind, 356, 27, 26, 16, '4 Knäcke',
   '[{"name":"Sardinen in Öl abgetropft","amount_g":90},{"name":"Vollkornknäckebrot","amount_g":50},{"name":"Tomate","amount_g":60},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Sardinen auf Knäckebrot verteilen, Tomate und Zitrone dazu.', ARRAY['pescetarisch','kalt','schnell','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Sardinen', 'Knäckebrot'),
  ('Kabeljau mit Kartoffeln und Senfsauce', 'Klassisches Fischgericht', 'lunch'::meal_slot_kind, 502, 42, 52, 14, '1 Teller',
   '[{"name":"Kabeljaufilet","amount_g":200},{"name":"Kartoffeln","amount_g":280},{"name":"Senf","amount_g":15},{"name":"Sojacreme","amount_g":60},{"name":"Rapsöl","amount_g":8}]'::jsonb, 'Fisch garen, Senfsauce anrühren, mit Kartoffeln servieren.', ARRAY['pescetarisch','klassisch','high_protein']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Kabeljau', 'Kartoffeln'),
  ('Garnelen-Nudelsalat mit Zitrone', 'Frischer Salat fürs Büro', 'lunch'::meal_slot_kind, 502, 36, 58, 14, '1 Schale',
   '[{"name":"Garnelen","amount_g":180},{"name":"Vollkornnudeln gekocht","amount_g":200},{"name":"Kirschtomaten","amount_g":100},{"name":"Rucola","amount_g":30},{"name":"Olivenöl","amount_g":12}]'::jsonb, 'Garnelen kurz braten, mit Nudeln und Gemüse mischen.', ARRAY['pescetarisch','kalt','mealprep','high_protein']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Garnelen', 'Vollkornnudeln'),
  ('Fischcurry mit Pangasius und Reis', 'Mildes Curry mit Weißfisch', 'lunch'::meal_slot_kind, 542, 38, 66, 14, '1 Teller',
   '[{"name":"Pangasiusfilet","amount_g":200},{"name":"Reis gekocht","amount_g":220},{"name":"Kokosmilch light","amount_g":100},{"name":"Paprika","amount_g":80},{"name":"Currypaste","amount_g":12}]'::jsonb, 'Fisch in Currysauce garen, mit Reis servieren.', ARRAY['pescetarisch','warm','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Pangasius', 'Reis'),
  ('Zanderfilet mit Rahmspinat und Kartoffeln', 'Feines Abendessen mit Süßwasserfisch', 'dinner'::meal_slot_kind, 488, 42, 44, 16, '1 Teller',
   '[{"name":"Zanderfilet","amount_g":200},{"name":"Blattspinat","amount_g":200},{"name":"Kartoffeln","amount_g":220},{"name":"Sojacreme","amount_g":60},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Zander braten, Spinat mit Sojacreme binden, Kartoffeln dazu.', ARRAY['pescetarisch','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Zander', 'Kartoffeln'),
  ('Miesmuscheln in Tomatensud mit Vollkornbrot', 'Mediterranes Muschelgericht', 'dinner'::meal_slot_kind, 412, 34, 42, 12, '1 Topf',
   '[{"name":"Miesmuscheln","amount_g":500},{"name":"Passierte Tomaten","amount_g":200},{"name":"Vollkornbrot","amount_g":60},{"name":"Knoblauch","amount_g":8},{"name":"Olivenöl","amount_g":10}]'::jsonb, 'Muscheln im Tomatensud öffnen lassen, mit Brot servieren.', ARRAY['pescetarisch','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Miesmuscheln', 'Vollkornbrot'),
  ('Fischfrikadellen mit Kartoffelsalat', 'Hausmannskost mit Seelachs', 'dinner'::meal_slot_kind, 514, 38, 50, 18, '2 Frikadellen + Salat',
   '[{"name":"Seelachsfilet","amount_g":200},{"name":"Kartoffeln","amount_g":250},{"name":"Zwiebel","amount_g":40},{"name":"Joghurtdressing","amount_g":60},{"name":"Rapsöl","amount_g":10}]'::jsonb, 'Fisch hacken, Frikadellen formen und braten, Kartoffelsalat dazu.', ARRAY['pescetarisch','klassisch','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'high'::meal_effort_level, 'medium'::meal_budget_level, 'Seelachs', 'Kartoffeln'),
  ('Makrelenfilet auf Gurkenscheiben', 'Low-Carb-Snack mit Omega-3', 'snack'::meal_slot_kind, 222, 20, 4, 14, '1 Portion',
   '[{"name":"Räuchermakrele","amount_g":80},{"name":"Gurke","amount_g":120},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Makrele auf Gurkenscheiben setzen, Zitrone darüber.', ARRAY['pescetarisch','low_carb','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Makrele', 'Gurke'),
  ('Räucherforelle auf Knäckebrot', 'Herzhafter Fischsnack', 'snack'::meal_slot_kind, 240, 22, 20, 8, '3 Knäcke',
   '[{"name":"Räucherforellenfilet","amount_g":90},{"name":"Vollkornknäckebrot","amount_g":35},{"name":"Frischkäse light","amount_g":30},{"name":"Dill","amount_g":3}]'::jsonb, 'Knäckebrot bestreichen und mit Forelle belegen.', ARRAY['pescetarisch','kalt','high_protein','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Forelle', 'Knäckebrot'),
  ('Shrimps-Cocktail mit Joghurtdip', 'Leichter Proteinsnack', 'snack'::meal_slot_kind, 182, 24, 8, 6, '1 Schälchen',
   '[{"name":"Garnelen gegart","amount_g":130},{"name":"Joghurt 1,5%","amount_g":60},{"name":"Tomatenmark","amount_g":15},{"name":"Zitrone","amount_g":10}]'::jsonb, 'Dip anrühren, Garnelen darin wenden.', ARRAY['pescetarisch','low_carb','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'high'::meal_budget_level, 'Garnelen', 'Gurke')
) AS s(name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
       ingredients, instructions, tags, no_go_ingredients,
       suitable_training, suitable_rest, mealprep_ok, eat_cold,
       effort, budget, main_protein, main_carb)
WHERE NOT EXISTS (
  SELECT 1 FROM public.coach_meal_library m
  WHERE lower(m.name) = lower(s.name) AND m.category = s.category
);
