-- BodyFuel: Gerichtsbibliothek auf >= 100 aktive Gerichte erweitern (idempotent)
INSERT INTO public.coach_meal_library (
  name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
  ingredients, instructions, tags, no_go_ingredients,
  suitable_training, suitable_rest, mealprep_ok, eat_cold,
  effort, budget, main_protein, main_carb, is_system, is_active
)
SELECT s.name, s.description, s.category, s.kcal, s.protein_g, s.carbs_g, s.fat_g, s.portion_label,
       s.ingredients, s.instructions, s.tags, s.no_go_ingredients,
       s.suitable_training, s.suitable_rest, s.mealprep_ok, s.eat_cold,
       s.effort, s.budget, s.main_protein, s.main_carb, true, true
FROM (VALUES
  ('Haferbrei mit Beeren und Skyr', 'Warmer Porridge mit Skyr und Beerenmischung', 'breakfast'::meal_slot_kind, 401, 22.0, 58.0, 9.0, '1 Schale (ca. 420 g)',
   '[{"name": "Haferflocken", "amount_g": 70}, {"name": "Milch 1,5%", "amount_g": 200}, {"name": "Skyr natur", "amount_g": 100}, {"name": "Beerenmischung TK", "amount_g": 80}]'::jsonb, 'Haferflocken mit Milch aufkochen, 4 Minuten quellen lassen, Skyr und Beeren unterheben.', ARRAY['high_protein','klassisch','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Skyr', 'Haferflocken'),
  ('Rührei mit Vollkorntoast', 'Klassiker mit drei Eiern und Vollkornbrot', 'breakfast'::meal_slot_kind, 434, 27.0, 32.0, 22.0, '3 Eier + 2 Scheiben',
   '[{"name": "Eier", "amount_g": 165}, {"name": "Vollkorntoast", "amount_g": 70}, {"name": "Butter", "amount_g": 10}, {"name": "Schnittlauch", "amount_g": 5}]'::jsonb, 'Eier verquirlen, in Butter stocken lassen, mit Toast servieren.', ARRAY['klassisch','high_protein','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Ei', 'Vollkornbrot'),
  ('Skyr-Bowl mit Banane und Nüssen', 'Kalte Bowl für schnelle Morgen', 'breakfast'::meal_slot_kind, 426, 30.0, 45.0, 14.0, '1 Bowl (ca. 400 g)',
   '[{"name": "Skyr natur", "amount_g": 250}, {"name": "Banane", "amount_g": 110}, {"name": "Walnüsse", "amount_g": 20}, {"name": "Honig", "amount_g": 10}]'::jsonb, 'Skyr in eine Schüssel geben, Banane in Scheiben und Nüsse darüber, mit Honig abrunden.', ARRAY['high_protein','kalt','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Skyr', 'Banane'),
  ('Overnight Oats mit Apfel und Zimt', 'Am Vorabend vorbereitet, morgens sofort essbar', 'breakfast'::meal_slot_kind, 395, 18.0, 56.0, 11.0, '1 Glas (ca. 400 g)',
   '[{"name": "Haferflocken", "amount_g": 60}, {"name": "Milch 1,5%", "amount_g": 200}, {"name": "Apfel", "amount_g": 120}, {"name": "Magerquark", "amount_g": 80}, {"name": "Zimt", "amount_g": 2}]'::jsonb, 'Alles im Glas vermischen und über Nacht kühlen.', ARRAY['mealprep','kalt','günstig','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Haferflocken'),
  ('Vollkornbrot mit Hüttenkäse und Tomate', 'Herzhaftes Frühstück ohne Kochen', 'breakfast'::meal_slot_kind, 337, 26.0, 38.0, 9.0, '2 Scheiben',
   '[{"name": "Vollkornbrot", "amount_g": 90}, {"name": "Hüttenkäse", "amount_g": 150}, {"name": "Tomate", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 5}]'::jsonb, 'Brot belegen, Tomatenscheiben auflegen, salzen und pfeffern.', ARRAY['high_protein','kalt','schnell','vegetarisch','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hüttenkäse', 'Vollkornbrot'),
  ('Protein-Pancakes mit Quark', 'Fluffige Pfannkuchen mit hohem Eiweißanteil', 'breakfast'::meal_slot_kind, 452, 38.0, 48.0, 12.0, '3 Pancakes',
   '[{"name": "Magerquark", "amount_g": 200}, {"name": "Haferflocken", "amount_g": 60}, {"name": "Eier", "amount_g": 110}, {"name": "Backpulver", "amount_g": 3}, {"name": "Beeren", "amount_g": 60}]'::jsonb, 'Alles verrühren, portionsweise in beschichteter Pfanne backen.', ARRAY['high_protein','vegetarisch','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Haferflocken'),
  ('Vollkornbrötchen mit Putenbrust', 'Schnelles herzhaftes Frühstück to go', 'breakfast'::meal_slot_kind, 364, 31.0, 42.0, 8.0, '1 Brötchen',
   '[{"name": "Vollkornbrötchen", "amount_g": 80}, {"name": "Putenbrust Aufschnitt", "amount_g": 80}, {"name": "Frischkäse light", "amount_g": 30}, {"name": "Gurke", "amount_g": 50}]'::jsonb, 'Brötchen aufschneiden, bestreichen und belegen.', ARRAY['high_protein','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Putenbrust', 'Vollkornbrötchen'),
  ('Griechischer Joghurt mit Granola', 'Cremig und knusprig', 'breakfast'::meal_slot_kind, 405, 24.0, 48.0, 13.0, '1 Schale',
   '[{"name": "Griechischer Joghurt 2%", "amount_g": 250}, {"name": "Granola", "amount_g": 50}, {"name": "Himbeeren", "amount_g": 70}]'::jsonb, 'Joghurt einfüllen, Granola und Beeren darüber geben.', ARRAY['kalt','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Joghurt', 'Granola'),
  ('Haferflocken-Shake mit Whey', 'Trinkbares Frühstück für frühe Trainingstage', 'breakfast'::meal_slot_kind, 432, 38.0, 52.0, 8.0, '1 Shaker (500 ml)',
   '[{"name": "Milch 1,5%", "amount_g": 300}, {"name": "Haferflocken", "amount_g": 60}, {"name": "Whey Protein", "amount_g": 30}, {"name": "Banane", "amount_g": 100}]'::jsonb, 'Alle Zutaten mixen, sofort trinken.', ARRAY['high_protein','schnell','pre_workout']::text[], ARRAY[]::text[],
   true, false, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Whey', 'Haferflocken'),
  ('Shakshuka mit Vollkornbrot', 'Eier in würziger Tomatensauce', 'breakfast'::meal_slot_kind, 452, 28.0, 40.0, 20.0, '1 Pfanne + 1 Scheibe',
   '[{"name": "Eier", "amount_g": 165}, {"name": "Passierte Tomaten", "amount_g": 250}, {"name": "Paprika", "amount_g": 100}, {"name": "Zwiebel", "amount_g": 50}, {"name": "Vollkornbrot", "amount_g": 45}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb, 'Gemüse anbraten, Tomaten zugeben, Eier einschlagen und stocken lassen.', ARRAY['vegetarisch','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Ei', 'Vollkornbrot'),
  ('Veganer Tofu-Rührei-Toast', 'Pflanzliche Alternative zum Rührei', 'breakfast'::meal_slot_kind, 418, 26.0, 38.0, 18.0, '1 Portion',
   '[{"name": "Räuchertofu", "amount_g": 180}, {"name": "Vollkorntoast", "amount_g": 70}, {"name": "Kurkuma", "amount_g": 2}, {"name": "Zwiebel", "amount_g": 40}, {"name": "Rapsöl", "amount_g": 8}]'::jsonb, 'Tofu zerbröseln, mit Zwiebel und Kurkuma anbraten, auf Toast servieren.', ARRAY['vegan','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Tofu', 'Vollkornbrot'),
  ('Quarkspeise mit Leinsamen', 'Sättigend und ballaststoffreich', 'breakfast'::meal_slot_kind, 349, 34.0, 24.0, 13.0, '1 Schale',
   '[{"name": "Magerquark", "amount_g": 250}, {"name": "Leinsamen geschrotet", "amount_g": 20}, {"name": "Milch 1,5%", "amount_g": 60}, {"name": "Blaubeeren", "amount_g": 80}]'::jsonb, 'Quark mit Milch cremig rühren, Leinsamen und Beeren untermischen.', ARRAY['high_protein','low_carb','kalt','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Beeren'),
  ('Buchweizen-Porridge mit Mandelmus', 'Glutenfreie warme Variante', 'breakfast'::meal_slot_kind, 446, 17.0, 54.0, 18.0, '1 Schale',
   '[{"name": "Buchweizenflocken", "amount_g": 70}, {"name": "Hafermilch", "amount_g": 250}, {"name": "Mandelmus", "amount_g": 20}, {"name": "Apfel", "amount_g": 100}]'::jsonb, 'Flocken mit Hafermilch aufkochen, Mandelmus und Apfel unterrühren.', ARRAY['vegan','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Mandelmus', 'Buchweizen'),
  ('Vollkorn-Bagel mit Lachs', 'Pescetarischer Frühstücksklassiker', 'breakfast'::meal_slot_kind, 457, 30.0, 46.0, 17.0, '1 Bagel',
   '[{"name": "Vollkornbagel", "amount_g": 90}, {"name": "Räucherlachs", "amount_g": 80}, {"name": "Frischkäse light", "amount_g": 40}, {"name": "Rucola", "amount_g": 15}, {"name": "Zitrone", "amount_g": 5}]'::jsonb, 'Bagel halbieren, mit Frischkäse bestreichen, Lachs und Rucola auflegen.', ARRAY['pescetarisch','kalt','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'high'::meal_budget_level, 'Lachs', 'Bagel'),
  ('Käse-Vollkornstulle mit Ei', 'Deftig und günstig', 'breakfast'::meal_slot_kind, 453, 30.0, 36.0, 21.0, '2 Scheiben + 1 Ei',
   '[{"name": "Vollkornbrot", "amount_g": 90}, {"name": "Gouda 30%", "amount_g": 60}, {"name": "Ei", "amount_g": 55}, {"name": "Tomate", "amount_g": 60}]'::jsonb, 'Ei kochen, Brot mit Käse belegen, Ei und Tomate darauflegen.', ARRAY['günstig','kalt','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Käse', 'Vollkornbrot'),
  ('Chia-Pudding mit Mango', 'Am Vorabend angerührt', 'breakfast'::meal_slot_kind, 352, 14.0, 38.0, 16.0, '1 Glas',
   '[{"name": "Chiasamen", "amount_g": 30}, {"name": "Hafermilch", "amount_g": 250}, {"name": "Mango", "amount_g": 120}, {"name": "Ahornsirup", "amount_g": 8}]'::jsonb, 'Chia mit Hafermilch verrühren, über Nacht quellen lassen, Mango darüber.', ARRAY['vegan','mealprep','kalt']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Chia', 'Mango'),
  ('Herzhafte Haferflocken mit Ei', 'Salzige Porridge-Variante', 'breakfast'::meal_slot_kind, 432, 26.0, 46.0, 16.0, '1 Schale',
   '[{"name": "Haferflocken", "amount_g": 65}, {"name": "Gemüsebrühe", "amount_g": 250}, {"name": "Ei", "amount_g": 110}, {"name": "Frühlingszwiebel", "amount_g": 30}, {"name": "Käse gerieben", "amount_g": 20}]'::jsonb, 'Haferflocken in Brühe garen, Eier einrühren, mit Käse abrunden.', ARRAY['warm','high_protein','vegetarisch','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Ei', 'Haferflocken'),
  ('Beeren-Smoothie-Bowl mit Sojajoghurt', 'Kalte Bowl für warme Tage', 'breakfast'::meal_slot_kind, 380, 20.0, 48.0, 12.0, '1 Bowl',
   '[{"name": "Sojajoghurt", "amount_g": 250}, {"name": "Beerenmischung TK", "amount_g": 150}, {"name": "Haferflocken", "amount_g": 30}, {"name": "Kürbiskerne", "amount_g": 15}]'::jsonb, 'Joghurt und Beeren mixen, mit Haferflocken und Kernen toppen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojajoghurt', 'Beeren'),
  ('Vollkorn-Müsli mit Milch und Ei', 'Klassisch deutsch mit Extra-Protein', 'breakfast'::meal_slot_kind, 453, 29.0, 55.0, 13.0, '1 Schale + 1 Ei',
   '[{"name": "Vollkornmüsli", "amount_g": 70}, {"name": "Milch 1,5%", "amount_g": 250}, {"name": "Ei", "amount_g": 55}]'::jsonb, 'Müsli mit Milch anrichten, gekochtes Ei dazu essen.', ARRAY['klassisch','schnell','vegetarisch','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Milch', 'Müsli'),
  ('Low-Carb-Omelett mit Spinat und Feta', 'Kohlenhydratarmer Start', 'breakfast'::meal_slot_kind, 398, 33.0, 8.0, 26.0, '1 Omelett',
   '[{"name": "Eier", "amount_g": 220}, {"name": "Blattspinat", "amount_g": 120}, {"name": "Feta", "amount_g": 50}, {"name": "Olivenöl", "amount_g": 8}]'::jsonb, 'Spinat andünsten, Eier zugeben, Feta darüber, stocken lassen.', ARRAY['low_carb','vegetarisch','warm','high_protein']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Ei', 'Spinat'),
  ('Hähnchenbrust mit Reis und Brokkoli', 'Der Mealprep-Klassiker', 'lunch'::meal_slot_kind, 533, 48.0, 65.0, 9.0, '1 Portion',
   '[{"name": "Hähnchenbrust", "amount_g": 180}, {"name": "Reis gekocht", "amount_g": 250}, {"name": "Brokkoli", "amount_g": 200}, {"name": "Olivenöl", "amount_g": 8}]'::jsonb, 'Reis kochen, Hähnchen anbraten, Brokkoli dämpfen und alles anrichten.', ARRAY['mealprep','high_protein','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Reis'),
  ('Rindergeschnetzeltes mit Vollkornnudeln', 'Kräftiges Mittagessen für Trainingstage', 'lunch'::meal_slot_kind, 600, 46.0, 68.0, 16.0, '1 Teller',
   '[{"name": "Rinderstreifen", "amount_g": 170}, {"name": "Vollkornnudeln gekocht", "amount_g": 250}, {"name": "Paprika", "amount_g": 120}, {"name": "Zwiebel", "amount_g": 50}, {"name": "Rapsöl", "amount_g": 10}]'::jsonb, 'Fleisch scharf anbraten, Gemüse zugeben, mit Nudeln mischen.', ARRAY['high_protein','warm']::text[], ARRAY[]::text[],
   true, false, true, false,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Rind', 'Vollkornnudeln'),
  ('Linsen-Bolognese mit Vollkornspaghetti', 'Pflanzlich und sättigend', 'lunch'::meal_slot_kind, 548, 28.0, 82.0, 12.0, '1 Teller',
   '[{"name": "Rote Linsen", "amount_g": 80}, {"name": "Passierte Tomaten", "amount_g": 250}, {"name": "Vollkornspaghetti gekocht", "amount_g": 250}, {"name": "Zwiebel", "amount_g": 60}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb, 'Linsen mit Tomaten und Zwiebel köcheln, über Spaghetti geben.', ARRAY['vegan','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Vollkornnudeln'),
  ('Lachsfilet mit Kartoffeln und Salat', 'Pescetarisch mit guten Fetten', 'lunch'::meal_slot_kind, 550, 40.0, 48.0, 22.0, '1 Portion',
   '[{"name": "Lachsfilet", "amount_g": 170}, {"name": "Kartoffeln", "amount_g": 300}, {"name": "Blattsalat", "amount_g": 80}, {"name": "Olivenöl", "amount_g": 10}, {"name": "Zitrone", "amount_g": 10}]'::jsonb, 'Kartoffeln kochen, Lachs braten, Salat anmachen.', ARRAY['pescetarisch','high_protein','klassisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Lachs', 'Kartoffeln'),
  ('Putengeschnetzeltes mit Basmatireis', 'Mager und alltagstauglich', 'lunch'::meal_slot_kind, 540, 47.0, 70.0, 8.0, '1 Teller',
   '[{"name": "Putenbrust", "amount_g": 180}, {"name": "Basmatireis gekocht", "amount_g": 260}, {"name": "Champignons", "amount_g": 120}, {"name": "Rapsöl", "amount_g": 8}]'::jsonb, 'Pute anbraten, Champignons zugeben, mit Reis servieren.', ARRAY['high_protein','mealprep','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Pute', 'Reis'),
  ('Kichererbsen-Curry mit Reis', 'Würziges veganes Curry', 'lunch'::meal_slot_kind, 602, 22.0, 88.0, 18.0, '1 Teller',
   '[{"name": "Kichererbsen", "amount_g": 200}, {"name": "Kokosmilch light", "amount_g": 120}, {"name": "Reis gekocht", "amount_g": 250}, {"name": "Currypaste", "amount_g": 20}, {"name": "Spinat", "amount_g": 80}]'::jsonb, 'Currypaste anrösten, Kichererbsen und Kokosmilch zugeben, mit Reis servieren.', ARRAY['vegan','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Kichererbsen', 'Reis'),
  ('Thunfisch-Nudelsalat', 'Kalt essbar, perfekt fürs Büro', 'lunch'::meal_slot_kind, 534, 40.0, 62.0, 14.0, '1 Box',
   '[{"name": "Thunfisch in Wasser", "amount_g": 150}, {"name": "Vollkornnudeln gekocht", "amount_g": 220}, {"name": "Mais", "amount_g": 80}, {"name": "Paprika", "amount_g": 100}, {"name": "Joghurtdressing", "amount_g": 60}]'::jsonb, 'Alles vermengen und kühl stellen.', ARRAY['pescetarisch','kalt','mealprep','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Thunfisch', 'Vollkornnudeln'),
  ('Hackfleischpfanne mit Kartoffeln', 'Deftig und günstig', 'lunch'::meal_slot_kind, 568, 42.0, 55.0, 20.0, '1 Pfanne',
   '[{"name": "Rinderhack 5%", "amount_g": 180}, {"name": "Kartoffeln", "amount_g": 300}, {"name": "Zwiebel", "amount_g": 60}, {"name": "Paprika", "amount_g": 100}, {"name": "Rapsöl", "amount_g": 10}]'::jsonb, 'Hack anbraten, Kartoffelwürfel und Gemüse zugeben, garen.', ARRAY['günstig','klassisch','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Rinderhack', 'Kartoffeln'),
  ('Bulgur-Salat mit Feta und Kichererbsen', 'Frischer Meal-Prep-Salat', 'lunch'::meal_slot_kind, 572, 26.0, 72.0, 20.0, '1 Schale',
   '[{"name": "Bulgur gekocht", "amount_g": 220}, {"name": "Kichererbsen", "amount_g": 130}, {"name": "Feta", "amount_g": 60}, {"name": "Gurke", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 12}]'::jsonb, 'Bulgur abkühlen lassen, mit allen Zutaten mischen.', ARRAY['vegetarisch','kalt','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Feta', 'Bulgur'),
  ('Hähnchen-Wrap mit Joghurtsauce', 'Schnell zusammengerollt', 'lunch'::meal_slot_kind, 540, 44.0, 55.0, 16.0, '2 Wraps',
   '[{"name": "Hähnchenbrust", "amount_g": 170}, {"name": "Vollkorn-Wraps", "amount_g": 100}, {"name": "Joghurt 1,5%", "amount_g": 80}, {"name": "Salat", "amount_g": 60}, {"name": "Tomate", "amount_g": 60}]'::jsonb, 'Hähnchen braten, Wraps belegen, Sauce dazugeben und rollen.', ARRAY['high_protein','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Wrap'),
  ('Ofengemüse mit Halloumi', 'Vegetarisch und aromatisch', 'lunch'::meal_slot_kind, 574, 34.0, 42.0, 30.0, '1 Blech',
   '[{"name": "Halloumi", "amount_g": 150}, {"name": "Süßkartoffel", "amount_g": 250}, {"name": "Zucchini", "amount_g": 150}, {"name": "Paprika", "amount_g": 120}, {"name": "Olivenöl", "amount_g": 15}]'::jsonb, 'Gemüse mit Öl im Ofen 25 Minuten backen, Halloumi zuletzt zugeben.', ARRAY['vegetarisch','warm','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Halloumi', 'Süßkartoffel'),
  ('Chili sin Carne mit Reis', 'Proteinreiche vegane Bowl', 'lunch'::meal_slot_kind, 580, 26.0, 92.0, 12.0, '1 Teller',
   '[{"name": "Kidneybohnen", "amount_g": 200}, {"name": "Mais", "amount_g": 80}, {"name": "Passierte Tomaten", "amount_g": 200}, {"name": "Reis gekocht", "amount_g": 220}, {"name": "Olivenöl", "amount_g": 8}]'::jsonb, 'Alles zusammen 20 Minuten köcheln, mit Reis servieren.', ARRAY['vegan','mealprep','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Bohnen', 'Reis'),
  ('Gefüllte Süßkartoffel mit Hüttenkäse', 'Warm und cremig', 'lunch'::meal_slot_kind, 458, 30.0, 62.0, 10.0, '1 Süßkartoffel',
   '[{"name": "Süßkartoffel", "amount_g": 350}, {"name": "Hüttenkäse", "amount_g": 180}, {"name": "Schnittlauch", "amount_g": 10}, {"name": "Olivenöl", "amount_g": 6}]'::jsonb, 'Süßkartoffel im Ofen 45 Minuten garen, aufschneiden und füllen.', ARRAY['vegetarisch','warm','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hüttenkäse', 'Süßkartoffel'),
  ('Hähnchen-Reispfanne asiatisch', 'Ein-Pfannen-Gericht mit Gemüse', 'lunch'::meal_slot_kind, 580, 46.0, 72.0, 12.0, '1 Pfanne',
   '[{"name": "Hähnchenbrust", "amount_g": 180}, {"name": "Reis gekocht", "amount_g": 250}, {"name": "Asia-Gemüse TK", "amount_g": 200}, {"name": "Sojasauce", "amount_g": 15}, {"name": "Sesamöl", "amount_g": 10}]'::jsonb, 'Hähnchen anbraten, Gemüse und Reis zugeben, mit Sojasauce abschmecken.', ARRAY['high_protein','schnell','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Reis'),
  ('Vollkornnudeln mit Magerquark-Kräutersauce', 'Günstiger High-Protein-Teller', 'lunch'::meal_slot_kind, 552, 42.0, 78.0, 8.0, '1 Teller',
   '[{"name": "Vollkornnudeln gekocht", "amount_g": 250}, {"name": "Magerquark", "amount_g": 250}, {"name": "Kräuter", "amount_g": 15}, {"name": "Milch 1,5%", "amount_g": 60}]'::jsonb, 'Quark mit Milch und Kräutern glattrühren, über heiße Nudeln geben.', ARRAY['high_protein','günstig','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Vollkornnudeln'),
  ('Forelle mit Kartoffelsalat', 'Regional und pescetarisch', 'lunch'::meal_slot_kind, 522, 42.0, 48.0, 18.0, '1 Portion',
   '[{"name": "Forellenfilet", "amount_g": 180}, {"name": "Kartoffeln", "amount_g": 300}, {"name": "Gurke", "amount_g": 80}, {"name": "Joghurtdressing", "amount_g": 60}]'::jsonb, 'Forelle braten, Kartoffelsalat anrühren und dazu servieren.', ARRAY['pescetarisch','klassisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Forelle', 'Kartoffeln'),
  ('Couscous-Pfanne mit Hähnchen', 'Schnell und würzig', 'lunch'::meal_slot_kind, 596, 46.0, 76.0, 12.0, '1 Pfanne',
   '[{"name": "Hähnchenbrust", "amount_g": 170}, {"name": "Couscous gekocht", "amount_g": 250}, {"name": "Zucchini", "amount_g": 150}, {"name": "Paprika", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb, 'Couscous quellen lassen, Hähnchen und Gemüse anbraten, mischen.', ARRAY['schnell','high_protein']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Couscous'),
  ('Tofu-Reisbowl mit Erdnusssauce', 'Vegane Bowl mit Biss', 'lunch'::meal_slot_kind, 630, 30.0, 78.0, 22.0, '1 Bowl',
   '[{"name": "Räuchertofu", "amount_g": 200}, {"name": "Reis gekocht", "amount_g": 230}, {"name": "Brokkoli", "amount_g": 150}, {"name": "Erdnussmus", "amount_g": 20}, {"name": "Sojasauce", "amount_g": 12}]'::jsonb, 'Tofu anbraten, Brokkoli dämpfen, mit Reis und Sauce anrichten.', ARRAY['vegan','high_protein','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tofu', 'Reis'),
  ('Low-Carb Hähnchen-Zucchini-Pfanne', 'Kohlenhydratarmes Mittagessen', 'lunch'::meal_slot_kind, 418, 48.0, 16.0, 18.0, '1 Pfanne',
   '[{"name": "Hähnchenbrust", "amount_g": 200}, {"name": "Zucchini", "amount_g": 250}, {"name": "Paprika", "amount_g": 120}, {"name": "Feta", "amount_g": 40}, {"name": "Olivenöl", "amount_g": 12}]'::jsonb, 'Hähnchen würfeln, mit Gemüse braten, Feta darüber streuen.', ARRAY['low_carb','high_protein','schnell']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Zucchini'),
  ('Magerquark-Auflauf mit Gemüse', 'Warmer High-Protein-Auflauf', 'dinner'::meal_slot_kind, 438, 46.0, 32.0, 14.0, '1 Portion',
   '[{"name": "Magerquark", "amount_g": 250}, {"name": "Eier", "amount_g": 110}, {"name": "Brokkoli", "amount_g": 200}, {"name": "Käse gerieben", "amount_g": 40}]'::jsonb, 'Alles mischen, in Form geben und 25 Minuten backen.', ARRAY['high_protein','low_carb','warm','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Brokkoli'),
  ('Hähnchen mit Ofenkartoffeln und Kräuterquark', 'Sättigend am Abend', 'dinner'::meal_slot_kind, 508, 48.0, 52.0, 12.0, '1 Portion',
   '[{"name": "Hähnchenbrust", "amount_g": 180}, {"name": "Kartoffeln", "amount_g": 280}, {"name": "Magerquark", "amount_g": 120}, {"name": "Kräuter", "amount_g": 10}, {"name": "Olivenöl", "amount_g": 8}]'::jsonb, 'Kartoffeln im Ofen backen, Hähnchen braten, Kräuterquark anrühren.', ARRAY['high_protein','klassisch']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Kartoffeln'),
  ('Gemüsepfanne mit Rührei', 'Schnelles Abendessen aus dem Kühlschrank', 'dinner'::meal_slot_kind, 406, 28.0, 24.0, 22.0, '1 Pfanne',
   '[{"name": "Eier", "amount_g": 165}, {"name": "Zucchini", "amount_g": 150}, {"name": "Paprika", "amount_g": 120}, {"name": "Champignons", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb, 'Gemüse anbraten, Eier zugeben und stocken lassen.', ARRAY['vegetarisch','schnell','low_carb','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Ei', 'Gemüse'),
  ('Vollkornbrot-Abendbrot mit Aufschnitt', 'Klassisches deutsches Abendbrot', 'dinner'::meal_slot_kind, 456, 34.0, 44.0, 16.0, '3 Scheiben',
   '[{"name": "Vollkornbrot", "amount_g": 120}, {"name": "Putenbrust Aufschnitt", "amount_g": 60}, {"name": "Harzer Käse", "amount_g": 60}, {"name": "Gurke", "amount_g": 80}, {"name": "Tomate", "amount_g": 80}]'::jsonb, 'Brot belegen und mit Gemüse servieren.', ARRAY['klassisch','kalt','günstig','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Harzer Käse', 'Vollkornbrot'),
  ('Lachs mit Ofengemüse', 'Leicht und omega-3-reich', 'dinner'::meal_slot_kind, 488, 38.0, 30.0, 24.0, '1 Portion',
   '[{"name": "Lachsfilet", "amount_g": 170}, {"name": "Zucchini", "amount_g": 150}, {"name": "Paprika", "amount_g": 120}, {"name": "Kirschtomaten", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 12}]'::jsonb, 'Gemüse mit Lachs zusammen 20 Minuten im Ofen garen.', ARRAY['pescetarisch','low_carb','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'high'::meal_budget_level, 'Lachs', 'Gemüse'),
  ('Linsensalat mit Feta', 'Kalt und ballaststoffreich', 'dinner'::meal_slot_kind, 484, 28.0, 48.0, 20.0, '1 Schale',
   '[{"name": "Belugalinsen gekocht", "amount_g": 220}, {"name": "Feta", "amount_g": 60}, {"name": "Rucola", "amount_g": 40}, {"name": "Kirschtomaten", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 12}]'::jsonb, 'Alles vermengen und 10 Minuten ziehen lassen.', ARRAY['vegetarisch','kalt','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Feta', 'Linsen'),
  ('Puten-Gemüse-Curry mit Blumenkohlreis', 'Low Carb am Abend', 'dinner'::meal_slot_kind, 426, 46.0, 20.0, 18.0, '1 Teller',
   '[{"name": "Putenbrust", "amount_g": 180}, {"name": "Blumenkohlreis", "amount_g": 250}, {"name": "Kokosmilch light", "amount_g": 100}, {"name": "Currypulver", "amount_g": 8}, {"name": "Rapsöl", "amount_g": 10}]'::jsonb, 'Pute anbraten, Curry und Kokosmilch zugeben, mit Blumenkohlreis servieren.', ARRAY['low_carb','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Pute', 'Blumenkohl'),
  ('Ofen-Feta mit Tomaten und Vollkornbrot', 'Ein Blech, wenig Aufwand', 'dinner'::meal_slot_kind, 512, 28.0, 46.0, 24.0, '1 Portion',
   '[{"name": "Feta", "amount_g": 150}, {"name": "Kirschtomaten", "amount_g": 250}, {"name": "Vollkornbrot", "amount_g": 80}, {"name": "Olivenöl", "amount_g": 12}, {"name": "Knoblauch", "amount_g": 8}]'::jsonb, 'Feta mit Tomaten im Ofen 25 Minuten backen, mit Brot servieren.', ARRAY['vegetarisch','warm','schnell']::text[], ARRAY[]::text[],
   true, true, false, false,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Feta', 'Vollkornbrot'),
  ('Gemüsesuppe mit Hähnchen', 'Leicht und wärmend', 'dinner'::meal_slot_kind, 386, 40.0, 34.0, 10.0, '1 großer Teller',
   '[{"name": "Hähnchenbrust", "amount_g": 160}, {"name": "Gemüsebrühe", "amount_g": 500}, {"name": "Möhren", "amount_g": 120}, {"name": "Sellerie", "amount_g": 80}, {"name": "Kartoffeln", "amount_g": 150}]'::jsonb, 'Brühe aufsetzen, Gemüse und Hähnchen garen, abschmecken.', ARRAY['klassisch','warm','günstig','mealprep']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Hähnchen', 'Kartoffeln'),
  ('Vegane Bowl mit Tempeh und Quinoa', 'Pflanzlich und vollwertig', 'dinner'::meal_slot_kind, 574, 32.0, 62.0, 22.0, '1 Bowl',
   '[{"name": "Tempeh", "amount_g": 150}, {"name": "Quinoa gekocht", "amount_g": 200}, {"name": "Rotkohl", "amount_g": 80}, {"name": "Avocado", "amount_g": 60}, {"name": "Sesamöl", "amount_g": 10}]'::jsonb, 'Tempeh anbraten, mit Quinoa und Gemüse anrichten.', ARRAY['vegan','high_protein','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Tempeh', 'Quinoa'),
  ('Zucchini-Lasagne mit Hackfleisch', 'Low-Carb-Variante des Klassikers', 'dinner'::meal_slot_kind, 488, 44.0, 24.0, 24.0, '1 Portion',
   '[{"name": "Rinderhack 5%", "amount_g": 180}, {"name": "Zucchini", "amount_g": 300}, {"name": "Passierte Tomaten", "amount_g": 200}, {"name": "Käse gerieben", "amount_g": 50}]'::jsonb, 'Zucchini in Scheiben schichten, mit Hack und Tomaten füllen, überbacken.', ARRAY['low_carb','high_protein','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'high'::meal_effort_level, 'medium'::meal_budget_level, 'Rinderhack', 'Zucchini'),
  ('Kartoffelpuffer mit Kräuterquark', 'Deutscher Klassiker leichter gemacht', 'dinner'::meal_slot_kind, 506, 28.0, 58.0, 18.0, '3 Puffer',
   '[{"name": "Kartoffeln", "amount_g": 350}, {"name": "Ei", "amount_g": 55}, {"name": "Magerquark", "amount_g": 200}, {"name": "Rapsöl", "amount_g": 12}, {"name": "Kräuter", "amount_g": 10}]'::jsonb, 'Kartoffeln reiben, mit Ei binden, ausbacken und mit Quark servieren.', ARRAY['vegetarisch','klassisch','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Kartoffeln'),
  ('Garnelenpfanne mit Vollkornreis', 'Pescetarisch und mager', 'dinner'::meal_slot_kind, 500, 40.0, 58.0, 12.0, '1 Pfanne',
   '[{"name": "Garnelen", "amount_g": 180}, {"name": "Vollkornreis gekocht", "amount_g": 220}, {"name": "Zuckerschoten", "amount_g": 120}, {"name": "Knoblauch", "amount_g": 8}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb, 'Garnelen kurz braten, Gemüse zugeben, mit Reis mischen.', ARRAY['pescetarisch','high_protein','schnell']::text[], ARRAY[]::text[],
   true, true, true, false,
   'low'::meal_effort_level, 'high'::meal_budget_level, 'Garnelen', 'Vollkornreis'),
  ('Ofen-Hähnchenkeule mit Rosenkohl', 'Deftig und günstig', 'dinner'::meal_slot_kind, 506, 44.0, 24.0, 26.0, '1 Portion',
   '[{"name": "Hähnchenkeule", "amount_g": 250}, {"name": "Rosenkohl", "amount_g": 250}, {"name": "Olivenöl", "amount_g": 12}, {"name": "Senf", "amount_g": 10}]'::jsonb, 'Keule und Rosenkohl 35 Minuten im Ofen garen.', ARRAY['klassisch','low_carb','günstig']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Hähnchen', 'Rosenkohl'),
  ('Brotzeit-Teller mit Harzer und Ei', 'Sehr proteinreich, kalt', 'dinner'::meal_slot_kind, 412, 46.0, 30.0, 12.0, '1 Teller',
   '[{"name": "Harzer Käse", "amount_g": 120}, {"name": "Eier", "amount_g": 110}, {"name": "Vollkornbrot", "amount_g": 80}, {"name": "Radieschen", "amount_g": 60}, {"name": "Senf", "amount_g": 10}]'::jsonb, 'Eier kochen, alles auf einem Teller anrichten.', ARRAY['high_protein','kalt','günstig']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Harzer Käse', 'Vollkornbrot'),
  ('Süßkartoffel-Linsen-Eintopf', 'Wärmender veganer Eintopf', 'dinner'::meal_slot_kind, 500, 22.0, 76.0, 12.0, '1 Teller',
   '[{"name": "Rote Linsen", "amount_g": 80}, {"name": "Süßkartoffel", "amount_g": 250}, {"name": "Kokosmilch light", "amount_g": 80}, {"name": "Gemüsebrühe", "amount_g": 300}, {"name": "Zwiebel", "amount_g": 60}]'::jsonb, 'Alles 25 Minuten köcheln lassen und pürieren oder stückig lassen.', ARRAY['vegan','mealprep','günstig','warm']::text[], ARRAY[]::text[],
   true, true, true, false,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Linsen', 'Süßkartoffel'),
  ('Seelachs mit Kartoffelpüree und Erbsen', 'Leichtes Abendessen', 'dinner'::meal_slot_kind, 484, 42.0, 52.0, 12.0, '1 Portion',
   '[{"name": "Seelachsfilet", "amount_g": 200}, {"name": "Kartoffeln", "amount_g": 300}, {"name": "Milch 1,5%", "amount_g": 60}, {"name": "Erbsen", "amount_g": 120}, {"name": "Butter", "amount_g": 8}]'::jsonb, 'Kartoffeln stampfen, Fisch braten, Erbsen dünsten.', ARRAY['pescetarisch','klassisch','günstig']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Seelachs', 'Kartoffeln'),
  ('Bunter Salat mit gebratenem Hähnchen', 'Frisch und leicht', 'dinner'::meal_slot_kind, 392, 44.0, 18.0, 16.0, '1 große Schale',
   '[{"name": "Hähnchenbrust", "amount_g": 180}, {"name": "Blattsalat", "amount_g": 120}, {"name": "Kirschtomaten", "amount_g": 120}, {"name": "Gurke", "amount_g": 100}, {"name": "Olivenöl", "amount_g": 12}]'::jsonb, 'Hähnchen braten, Salat anmachen und Streifen darauflegen.', ARRAY['low_carb','high_protein','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Salat'),
  ('Vollkorn-Gemüse-Pizza mit Mozzarella', 'Freitagabend ohne Reue', 'dinner'::meal_slot_kind, 628, 36.0, 76.0, 20.0, '1/2 Blech',
   '[{"name": "Vollkornpizzateig", "amount_g": 200}, {"name": "Passierte Tomaten", "amount_g": 120}, {"name": "Mozzarella light", "amount_g": 125}, {"name": "Paprika", "amount_g": 100}, {"name": "Champignons", "amount_g": 80}]'::jsonb, 'Teig ausrollen, belegen und 15 Minuten backen.', ARRAY['vegetarisch','warm','klassisch']::text[], ARRAY[]::text[],
   true, true, false, true,
   'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Mozzarella', 'Pizzateig'),
  ('Rinderfilet mit grünen Bohnen', 'Proteinreich und kohlenhydratarm', 'dinner'::meal_slot_kind, 402, 46.0, 14.0, 18.0, '1 Portion',
   '[{"name": "Rinderfilet", "amount_g": 180}, {"name": "Grüne Bohnen", "amount_g": 250}, {"name": "Butter", "amount_g": 10}, {"name": "Knoblauch", "amount_g": 8}]'::jsonb, 'Filet scharf anbraten, Bohnen blanchieren und schwenken.', ARRAY['low_carb','high_protein']::text[], ARRAY[]::text[],
   true, true, false, false,
   'medium'::meal_effort_level, 'high'::meal_budget_level, 'Rind', 'Bohnen'),
  ('Skyr mit Honig', 'Schnelle Eiweißportion', 'snack'::meal_slot_kind, 136, 20.0, 14.0, 0.0, '1 Becher (150 g)',
   '[{"name": "Skyr natur", "amount_g": 150}, {"name": "Honig", "amount_g": 12}]'::jsonb, 'Skyr mit Honig verrühren.', ARRAY['high_protein','kalt','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Skyr', 'Honig'),
  ('Apfel mit Erdnussmus', 'Süß-salziger Snack', 'snack'::meal_slot_kind, 272, 8.0, 24.0, 16.0, '1 Apfel + 20 g',
   '[{"name": "Apfel", "amount_g": 180}, {"name": "Erdnussmus", "amount_g": 20}]'::jsonb, 'Apfel in Spalten schneiden und in Erdnussmus dippen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Erdnussmus', 'Apfel'),
  ('Proteinshake mit Wasser', 'Nach dem Training', 'snack'::meal_slot_kind, 130, 25.0, 3.0, 2.0, '1 Shaker',
   '[{"name": "Whey Protein", "amount_g": 30}, {"name": "Wasser", "amount_g": 300}]'::jsonb, 'Pulver mit Wasser shaken.', ARRAY['high_protein','post_workout','schnell']::text[], ARRAY[]::text[],
   true, false, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Whey', NULL),
  ('Handvoll Mandeln', 'Fettreicher Energie-Snack', 'snack'::meal_slot_kind, 268, 8.0, 5.0, 24.0, '30 g',
   '[{"name": "Mandeln", "amount_g": 30}]'::jsonb, 'Mandeln portionieren.', ARRAY['vegan','kalt','schnell','low_carb']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Mandeln', NULL),
  ('Hüttenkäse mit Gurke', 'Leichter Mini-Snack', 'snack'::meal_slot_kind, 120, 16.0, 5.0, 4.0, '1 Becher',
   '[{"name": "Hüttenkäse", "amount_g": 150}, {"name": "Gurke", "amount_g": 80}, {"name": "Pfeffer", "amount_g": 1}]'::jsonb, 'Hüttenkäse mit Gurkenscheiben anrichten.', ARRAY['high_protein','low_carb','kalt','vegetarisch','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hüttenkäse', 'Gurke'),
  ('Vollkornknäckebrot mit Frischkäse', 'Knuspriger Zwischendurch-Snack', 'snack'::meal_slot_kind, 216, 10.0, 26.0, 8.0, '2 Scheiben',
   '[{"name": "Vollkornknäckebrot", "amount_g": 40}, {"name": "Frischkäse light", "amount_g": 40}, {"name": "Radieschen", "amount_g": 40}]'::jsonb, 'Knäckebrot bestreichen und belegen.', ARRAY['vegetarisch','kalt','günstig','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Frischkäse', 'Knäckebrot'),
  ('Banane mit Magerquark', 'Vor dem Training', 'snack'::meal_slot_kind, 193, 16.0, 30.0, 1.0, '1 Portion',
   '[{"name": "Banane", "amount_g": 120}, {"name": "Magerquark", "amount_g": 150}]'::jsonb, 'Banane in Scheiben schneiden und in Quark rühren.', ARRAY['high_protein','pre_workout','kalt','günstig','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Banane'),
  ('Selbstgemachte Haferriegel', 'Mealprep für die Woche', 'snack'::meal_slot_kind, 300, 10.0, 38.0, 12.0, '1 Riegel',
   '[{"name": "Haferflocken", "amount_g": 50}, {"name": "Datteln", "amount_g": 40}, {"name": "Erdnussmus", "amount_g": 15}, {"name": "Wasser", "amount_g": 20}]'::jsonb, 'Alles mixen, in Form pressen, 15 Minuten backen und schneiden.', ARRAY['vegan','mealprep','kalt']::text[], ARRAY[]::text[],
   true, true, true, true,
   'medium'::meal_effort_level, 'low'::meal_budget_level, 'Erdnussmus', 'Haferflocken'),
  ('Reiswaffeln mit Hüttenkäse', 'Leicht und knusprig', 'snack'::meal_slot_kind, 207, 17.0, 28.0, 3.0, '3 Waffeln',
   '[{"name": "Reiswaffeln", "amount_g": 30}, {"name": "Hüttenkäse", "amount_g": 150}, {"name": "Schnittlauch", "amount_g": 5}]'::jsonb, 'Waffeln belegen und sofort essen.', ARRAY['vegetarisch','kalt','schnell','günstig']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hüttenkäse', 'Reiswaffeln'),
  ('Beeren mit Sojajoghurt', 'Leichter veganer Snack', 'snack'::meal_slot_kind, 173, 10.0, 22.0, 5.0, '1 Schale',
   '[{"name": "Sojajoghurt", "amount_g": 200}, {"name": "Beerenmischung TK", "amount_g": 120}]'::jsonb, 'Beeren auftauen und unter den Joghurt rühren.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Sojajoghurt', 'Beeren'),
  ('Gekochte Eier mit Salz', 'Purer Protein-Snack', 'snack'::meal_slot_kind, 194, 16.0, 1.0, 14.0, '2 Eier',
   '[{"name": "Eier", "amount_g": 120}, {"name": "Salz", "amount_g": 1}]'::jsonb, 'Eier 8 Minuten kochen, abschrecken und pellen.', ARRAY['high_protein','low_carb','kalt','günstig','vegetarisch','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Ei', NULL),
  ('Gemüsesticks mit Hummus', 'Ballaststoffreich und pflanzlich', 'snack'::meal_slot_kind, 228, 8.0, 22.0, 12.0, '1 Portion',
   '[{"name": "Möhren", "amount_g": 120}, {"name": "Paprika", "amount_g": 100}, {"name": "Hummus", "amount_g": 60}]'::jsonb, 'Gemüse in Sticks schneiden und in Hummus dippen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Hummus', 'Gemüse'),
  ('Proteinpudding mit Kakao', 'Süßer Abendsnack', 'snack'::meal_slot_kind, 179, 26.0, 12.0, 3.0, '1 Schale',
   '[{"name": "Magerquark", "amount_g": 200}, {"name": "Kakaopulver", "amount_g": 8}, {"name": "Milch 1,5%", "amount_g": 60}, {"name": "Süßstoff", "amount_g": 1}]'::jsonb, 'Alles cremig rühren und kalt stellen.', ARRAY['high_protein','low_carb','kalt','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Kakao'),
  ('Vollkornbrot mit Avocado', 'Gute Fette für zwischendurch', 'snack'::meal_slot_kind, 296, 8.0, 30.0, 16.0, '1 Scheibe',
   '[{"name": "Vollkornbrot", "amount_g": 60}, {"name": "Avocado", "amount_g": 80}, {"name": "Zitrone", "amount_g": 5}, {"name": "Chili", "amount_g": 1}]'::jsonb, 'Avocado zerdrücken, würzen, aufs Brot streichen.', ARRAY['vegan','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, false, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Avocado', 'Vollkornbrot'),
  ('Studentenfutter-Portion', 'Kompakter Energiesnack', 'snack'::meal_slot_kind, 304, 9.0, 22.0, 20.0, '40 g',
   '[{"name": "Nussmischung", "amount_g": 25}, {"name": "Rosinen", "amount_g": 15}]'::jsonb, 'Portionieren und mitnehmen.', ARRAY['vegan','kalt','schnell','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Nüsse', 'Rosinen'),
  ('Thunfisch auf Knäckebrot', 'Herzhaft und proteinreich', 'snack'::meal_slot_kind, 236, 26.0, 24.0, 4.0, '2 Scheiben',
   '[{"name": "Thunfisch in Wasser", "amount_g": 100}, {"name": "Vollkornknäckebrot", "amount_g": 40}, {"name": "Joghurt 1,5%", "amount_g": 30}, {"name": "Zwiebel", "amount_g": 20}]'::jsonb, 'Thunfisch mit Joghurt mischen und auf Knäckebrot geben.', ARRAY['pescetarisch','high_protein','kalt','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Thunfisch', 'Knäckebrot'),
  ('Edamame mit Meersalz', 'Pflanzlicher High-Protein-Snack', 'snack'::meal_slot_kind, 158, 14.0, 12.0, 6.0, '150 g',
   '[{"name": "Edamame TK", "amount_g": 150}, {"name": "Meersalz", "amount_g": 2}]'::jsonb, 'Edamame 5 Minuten kochen und salzen.', ARRAY['vegan','high_protein','warm','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Edamame', NULL),
  ('Quarkbrötchen mit Marmelade', 'Süßer Mealprep-Snack', 'snack'::meal_slot_kind, 244, 18.0, 34.0, 4.0, '1 Brötchen',
   '[{"name": "Vollkornbrötchen", "amount_g": 60}, {"name": "Magerquark", "amount_g": 120}, {"name": "Marmelade", "amount_g": 20}]'::jsonb, 'Brötchen aufschneiden, Quark und Marmelade darauf geben.', ARRAY['vegetarisch','kalt','günstig','schnell']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'low'::meal_budget_level, 'Quark', 'Vollkornbrötchen'),
  ('Käsewürfel mit Weintrauben', 'Kalter Snack für unterwegs', 'snack'::meal_slot_kind, 280, 16.0, 18.0, 16.0, '1 Portion',
   '[{"name": "Gouda 30%", "amount_g": 60}, {"name": "Weintrauben", "amount_g": 120}]'::jsonb, 'Käse würfeln und mit Trauben anrichten.', ARRAY['vegetarisch','kalt','schnell','low_carb']::text[], ARRAY[]::text[],
   true, true, true, true,
   'low'::meal_effort_level, 'medium'::meal_budget_level, 'Käse', 'Weintrauben')
) AS s(name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
       ingredients, instructions, tags, no_go_ingredients,
       suitable_training, suitable_rest, mealprep_ok, eat_cold,
       effort, budget, main_protein, main_carb)
WHERE NOT EXISTS (
  SELECT 1 FROM public.coach_meal_library existing
  WHERE lower(existing.name) = lower(s.name) AND existing.category = s.category
);

-- Nachtrag: vier weitere Gerichte, damit mindestens 100 aktive Gerichte vorhanden sind
INSERT INTO public.coach_meal_library (
  name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
  ingredients, instructions, tags, no_go_ingredients,
  suitable_training, suitable_rest, mealprep_ok, eat_cold,
  effort, budget, main_protein, main_carb, is_system, is_active
)
SELECT s.name, s.description, s.category, s.kcal, s.protein_g, s.carbs_g, s.fat_g, s.portion_label,
       s.ingredients, s.instructions, s.tags, s.no_go_ingredients,
       s.suitable_training, s.suitable_rest, s.mealprep_ok, s.eat_cold,
       s.effort, s.budget, s.main_protein, s.main_carb, true, true
FROM (VALUES
  ('Hirtensalat mit Ei und Vollkornbrot', 'Frischer Abendsalat mit Feta und Ei', 'dinner'::meal_slot_kind, 566, 30.0, 40.0, 30.0, '1 große Schale',
   '[{"name": "Feta", "amount_g": 80}, {"name": "Eier", "amount_g": 110}, {"name": "Gurke", "amount_g": 120}, {"name": "Tomate", "amount_g": 150}, {"name": "Vollkornbrot", "amount_g": 60}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb,
   'Gemüse würfeln, Eier kochen, alles mit Feta und Öl mischen, Brot dazu.', ARRAY['vegetarisch','kalt','schnell','high_protein']::text[], ARRAY[]::text[],
   true, true, false, true, 'low'::meal_effort_level, 'medium'::meal_budget_level, 'Feta', 'Vollkornbrot'),
  ('Pilzrisotto mit Hähnchen', 'Cremiges Risotto mit magerem Hähnchen', 'dinner'::meal_slot_kind, 646, 44.0, 68.0, 20.0, '1 Teller',
   '[{"name": "Hähnchenbrust", "amount_g": 160}, {"name": "Risottoreis gekocht", "amount_g": 230}, {"name": "Champignons", "amount_g": 150}, {"name": "Parmesan", "amount_g": 20}, {"name": "Olivenöl", "amount_g": 10}]'::jsonb,
   'Reis mit Brühe cremig garen, Pilze und Hähnchen anbraten, unterheben, mit Parmesan abrunden.', ARRAY['warm','klassisch','high_protein']::text[], ARRAY[]::text[],
   true, true, true, false, 'medium'::meal_effort_level, 'medium'::meal_budget_level, 'Hähnchen', 'Reis'),
  ('Skyr mit Zimt und Walnüssen', 'Cremiger Snack mit gesunden Fetten', 'snack'::meal_slot_kind, 303, 22.0, 10.0, 19.0, '1 Becher',
   '[{"name": "Skyr natur", "amount_g": 150}, {"name": "Walnüsse", "amount_g": 25}, {"name": "Zimt", "amount_g": 2}]'::jsonb,
   'Skyr mit Zimt verrühren und Walnüsse darüber streuen.', ARRAY['high_protein','low_carb','kalt','schnell','vegetarisch']::text[], ARRAY[]::text[],
   true, true, true, true, 'low'::meal_effort_level, 'medium'::meal_budget_level, 'Skyr', 'Walnüsse'),
  ('Vollkornwrap mit Frischkäse und Pute', 'Handlicher Snack für unterwegs', 'snack'::meal_slot_kind, 318, 25.0, 32.0, 9.0, '1 halber Wrap',
   '[{"name": "Vollkorn-Wrap", "amount_g": 50}, {"name": "Putenbrust Aufschnitt", "amount_g": 60}, {"name": "Frischkäse light", "amount_g": 30}, {"name": "Salat", "amount_g": 30}]'::jsonb,
   'Wrap bestreichen, belegen, aufrollen und halbieren.', ARRAY['high_protein','kalt','schnell','mealprep']::text[], ARRAY[]::text[],
   true, true, true, true, 'low'::meal_effort_level, 'medium'::meal_budget_level, 'Putenbrust', 'Wrap')
) AS s(name, description, category, kcal, protein_g, carbs_g, fat_g, portion_label,
       ingredients, instructions, tags, no_go_ingredients,
       suitable_training, suitable_rest, mealprep_ok, eat_cold,
       effort, budget, main_protein, main_carb)
WHERE NOT EXISTS (
  SELECT 1 FROM public.coach_meal_library existing
  WHERE lower(existing.name) = lower(s.name) AND existing.category = s.category
);
