import type { PerformanceProfile } from "./types";

// Football (Coesfeld Bulls) performance profile — V1.
// Benchmarks are position-group specific and are DELIBERATELY conservative starting points
// derived from public combine/scouting data. Coaches can iterate later.
//
// Format for each benchmark tuple: [score_0_value, score_100_value].
// For lower_is_better metrics (times), score_0 is the SLOW anchor and score_100 the FAST anchor.
// For higher_is_better metrics (cm, kg), score_0 is the LOW anchor and score_100 the HIGH anchor.

export const footballBullsProfile: PerformanceProfile = {
  id: "football_bulls",
  name: "Bulls Football Performance",
  positions: {
    QB: "SKILL", WR: "SKILL", DB: "SKILL",
    RB: "HYBRID", TE: "HYBRID", LB: "HYBRID",
    OL: "LINE", DL: "LINE",
    K: "SPECIALIST", P: "SPECIALIST", KP: "SPECIALIST",
  },
  moduleWeights: {
    SKILL:      { speed: 0.35, agility: 0.25, power: 0.20, strength: 0.20 },
    HYBRID:     { speed: 0.20, agility: 0.20, power: 0.25, strength: 0.35 },
    LINE:       { speed: 0.10, agility: 0.15, power: 0.25, strength: 0.50 },
    SPECIALIST: { speed: 0.15, agility: 0.20, power: 0.40, strength: 0.25 },
  },
  modules: [
    {
      id: "speed",
      name: "Speed",
      tests: [
        {
          id: "sprint_10y",
          moduleId: "speed",
          name: "10 Yard Sprint",
          short: "Acceleration / Antritt",
          unit: "s",
          direction: "lower_is_better",
          instructions: [
            "Markiere Start- und 10-Yard-Linie auf gerader Strecke.",
            "Aus athletischer Startposition (kein fliegender Start).",
            "Maximal bis über die Ziellinie sprinten.",
            "Mindestens 2 Versuche, bestes gültiges Ergebnis eintragen.",
          ],
          equipment: ["Maßband", "Startlinie & Ziellinie", "Stoppuhr oder Videokamera"],
          videoRequirements: [
            "Startposition sichtbar",
            "Startlinie sichtbar",
            "Vollständiger Sprint im Bild",
            "Ziellinie sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=Q5nY7iBd8dU",
          inputs: { measurementMethod: true, surface: true, footwear: true },
          benchmarks: {
            SKILL:      [2.10, 1.55],
            HYBRID:     [2.20, 1.65],
            LINE:       [2.40, 1.80],
            SPECIALIST: [2.20, 1.65],
          },
        },
        {
          id: "sprint_40y",
          moduleId: "speed",
          name: "40 Yard Dash",
          short: "Acceleration & Sprint Speed",
          unit: "s",
          direction: "lower_is_better",
          instructions: [
            "Markiere Start- und 40-Yard-Linie.",
            "Aus athletischer Startposition.",
            "Maximal bis über die Ziellinie sprinten.",
            "Mindestens 2 Versuche, bestes gültiges Ergebnis eintragen.",
          ],
          equipment: ["Maßband", "Startlinie & Ziellinie", "Stoppuhr oder Videokamera"],
          videoRequirements: [
            "Startposition sichtbar",
            "Startlinie sichtbar",
            "Vollständiger Sprint im Bild",
            "Ziellinie sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=UYlaMxjw4CQ",
          inputs: { measurementMethod: true, surface: true, footwear: true },
          benchmarks: {
            SKILL:      [5.20, 4.35],
            HYBRID:     [5.40, 4.55],
            LINE:       [5.90, 4.90],
            SPECIALIST: [5.40, 4.60],
          },
        },
      ],
    },
    {
      id: "agility",
      name: "Agility",
      tests: [
        {
          id: "pro_agility_5_10_5",
          moduleId: "agility",
          name: "5-10-5 Pro Agility",
          short: "Change of Direction / laterale Agility",
          unit: "s",
          direction: "lower_is_better",
          instructions: [
            "Drei Linien im Abstand von 5 Yards markieren (LINKS – MITTE – RECHTS).",
            "Start an der Mittellinie in athletischer Position.",
            "Sprint 5 Yards zu einer Seite, Linie mit der Hand berühren.",
            "10 Yards zur gegenüberliegenden Linie, Linie mit der Hand berühren.",
            "5 Yards zurück durch die Mitte.",
            "Mindestens 2 Versuche, bestes gültiges Ergebnis eintragen.",
          ],
          equipment: ["Maßband", "3 Bodenmarkierungen", "Stoppuhr oder Videokamera"],
          videoRequirements: [
            "Kompletter Aufbau mit allen drei Linien sichtbar",
            "Vollständiger Testablauf im Bild",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=fVXVKuOfp5U",
          inputs: { measurementMethod: true, surface: true, footwear: true },
          benchmarks: {
            SKILL:      [5.20, 4.10],
            HYBRID:     [5.40, 4.25],
            LINE:       [5.80, 4.55],
            SPECIALIST: [5.30, 4.20],
          },
        },
      ],
    },
    {
      id: "power",
      name: "Power",
      tests: [
        {
          id: "broad_jump",
          moduleId: "power",
          name: "Standing Broad Jump",
          short: "Horizontal Explosive Power",
          unit: "cm",
          direction: "higher_is_better",
          instructions: [
            "Füße hinter der Startlinie.",
            "Beidbeiniger Absprung, freie Armbewegung erlaubt.",
            "Beidbeinige Landung.",
            "Entfernung von Startlinie bis zur hintersten Ferse messen.",
            "3 Versuche, bestes gültiges Ergebnis eintragen.",
          ],
          equipment: ["Maßband", "Startlinie", "Landefläche"],
          videoRequirements: [
            "Startlinie sichtbar",
            "Absprung vollständig im Bild",
            "Landung vollständig im Bild",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=hZ8gk28RTaI",
          inputs: { surface: true, footwear: true },
          benchmarks: {
            SKILL:      [220, 305],
            HYBRID:     [210, 295],
            LINE:       [190, 275],
            SPECIALIST: [215, 295],
          },
        },
      ],
    },
    {
      id: "strength",
      name: "Strength",
      tests: [
        {
          id: "back_squat",
          moduleId: "strength",
          name: "Back Squat / Kniebeuge",
          short: "Unterkörper-Kraft",
          unit: "kg",
          direction: "higher_is_better",
          instructions: [
            "Volle Tiefe (Oberschenkel mind. parallel).",
            "Kontrollierte Ausführung, aufrechter Rumpf.",
            "Gewicht und Wiederholungen eintragen (RPE/RIR angeben).",
            "Bodyweight am Testtag mit angeben.",
          ],
          equipment: ["Langhantel", "Rack", "Sicherheitsablagen"],
          videoRequirements: [
            "Ganzer Körper im Bild",
            "Seitliche Perspektive",
            "Vollständiger Satz sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=SW_C1A-rejs",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [80, 190],
            HYBRID:     [100, 220],
            LINE:       [130, 260],
            SPECIALIST: [80, 180],
          },
        },
        {
          id: "bench_press",
          moduleId: "strength",
          name: "Bench Press / Bankdrücken",
          short: "Oberkörper-Druckkraft",
          unit: "kg",
          direction: "higher_is_better",
          instructions: [
            "Rücken, Kopf, Gesäß in Kontakt mit Bank.",
            "Kontrolliert bis Brust senken, sauber drücken.",
            "Kein Bounce.",
          ],
          equipment: ["Langhantel", "Bank", "Ablage/Spotter"],
          videoRequirements: [
            "Seitliche Perspektive",
            "Vollständige Reps sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [60, 145],
            HYBRID:     [80, 165],
            LINE:       [100, 195],
            SPECIALIST: [60, 140],
          },
        },
        {
          id: "deadlift",
          moduleId: "strength",
          name: "Deadlift",
          short: "Ganzkörper-Kraft",
          unit: "kg",
          direction: "higher_is_better",
          variants: [
            { id: "trap_bar", label: "Trap Bar Deadlift" },
            { id: "conventional", label: "Conventional Deadlift" },
          ],
          instructions: [
            "Neutraler Rücken vom Boden weg.",
            "Volle Streckung von Hüfte und Knie in der Endposition.",
            "Kontrolliertes Ablassen.",
          ],
          equipment: ["Trap Bar oder Langhantel", "Scheiben"],
          videoRequirements: [
            "Seitliche Perspektive",
            "Vollständige Reps sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [100, 230],
            HYBRID:     [130, 260],
            LINE:       [160, 300],
            SPECIALIST: [100, 220],
          },
        },
        {
          id: "pull_up",
          moduleId: "strength",
          name: "Pull-Up",
          short: "Oberkörper-Zugkraft",
          unit: "kg",
          direction: "higher_is_better",
          variants: [
            { id: "pull_up", label: "Pull-Up (Zusatzgewicht)" },
            { id: "lat_pulldown", label: "Lat Pulldown" },
          ],
          instructions: [
            "Volle Streckung im Hang, Kinn über Stange.",
            "Ohne Schwung.",
            "Bei Pull-Up: Zusatzgewicht als Wert eintragen (0 = Körpergewicht).",
          ],
          equipment: ["Klimmzugstange oder Latmaschine", "Gürtel für Zusatzgewicht"],
          videoRequirements: [
            "Frontal- oder Seitenperspektive",
            "Alle Reps sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [0, 45],
            HYBRID:     [0, 50],
            LINE:       [0, 40],
            SPECIALIST: [0, 40],
          },
        },
        {
          id: "overhead_press",
          moduleId: "strength",
          name: "Overhead Press / Schulterdrücken",
          short: "Vertikale Druckkraft",
          unit: "kg",
          direction: "higher_is_better",
          instructions: [
            "Stehend, Langhantel oder Kurzhanteln.",
            "Volle Streckung über Kopf.",
            "Kein übermäßiges Hohlkreuz.",
          ],
          equipment: ["Langhantel oder Kurzhanteln"],
          videoRequirements: [
            "Frontal- oder Seitenperspektive",
            "Vollständige Reps sichtbar",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=2yjwXTZQDDI",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [40, 100],
            HYBRID:     [50, 115],
            LINE:       [60, 130],
            SPECIALIST: [40, 95],
          },
        },
        {
          id: "single_leg_strength",
          moduleId: "strength",
          name: "Single Leg Strength",
          short: "Einbein-Kraft",
          unit: "kg",
          direction: "higher_is_better",
          variants: [
            { id: "bulgarian_split_squat", label: "Bulgarian Split Squat" },
            { id: "single_leg_press", label: "Single Leg Press" },
          ],
          instructions: [
            "Einbein-Übung — je Bein sauber ausführen.",
            "Gewicht pro Bein (nicht bilaterale Summe).",
            "Kontrollierte Bewegung, volle Amplitude.",
          ],
          equipment: ["Kurzhanteln oder Beinpresse", "Bank für Split Squat"],
          videoRequirements: [
            "Seitliche Perspektive",
            "Beide Seiten oder mindestens die getestete Seite vollständig",
          ],
          demoVideoUrl: "https://www.youtube.com/watch?v=2C-uNgKwPLE",
          inputs: { reps: true, rir: true, bodyweight: true },
          benchmarks: {
            SKILL:      [30, 100],
            HYBRID:     [40, 120],
            LINE:       [50, 140],
            SPECIALIST: [30, 95],
          },
        },
      ],
    },
  ],
};
